using UnityEngine;
using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace WitchPlayground {
public sealed partial class AdventureVerification:MonoBehaviour {
 static bool launched;string folder;float began;bool done;int errors;readonly List<string> checks=new List<string>(),failures=new List<string>();RpgSession session;RpgProgress stats;WitchPlayer p;AdventureProgress a;HeroRoster roster;string savedTest;bool hadTest;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Init(){var args=Environment.GetCommandLineArgs();int i=Array.IndexOf(args,"--adventure-verify");if(!launched&&i>=0&&i+1<args.Length){launched=true;var test=new GameObject("Adventure verification").AddComponent<AdventureVerification>();test.folder=args[i+1];Application.runInBackground=true;}}
 void Check(bool value,string text){(value?checks:failures).Add(text);Debug.Log((value?"ADVENTURE PASS ":"ADVENTURE FAIL ")+text);}
 void ClearUI(){while(stats.PendingChoices>0)stats.Choose(0);if(RpgUI.Instance.ActiveWindow!=RpgUI.Window.None)RpgUI.Instance.Close();RpgUI.Instance.ReleaseInputForTest();Time.timeScale=1;p.ProcessButtons(false,false,false,Vector3.zero);}
 IEnumerator Wait(float duration){yield return new WaitForSecondsRealtime(duration);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(folder,name+".png"));yield return null;}
 void Kill(string id){var e=a.Enemies[id];if(e.gameObject.activeSelf&&!e.IsDead)e.ReceiveHit(new HitData{damage=e.maxHealth+100,owner=p,direction=Vector3.forward});ClearUI();}
 bool Node(string id,Vector3 at){p.Teleport(at);Camera.main.GetComponent<PlaygroundView>().Snap();Physics.SyncTransforms();ClearUI();return a.Interact(id);}
 void RoundTrip(string label){string before=a.Export();session.Save();Check(session.LoadGame(),label+" loads");Check(a.Export()==before,label+" preserves quest and relic state");ClearUI();}
 IEnumerator Start(){began=Time.realtimeSinceStartup;Directory.CreateDirectory(folder);Application.logMessageReceived+=Log;yield return Wait(.6f);p=FindAnyObjectByType<WitchPlayer>();stats=p.GetComponent<RpgProgress>();roster=p.GetComponent<HeroRoster>();session=p.GetComponent<RpgSession>();a=p.GetComponent<AdventureProgress>();p.TestControl=true;a.TestFreezeEnemies=true;hadTest=PlayerPrefs.HasKey("WitchRPG.Test.v4");savedTest=PlayerPrefs.GetString("WitchRPG.Test.v4","");session.AllowTestStorage=true;
 if(Array.IndexOf(Environment.GetCommandLineArgs(),"--live-ai")>=0){yield return LiveAI();yield break;}
 Check(a&&a.Ready,"Adventure initializes on existing forest terrain");Check(Shader.GetGlobalVector("_AdventureClearing").w>5,"Boss arena foliage clearing is configured");Check(a.Enemies.Count==11,"Four road enemies, four site guards, three elite encounter enemies");Check(a.Enemies.Values.All(e=>e.persistentDefeat),"Quest enemies never respawn for farming");
 // Title preview uses the same pointer reducer as actual mouse polling; radius stays fixed.
 session.ShowTitleForTest();session.Creating=true;yield return Wait(.15f);var rotation=p.transform.rotation;float zoom=roster.previewCamera.orthographicSize;var rect=new Rect(200,185,326,407.5f);roster.PreviewInput(rect,true);roster.PollPreview(rect.center,true,true);roster.PollPreview(rect.center+new Vector2(110,40),false,true);yield return Wait(.15f);Check(Mathf.Abs(roster.PreviewYaw)>45&&roster.PreviewPitch>10,"Preview drag changes yaw and pitch while the menu is paused");Check(Mathf.Abs(roster.previewCamera.orthographicSize-zoom)<.001f&&p.transform.rotation==rotation,"Preview rotation preserves zoom and player orientation");yield return Shot("character-orbit");roster.PollPreview(rect.center,false,false);
 for(int hero=0;hero<3;hero++){
  Check(session.NewGame("Adventure"+hero,hero),"Hero "+hero+" creates a fresh adventure");ClearUI();yield return Wait(.15f);var camera=Camera.main.GetComponent<PlaygroundView>().Capture();Check(Mathf.Abs(camera.pitch-29.3f)<.001f&&Mathf.Abs(camera.yaw-144.1f)<.001f&&Mathf.Abs(camera.zoom-6.004f)<.001f&&camera.height==.6f&&camera.distance==14&&camera.follow==10&&camera.sensitivity==3&&camera.zoomStep==.28f&&camera.orthographic,"New game uses all nine screenshot camera settings");Check(a.Stage==AdventureStage.Offer&&a.Relics.State.owned==0,"New game resets only adventure progress and owned relics");Check(a.GuideMarker=="?","Available quest displays question mark over Lumi");if(hero==0)yield return Shot("quest-available");session.Kills=99;yield return Wait(.15f);Check(!MoonwolfEvent.Instance.Summoned,"Kill count alone never summons story boss");session.Kills=0;
  Check(a.AcceptMain(),"Hero "+hero+" accepts Lumi request");Check(!a.AcceptMain(),"Main request cannot be accepted twice");Check(a.GuideMarker=="","Quest offer marker hides while the quest is in progress");yield return Wait(.1f);Kill("road0");Check(a.RoadKills==1,"First designated road enemy counts once");a.EnemyDefeated(a.Enemies["road0"]);Check(a.RoadKills==1,"Duplicate death event cannot advance objective twice");RoundTrip("Road checkpoint");Check(!a.Enemies["road0"].gameObject.activeSelf,"Defeated road enemy stays gone after load");Kill("road1");Kill("road2");Kill("road3");Check(a.Stage==AdventureStage.Purify&&stats.Level>=2,"Road clear grants a level and unlocks purification");yield return Wait(.1f);Check(!Node("site0",a.Sites[0]),"Purification requires its guards to be defeated");Kill("site0a");Kill("site0b");Check(Node("site0",a.Sites[0])&&a.SiteCount==1,"First site can be purified after combat");RoundTrip("Purification checkpoint");Check(!Node("site0",a.Sites[0]),"Purified site cannot be collected twice");Kill("site1a");Kill("site1b");Check(Node("site1",a.Sites[1])&&a.Stage==AdventureStage.Gate,"Two sites unlock the boss refuge");ClearUI();yield return Wait(.1f);Check(Node("gate",a.Gate)&&p.Spawn==a.Gate,"Refuge restores player and records safe checkpoint");if(hero==0)yield return Shot("boss-refuge");Check(a.EnterBoss(),"Hero "+hero+" explicitly enters fixed boss encounter");ClearUI();yield return Wait(.1f);var boss=MoonwolfEvent.Instance.boss.GetComponent<SlimeMonster>();boss.TestIdle=true;Check(ClassCombat.Flat(boss.transform.position-a.Arena).magnitude<.1f&&boss.Health==1400,"Moonwolf appears at authored arena with full health");if(hero==0){p.Teleport(AdventureProgress.Safe(a.Arena+Vector3.forward*4));Camera.main.GetComponent<PlaygroundView>().Snap();yield return Wait(.3f);yield return Shot("boss-arena");}boss.ReceiveHit(new HitData{damage=10});MoonwolfEvent.Instance.boss.GetComponent<MoonwolfBoss>().Cast(MoonwolfBoss.Skill.Charge);yield return Wait(.15f);Check(FindObjectsByType<RasterEffect>().Any(f=>f.loop),"Boss attack creates warning markers");var warnings=MoonwolfEvent.Instance.boss.GetComponent<MoonwolfBoss>().Warnings.ToArray();p.Respawn();ClearUI();yield return Wait(.1f);Check(a.Stage==AdventureStage.Gate&&!boss.gameObject.activeSelf,"Respawn preserves quest but resets boss encounter");Check(warnings.All(f=>!f),"Boss reset removes every outstanding warning marker");
  Node("gate",a.Gate);a.EnterBoss();ClearUI();yield return Wait(.1f);boss.TestIdle=true;Check(boss.Health==1400,"Retry restores full boss health");session.Save();Check(session.LoadGame()&&a.Stage==AdventureStage.Gate&&!boss.gameObject.activeSelf,"Loading mid-boss resumes safely at refuge");ClearUI();Node("gate",a.Gate);a.EnterBoss();ClearUI();yield return Wait(.1f);boss.TestIdle=true;boss.ReceiveHit(new HitData{damage=5000,owner=p});ClearUI();yield return Wait(.1f);Check(a.Stage==AdventureStage.Reward&&session.BossDefeated,"Boss defeat unlocks reward and records liberation");RoundTrip("Unclaimed boss reward");if(hero==0){RpgUI.Instance.Open(RpgUI.Window.Adventure);yield return Shot("boss-reward-ko");Loc.Language=1;yield return Shot("boss-reward-en");Loc.Language=2;yield return Shot("boss-reward-ja");Loc.Language=0;ClearUI();}
  Check(a.ChooseRelic(hero),"Hero "+hero+" receives chosen relic");Check(!a.ChooseRelic((hero+1)%3),"Boss reward cannot be claimed twice");ClearUI();Check(a.Relics.State.equipped==hero&&a.Stage==AdventureStage.Camp&&ClassCombat.Flat(p.transform.position-a.Camp).magnitude<.1f,"Reward equips relic and returns to camp");RoundTrip("Owned relic");Check(a.GuideMarker=="!","Completed quest marker survives reward and reload");if(hero==0)yield return Shot("quest-complete");a.TalkGuide();Check(a.GuideMarker=="?","Talking to Lumi acknowledges completion and shows next quest");ClearUI();
  Check(a.AcceptSide(hero%2),"Either follow-up request can be chosen first");if(a.Stage==AdventureStage.Elite){yield return Wait(.1f);Kill("elite0");Kill("elite1");Kill("elite2");Check(Node("elite",a.Sites[0]),"Elite bee and guards must fall before cleansing");}else{Check(Node("herb0",a.Herbs[0]),"First herb is gathered");RoundTrip("Herb checkpoint");Check(!Node("herb0",a.Herbs[0]),"Herb is not collectible twice");Node("herb1",a.Herbs[1]);Node("herb2",a.Herbs[2]);}
  Check(a.Stage==AdventureStage.Reward,"First follow-up grants a reward");Check(a.ChooseRelic((hero+1)%3),"Remaining relic is awarded");ClearUI();Check(!a.AcceptSide(hero%2),"Completed follow-up cannot be accepted twice");Check(a.AcceptSide(1-hero%2),"Unchosen request remains available");if(a.Stage==AdventureStage.Elite){yield return Wait(.1f);Kill("elite0");Kill("elite1");Kill("elite2");Node("elite",a.Sites[0]);}else{Node("herb0",a.Herbs[0]);Node("herb1",a.Herbs[1]);Node("herb2",a.Herbs[2]);}Check(a.ChooseRelic((hero+2)%3),"Final unique relic is awarded");ClearUI();Check(a.Stage==AdventureStage.Complete&&a.State.sideDone==3&&a.Relics.State.owned==7,"Hero "+hero+" completes all available adventures");RoundTrip("Completed adventure");
  a.Relics.Equip(0);a.Relics.OnKill();Check(Mathf.Abs(a.Relics.MoveMultiplier-1.2f)<.001f,"Windleaf grants bounded movement bonus");a.Relics.Equip(1);a.Relics.OnDodge();a.Relics.OnDodge();var hit=new HitData{damage=100};Check(a.Relics.BasicHit(hit).damage==130&&a.Relics.BasicHit(hit).damage==100,"Moonlit Echo buffs exactly one basic attack without stacking");a.Relics.Equip(2);stats.SetManaForTest(0);a.Relics.OnKill();Check(Mathf.Abs(stats.Mana-stats.MaxMana*.12f)<.01f,"Spring Crystal restores exactly twelve percent MP");a.Relics.Equip(-1);Check(a.Relics.MoveMultiplier==1&&!a.Relics.Empowered,"Unequipping clears temporary relic benefits");
 }
 // Migration retains character progression; old victories are not forced through the first quest again.
 int level=stats.Level;a.Import("",true);Check(a.Stage==AdventureStage.Reward&&stats.Level==level,"Legacy boss-clear saves migrate directly to their unclaimed relic");a.Import("",false);Check(a.Stage==AdventureStage.Offer&&stats.Level==level&&p.Spawn==a.Camp,"Legacy non-boss saves retain stats and start at camp");
 ClearUI();Check(a.CanReturnCamp,"Safe camp return is available outside combat");a.PlayerDamaged();Check(!a.CanReturnCamp,"Recent damage blocks instant camp healing");yield return Wait(5.1f);Check(a.CanReturnCamp,"Camp return unlocks after five safe seconds");
 session.NewGame("ForestWalker",0);ClearUI();yield return Wait(.2f);a.AcceptMain();ClearUI();yield return Wait(.1f);a.TestFreezeEnemies=true;foreach(var e in a.Enemies.Values)e.TestIdle=true;
 // Use actual character controller and camera-relative movement through the existing forest.
 for(int hero=0;hero<3;hero++){roster.Select(hero);p.Teleport(a.Camp);yield return Wait(.15f);var waypoints=new[]{new Vector3(1,0,22),new Vector3(5,0,18),new Vector3(8,0,15),new Vector3(12,0,12),new Vector3(14,0,9),a.Sites[0],new Vector3(6,0,0),a.Sites[1],a.Gate,a.Arena};foreach(var point in waypoints){float end=Time.realtimeSinceStartup+9;while(ClassCombat.Flat(point-p.transform.position).magnitude>.8f&&Time.realtimeSinceStartup<end){var dir=ClassCombat.Flat(point-p.transform.position).normalized;var f=ClassCombat.Flat(Camera.main.transform.forward).normalized;var r=ClassCombat.Flat(Camera.main.transform.right).normalized;p.TestMovement=new Vector2(Vector3.Dot(dir,r),Vector3.Dot(dir,f));p.TestRunning=true;yield return null;}Check(ClassCombat.Flat(point-p.transform.position).magnitude<=.8f,"Hero "+hero+" physically reaches route waypoint "+point);p.TestMovement=Vector2.zero;}p.TestRunning=false;}
 p.Teleport(a.Camp);Camera.main.GetComponent<PlaygroundView>().Snap();ClearUI();Loc.Language=0;yield return Wait(.4f);yield return Shot("objective-hud");RpgUI.Instance.Open(RpgUI.Window.Bag);yield return Shot("relic-bag");Check(errors==0,"No runtime errors");Finish(null);
 }
 void Log(string m,string stack,LogType type){if(type==LogType.Error||type==LogType.Exception){errors++;File.AppendAllText(Path.Combine(folder,"errors.txt"),m+"\n"+stack+"\n");}}
 void Update(){if(!done&&began>0&&Time.realtimeSinceStartup-began>480)Finish("Timed out");}
 [Serializable]class Report{public bool passed;public string[] checks,failures;public int runtimeErrors;public float elapsedSeconds;}
 void Finish(string error){if(done)return;done=true;if(error!=null)failures.Add(error);File.WriteAllText(Path.Combine(folder,"adventure-tests.json"),JsonUtility.ToJson(new Report{passed=failures.Count==0&&errors==0,checks=checks.ToArray(),failures=failures.ToArray(),runtimeErrors=errors,elapsedSeconds=Time.realtimeSinceStartup-began},true));session.AllowTestStorage=false;if(hadTest)PlayerPrefs.SetString("WitchRPG.Test.v4",savedTest);else PlayerPrefs.DeleteKey("WitchRPG.Test.v4");Application.logMessageReceived-=Log;Application.Quit();}
}
}
