using UnityEngine;
using System;
using System.Linq;
using System.Collections;
namespace WitchPlayground {
public sealed partial class AdventureVerification {
 void FreeKill(SlimeMonster e){e.gameObject.SetActive(true);e.TestIdle=true;e.ResetMonster();e.ReceiveHit(new HitData{damage=e.maxHealth+1,owner=p,direction=Vector3.forward});}
 void SafeMenus(){a.Population.enabled=false;RpgUI.Instance.Close();p.Teleport(a.Camp);Camera.main.GetComponent<PlaygroundView>().Snap();foreach(var e in a.Enemies.Values)if(e.gameObject.activeSelf&&!e.IsDead)e.gameObject.SetActive(false);Time.timeScale=1;}
 IEnumerator FreeHunt(){
  Check(a.Ready&&a.Population.Slots.Count==27,"Three regions contain 27 independent population slots");
  for(int hero=0;hero<3;hero++){
   a.Population.enabled=true;session.NewGame("FreeHunter"+hero,hero);p.TestControl=true;a.TestFreezeEnemies=true;yield return Wait(.3f);
   Check(a.Population.ActiveCount>0&&a.Population.ActiveCount<=16,"Hero "+hero+" has ordinary enemies before accepting any quest within budget");
   var enemy=a.Population.Slots.First(s=>!s.enemy.isBee).enemy;
   for(int i=0;i<5;i++)FreeKill(enemy);Check(a.State.kills==5&&stats.Level>=2,"Five respawned enemies count and grant XP before quest acceptance");
   int kills=a.State.kills,essence=a.State.essence;a.EnemyDefeated(enemy);Check(a.State.kills==kills&&a.State.essence==essence,"Duplicate death notification awards nothing");
   Check(!RpgUI.Blocking&&stats.PendingChoices>0&&Time.timeScale==1,"Level-up is banked without pausing combat");
   Check(a.AcceptMain()&&a.State.introComplete,"Intro credits all kills made before acceptance");
   Check(a.Quests.Accept(0)&&a.Quests.Accept(1)&&!a.Quests.Accept(2),"At most two concurrent hunt contracts");
   var bee=a.Population.Slots.First(s=>s.enemy.isBee).enemy;for(int i=0;i<12;i++)FreeKill(bee);
   Check(a.Quests.State.jobs[0].Complete&&a.Quests.State.jobs[1].Complete,"Same ordinary bee kills advance both matching contracts");
   SafeMenus();yield return Wait(.2f);var position=p.transform.position;var checkpoint=p.Spawn;var camera=Camera.main.transform.position;
   Check(a.Quests.Claim(0)&&!a.Quests.Claim(0),"Hunt reward is claimable exactly once");Check(ClassCombat.Flat(p.transform.position-position).magnitude<.01f&&p.Spawn==checkpoint,"Contract reward preserves position and checkpoint");
   a.Quests.Claim(1);Check(a.Quests.Accept(0)&&a.Quests.State.jobs[0].count==0,"Replacement contract starts with no historical kill credit");Check(a.Quests.Abandon(0)&&a.Quests.State.jobs[0].count==0,"Abandoning clears only that contract");
   for(int i=0;i<30;i++)FreeKill(bee);a.DiscoverRegion(0);Check(!a.State.bossUnlocked,"Enough kills alone do not skip exploration");a.DiscoverRegion(1);Check(a.State.bossUnlocked&&!MoonwolfEvent.Instance.Summoned,"Survey and two regions unlock, but never auto-spawn, the boss");
   SafeMenus();yield return Wait(.2f);Check(RpgUI.Instance.TryOpenGrowth(),"Stored growth can be opened safely");yield return Wait(.2f);yield return Shot("growth-"+hero);while(stats.PendingChoices>0)stats.Choose(0);RpgUI.Instance.Close();
   string offers=stats.Export();session.Save();Check(session.LoadGame(),"New progression save loads");Check(stats.Export()==offers&&a.State.bossUnlocked,"Level choices and boss unlock round-trip without drift");p.TestControl=true;a.TestFreezeEnemies=true;
   SafeMenus();p.Teleport(a.Gate);yield return Wait(.2f);Check(a.EnterBoss(),"Unlocked boss can be manually challenged at its refuge");yield return Wait(.2f);
   var boss=MoonwolfEvent.Instance.boss.GetComponent<SlimeMonster>();boss.TestIdle=true;boss.ReceiveHit(new HitData{damage=boss.maxHealth+1,owner=p});yield return Wait(.2f);Check(a.State.bossCleared&&a.State.relicRewards==1&&a.State.unlockedDanger==2,"First boss banks one relic reward and unlocks danger two");Check(RpgUI.Instance.ActiveWindow==RpgUI.Window.None,"Victory does not force a modal window");
   SafeMenus();position=p.transform.position;checkpoint=p.Spawn;camera=Camera.main.transform.position;
   Check(a.ChooseRelic(hero)&&!a.ChooseRelic((hero+1)%3),"First relic reward cannot be duplicated");Check((p.transform.position-position).sqrMagnitude<.001f&&p.Spawn==checkpoint&&(Camera.main.transform.position-camera).sqrMagnitude<.001f,"Relic claim preserves player, camera and checkpoint");
   a.AddEssence(190);for(int n=0;n<3;n++)Check(a.Relics.Upgrade(hero),"Relic upgrade "+(n+1)+" succeeds");int balance=a.State.essence;Check(a.Relics.Rank(hero)==3&&!a.Relics.Upgrade(hero)&&a.State.essence==balance,"Relic upgrade cap cannot spend extra essence");
   Check(!a.EnterBoss(),"Repeat boss requires new hunting traces");for(int i=0;i<10;i++)FreeKill(bee);Check(a.State.retry==20,"New hunting restores rematch traces");SafeMenus();p.Teleport(a.Gate);yield return Wait(.2f);Check(a.ChangeDanger(2)&&a.State.danger==2,"Unlocked danger changes only at a safe refuge");
   Check(a.EnterBoss(),"Higher-danger rematch is available");yield return Wait(.2f);Check(ForestMusic.Instance.CurrentTrack=="SilverMoonwolf","Boss rematch switches to the boss soundtrack");boss.TestIdle=true;Check(boss.maxHealth==2240,"Danger changes boss strength");boss.ReceiveHit(new HitData{damage=boss.maxHealth+1,owner=p});yield return Wait(.2f);Check(ForestMusic.Instance.CurrentTrack=="MoonlitForest","Boss victory restores the exploration soundtrack");Check(a.State.relicRewards==0&&a.State.unlockedDanger==3,"Repeat boss gives essence, not a duplicate first-clear relic");
   SafeMenus();Check(a.AcceptSide(0),"Post-boss herb quest remains available");for(int i=0;i<3;i++){SafeMenus();p.Teleport(a.Herbs[i]);Check(a.Interact("herb"+i),"Herb site "+i+" collects");}Check(a.State.relicRewards==1&&(a.State.sideDone&1)!=0,"Herb follow-up banks a guaranteed relic");SafeMenus();Check(a.ChooseRelic((hero+1)%3),"Second unique relic can be selected");Check(a.AcceptSide(1),"Elite follow-up can be accepted afterwards");p.Teleport(a.Sites[0]);Check(a.StartEvent(0),"Optional elite event starts on demand");foreach(var e in a.Enemies.Where(k=>k.Key.StartsWith("elite")).Select(k=>k.Value))e.ReceiveHit(new HitData{damage=e.maxHealth+1,owner=p});Check(a.State.relicRewards==1&&(a.State.sideDone&2)!=0,"Elite follow-up completes from actual event kills");SafeMenus();Check(a.ChooseRelic((hero+2)%3)&&a.Relics.State.owned==7,"All three unique relics are obtainable without random drops");
   a.Population.ResetPopulation();yield return Wait(.2f);Check(a.Population.ActiveCount>0,"Completing every story quest leaves ordinary enemies alive");session.Save();string before=a.Export();Check(session.LoadGame()&&a.Export()==before,"Complete free-hunt progression and upgrades round-trip");p.TestControl=true;
  }
  // Version-one saves keep their entitlement and position; their defeated-list no longer empties the world.
  foreach(var stage in new[]{AdventureStage.Gate,AdventureStage.Boss,AdventureStage.Complete}){SafeMenus();var pos=p.transform.position;a.Import("{\"version\":1,\"stage\":"+(int)stage+",\"rewardSource\":-1,\"sideDone\":3,\"relics\":{\"owned\":7,\"equipped\":1}}",stage==AdventureStage.Complete);Check(a.State.bossUnlocked&&(p.transform.position-pos).sqrMagnitude<.001f,"Legacy "+stage+" keeps boss unlock and position");}
  SafeMenus();stats.GainXP(stats.NeededXP);string saved=stats.Export();stats.Import(saved);Check(stats.Export()==saved,"Stored offers are serialized without rerolling");
  a.State.relicRewards=1;a.State.bossCleared=true;a.ApplyWorld();RpgUI.Instance.OpenJournal(2);yield return Wait(.2f);yield return Shot("journal-relics");RpgUI.Instance.Close();RpgUI.Instance.OpenJournal(1);yield return Wait(.2f);yield return Shot("journal-hunts");RpgUI.Instance.Close();RpgUI.Instance.OpenJournal(3);yield return Wait(.2f);yield return Shot("journal-refuge");RpgUI.Instance.Close();
  a.Population.ResetPopulation();yield return Wait(.3f);Check(!a.Population.RespawnSafe(p.transform.position+Vector3.forward),"Respawn refuses the player vicinity");Check(a.Population.ActiveCount<=16,"Active population stays within the budget after all quest transitions");yield return Shot("free-hunt-field");Finish(null);
 }
 IEnumerator PopulationAI(){session.NewGame("PopulationAI",0);ClearUI();p.TestControl=true;a.TestFreezeEnemies=false;a.Population.ResetPopulation();yield return Wait(.5f);var e=a.Population.Slots.First(s=>s.enemy.gameObject.activeSelf).enemy;e.TestIdle=false;p.Teleport(AdventureProgress.Safe(e.transform.position+Vector3.forward*4));var start=e.transform.position;yield return Wait(1.2f);Check((e.transform.position-start).sqrMagnitude>.2f,"Population enemy walks toward a nearby player without a quest");e.ReceiveHit(new HitData{damage=1,owner=p});yield return Wait(.3f);Check(e.State=="Chasing","Hitting an ordinary enemy activates pursuit");e.ReceiveHit(new HitData{damage=e.maxHealth+1,owner=p});var slot=a.Population.Slots.First(s=>s.enemy==e);a.Population.Tick();p.Teleport(a.Regions[1]);Camera.main.GetComponent<PlaygroundView>().Snap();Check(a.Population.RespawnSafe(slot.home),"Respawn test point is outside the camera and player safety radius");for(int second=0;second<42;second++){p.ProtectArrival();yield return Wait(1);}a.Population.Tick();if(e.IsDead){Check(a.Population.ActiveCount==16,"Full population budget postpones a distant respawn");foreach(var other in a.Population.Slots.Where(s=>s!=slot&&s.enemy.gameObject.activeSelf&&!s.enemy.IsDead).ToArray())other.enemy.ReceiveHit(new HitData{damage=other.enemy.maxHealth+1,owner=p});a.Population.Tick();}Debug.Log("RESPAWN STATE active="+e.gameObject.activeSelf+" dead="+e.IsDead+" waiting="+slot.waiting+" safe="+a.Population.RespawnSafe(slot.home)+" count="+a.Population.ActiveCount+" due="+(slot.readyAt-Time.time));Check(!e.IsDead&&e.gameObject.activeSelf,"Dead ordinary enemy actually respawns when delay, visibility and population capacity permit");yield return Shot("population-live");Check(a.Population.ActiveCount<=16,"Live AI remains within population budget");Finish(null);}
}
}
