using UnityEngine;using System;using System.IO;using System.Collections;using System.Collections.Generic;using System.Linq;
namespace WitchPlayground {
public sealed partial class AudioVerification:MonoBehaviour {
 static bool launched;string folder;bool done;int errors;float began;WitchPlayer p;RpgProgress stats;HeroRoster roster;ForestSound sound;ForestMusic music;SlimeMonster source;readonly List<SlimeMonster> spawned=new List<SlimeMonster>();readonly List<string> checks=new List<string>(),failures=new List<string>();Vector3 arena=new Vector3(2000,.02f,0);
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Init(){var args=Environment.GetCommandLineArgs();int i=Array.IndexOf(args,"--audio-verify");if(!launched&&i>=0&&i+1<args.Length){launched=true;var v=new GameObject("Audio verification").AddComponent<AudioVerification>();v.folder=args[i+1];DontDestroyOnLoad(v.gameObject);Application.runInBackground=true;}}
 void Check(bool ok,string label){(ok?checks:failures).Add(label);Debug.Log((ok?"AUDIO PASS ":"AUDIO FAIL ")+label);}
 IEnumerator Wait(float t){yield return new WaitForSecondsRealtime(t);}void Update(){if(!done&&Time.realtimeSinceStartup-began>180)Finish("Timeout");}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(folder,name+".png"));yield return null;}
 IEnumerator Reset(int hero){foreach(var e in spawned)if(e)Destroy(e.gameObject);spawned.Clear();stats.ResetProgress();roster.Select(hero);p.Respawn();p.Teleport(arena);p.TestControl=true;p.TestMovement=Vector2.zero;p.TestRunning=false;RpgUI.Instance.Close();RpgUI.Instance.ReleaseInputForTest();p.ProcessButtons(false,false,false,Vector3.zero);p.transform.rotation=Quaternion.identity;stats.ranks=new[]{1,1,1,1};stats.CritOverride=0;stats.RestoreMana();Camera.main.GetComponent<PlaygroundView>().Snap();yield return Wait(.2f);}
 SlimeMonster Spawn(float distance=1.4f){var e=Instantiate(source,arena+Vector3.forward*distance,Quaternion.identity);e.TestIdle=true;e.maxHealth=5000;spawned.Add(e);return e;}
 IEnumerator Start(){began=Time.realtimeSinceStartup;Directory.CreateDirectory(folder);Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Error||t==LogType.Exception)errors++;};yield return Wait(.7f);p=FindAnyObjectByType<WitchPlayer>();p.TestControl=true;stats=p.GetComponent<RpgProgress>();roster=p.GetComponent<HeroRoster>();sound=ForestSound.Instance;music=ForestMusic.Instance;foreach(var e in FindObjectsByType<SlimeMonster>()){e.TestIdle=true;if(!e.isBee&&!e.isBoss)source=e;}
 foreach(var name in new[]{"MusicVolume","MusicMuted","EffectsVolume","AmbientVolume","EffectsMuted","AmbientMuted"})PlayerPrefs.DeleteKey("WitchRPG.Test."+name);music.ReloadSettings();sound.ReloadSettings();
 var all=Resources.LoadAll<AudioClip>("Audio/SFX");Check(all.Length==73&&all.All(c=>c.samples>0),"All 73 effect and ambience assets load");Check(music.Testing&&stats.TestSession,"Verification does not change player save settings");
 RpgSession.Instance.ShowTitleForTest();yield return Wait(1.6f);Check(music.CurrentTrack=="MoonlitFirstSteps"&&music.Source.isPlaying,"Title plays the original theme");int sample=music.Source.timeSamples;RpgSession.Instance.Creating=true;yield return Wait(.2f);Check(music.Source.timeSamples>sample,"Character selection does not restart title music");
 RpgUI.Instance.Open(RpgUI.Window.Audio);yield return Shot("audio-settings-ko");Loc.Language=1;yield return Shot("audio-settings-en");Loc.Language=2;yield return Shot("audio-settings-ja");Loc.Language=0;RpgUI.Instance.Close();
 sound.SetVolume(false,.31f);sound.SetVolume(true,.22f);sound.SetMuted(false,true);sound.SetMuted(true,true);sound.SaveSettings();sound.ReloadSettings();Check(sound.EffectsVolume==.31f&&sound.AmbientVolume==.22f&&sound.EffectsMuted&&sound.AmbientMuted,"Effect and ambience levels and mute settings persist independently");sound.SetVolume(false,.8f);sound.SetVolume(true,.45f);sound.SetMuted(false,false);sound.SetMuted(true,false);
 Check(RpgSession.Instance.NewGame("SoundTest",1),"New adventure starts");p.TestControl=true;yield return Wait(1.7f);Check(music.CurrentTrack=="MoonlitForest"&&music.Source.isPlaying&&music.Source.volume>.5f,"Forest exploration arrangement fades in");
 float output=0;var data=new float[2048];for(int n=0;n<20;n++){music.Source.GetOutputData(data,0);output=Mathf.Max(output,data.Sum(v=>v*v));yield return null;}Check(output>1e-6,"Exploration music produces real audio output");
 var floor=GameObject.CreatePrimitive(PrimitiveType.Cube);floor.layer=10;floor.transform.position=new Vector3(2000,-.25f,0);floor.transform.localScale=new Vector3(80,.5f,80);
 yield return InputAudit();if(Environment.GetCommandLineArgs().Contains("--input-only")){Check(errors==0,"No runtime errors");Finish(null);yield break;}
 yield return Reset(1);var enemy=Spawn();yield return Wait(.1f);enemy.ResetMonster();enemy.enabled=false;
 int slash=sound.Count("slash"),heavy=sound.Count("slash_heavy");for(int i=0;i<3;i++){Check(p.Combat.SwordAttack(enemy.HitPoint,false),"Warrior combo "+(i+1)+" starts");yield return Wait(i==2?.85f:.67f);}Check(sound.Count("slash")==slash+2&&sound.Count("slash_heavy")==heavy+1,"Three-hit combo emits two swishes and one heavy slash");Check(sound.Count("slime_hit")>0,"Actual damage emits monster impact sound");
 yield return Reset(1);enemy=Spawn(3);yield return Wait(.1f);enemy.ResetMonster();int before=sound.Count("dash");stats.TrySkill(SpellId.Frost,enemy.HitPoint);yield return Wait(.65f);Check(sound.Count("dash")==before+1,"Dash skill has its own cue");yield return Wait(.2f);before=sound.Count("fan");stats.TrySkill(SpellId.Meteor,enemy.HitPoint);yield return Wait(1);Check(sound.Count("fan")==before+1,"Fan slash cue occurs at its attack");
 yield return Reset(1);enemy=Spawn();yield return Wait(.1f);enemy.ResetMonster();stats.TrySkill(SpellId.Heal);before=sound.Count("parry");p.Combat.AvoidDamage(enemy);Check(sound.Count("parry")==before+1&&enemy.HardStunned,"Successful parry has a distinct cue and still stuns");
 yield return Reset(2);enemy=Spawn(4);yield return Wait(.1f);enemy.ResetMonster();enemy.enabled=false;before=sound.Count("bow_release");p.ProcessButtons(false,true,false,enemy.HitPoint);yield return Wait(.7f);Check(sound.Count("bow_draw")>0&&sound.Count("charge_ready")>0,"Bow drawing and fully charged state are audible");p.ProcessButtons(false,false,false,enemy.HitPoint);yield return Wait(.5f);Check(sound.Count("bow_release")==before+1&&sound.Count("arrow_hit")>0,"Arrow release and lodging play at the actual events");
 yield return Reset(2);enemy=Spawn(4);yield return Wait(.1f);enemy.ResetMonster();enemy.enabled=false;before=sound.Count("bow_release");stats.TrySkill(SpellId.Frost,enemy.HitPoint);yield return Wait(1.1f);Check(sound.Count("bow_release")==before+3,"Triple shot has three releases");
 yield return Reset(2);before=sound.Count("trap_set");var trap=HuntingTrap.Place(arena,p);enemy=Spawn(.1f);yield return Wait(.25f);Check(sound.Count("trap_set")==before+1&&sound.Count("trap_trigger")>0&&enemy.Rooted,"Trap setting and triggering are audible");
 yield return Reset(2);enemy=Spawn(4);yield return Wait(.1f);enemy.ResetMonster();stats.TrySkill(SpellId.Heal,enemy.transform.position);yield return Wait(.6f);p.CancelChannel();int rain=sound.Count("rain_start");yield return Wait(1.6f);Check(sound.Count("rain_start")==rain,"Cancelled rain does not emit a release cue");stats.RestoreMana();stats.TrySkill(SpellId.Heal,enemy.transform.position);yield return Wait(5.4f);Check(sound.Count("rain_start")==rain+1&&sound.Count("rain_tick")>=6,"Completed rain plays one release and six grouped impacts");
 yield return Reset(0);enemy=Spawn(3);yield return Wait(.1f);enemy.ResetMonster();enemy.enabled=false;before=sound.Count("energy_light");p.ProcessButtons(false,true,false,enemy.HitPoint);yield return Wait(.25f);p.ProcessButtons(false,false,false,enemy.HitPoint);yield return Wait(.3f);Check(sound.Count("energy_light")==before+1,"Light magic shot uses its release sound");yield return Wait(.25f);before=sound.Count("energy_heavy");p.ProcessButtons(false,true,false,enemy.HitPoint);yield return Wait(1.5f);p.ProcessButtons(false,false,false,enemy.HitPoint);yield return Wait(.3f);Check(sound.Count("energy_heavy")==before+1,"Charged magic shot uses its stronger release sound");
 yield return Reset(0);before=sound.Count("ice_wave");stats.TrySkill(SpellId.Frost);yield return Wait(1);Check(sound.Count("ice_wave")==before+3,"Frost cast emits three timed waves rather than 36 overlapping sounds");
 yield return Reset(0);before=sound.Count("meteor_hit");stats.TrySkill(SpellId.Meteor,arena+Vector3.forward*3);yield return Wait(.7f);p.CancelChannel();yield return Wait(2.6f);Check(sound.Count("meteor_hit")==before,"Cancelled meteor stays silent at the would-be impact");stats.TrySkill(SpellId.Meteor,arena+Vector3.forward*3);yield return Wait(3.4f);Check(sound.Count("meteor_hit")==before+1&&sound.Count("meteor_fall")>0,"Meteor descent and impact have separate timed cues");
 yield return Reset(0);p.TakeDamage(30);before=sound.Count("heal_tick");stats.TrySkill(SpellId.Heal);yield return Wait(5.3f);Check(sound.Count("heal_tick")==before+5&&p.Health==p.maxHealth,"Healing has a start cue and five quiet pulses");
 yield return Reset(0);before=sound.Count("roll");p.Combat.TryEvade(Vector2.up);yield return Wait(.7f);Check(sound.Count("roll")==before+1,"Roll plays one movement cue");p.TestMovement=Vector2.up;yield return Wait(1.2f);p.TestMovement=Vector2.zero;Check(sound.Count("foot_0")+sound.Count("foot_1")+sound.Count("foot_2")>0,"Actual grounded travel generates footsteps");
 yield return Reset(0);enemy=Spawn();yield return Wait(.1f);enemy.ResetMonster();before=sound.Count("critical");enemy.ReceiveHit(new HitData{owner=p,damage=10,critical=true});Check(sound.Count("critical")==before+1,"Critical impact is distinct");enemy.FreezeFor(1);Check(sound.Count("freeze")>0,"First freeze has a crystal cue");enemy.ReceiveHit(new HitData{owner=p,damage=10000});Check(sound.Count("slime_death")>0,"Monster death has a cue");
 yield return Reset(0);before=sound.Count("level_up");stats.GainXP(stats.NeededXP);yield return Wait(.1f);Check(sound.Count("level_up")==before+1&&Time.timeScale==0,"Level-up cue can play while choices pause the world");stats.Choose(0);Check(sound.Count("upgrade")>0,"Reward selection has a confirmation cue");yield return Wait(.2f);RpgUI.Instance.Close();
 before=sound.Count("ui_error");stats.SetManaForTest(0);stats.Spend(20);stats.Spend(20);Check(sound.Count("ui_error")==before+1,"Repeated invalid actions are rate-limited");
 yield return Reset(1);before=sound.Count("player_hit");p.TakeDamage(10);Check(sound.Count("player_hit")==before+1,"Player damage has feedback");yield return Wait(.4f);p.TakeDamage(1000);yield return Wait(.15f);Check(sound.Count("death")>0&&music.Source.volume<.55f,"Death cue ducks the background music");p.Respawn();RpgUI.Instance.Close();yield return Wait(.2f);Check(sound.Count("revive")>0,"Respawn has a gentle return cue");
 // Pool saturation and deterministic combat RNG: audio must not influence critical rolls.
 yield return Reset(0);var randomState=UnityEngine.Random.state;float expected=UnityEngine.Random.value;UnityEngine.Random.state=randomState;ForestSound.Play("slash",arena);float actual=UnityEngine.Random.value;Check(expected==actual,"Audio pitch variation does not consume gameplay random numbers");
 int accepted=0;foreach(var c in all)if(ForestSound.Play(c.name,null,.1f))accepted++;Check(sound.ActiveVoices<=sound.VoiceLimit&&accepted<all.Length,"Crowd audio remains bounded by the 18-voice pool");sound.StopWorld();yield return Wait(2.4f);
 Check(!ForestSound.Play("slash",arena+Vector3.forward*100),"Far-off world sounds are culled");
 RpgUI.Instance.Open(RpgUI.Window.Pause);before=sound.Count("slash");Check(!ForestSound.Play("slash",arena),"World one-shots do not start while paused");RpgUI.Instance.Open(RpgUI.Window.Audio);yield return Shot("pause-audio-settings");RpgUI.Instance.Close();Check(RpgUI.Instance.ActiveWindow==RpgUI.Window.Pause&&Time.timeScale==0,"Closing audio settings returns to the pause menu");RpgUI.Instance.Close();
 p.Teleport(p.Spawn);p.ProtectArrival();MoonwolfEvent.Instance.Summon();yield return Wait(1.7f);Check(music.CurrentTrack=="SilverMoonwolf"&&music.Source.isPlaying,"Nearby field boss switches to the battle arrangement");var boss=MoonwolfEvent.Instance.boss.GetComponent<SlimeMonster>();var behavior=boss.GetComponent<MoonwolfBoss>();before=sound.Count("boss_warning");yield return Wait(1.4f);if(!behavior.Casting)behavior.Cast(MoonwolfBoss.Skill.Howl);yield return Wait(3.2f);Check(sound.Count("boss_warning")>before||sound.Count("boss_warning")>0,"Boss wind-up announces danger audibly");boss.ReceiveHit(new HitData{owner=p,damage=100000});yield return Wait(1.7f);Check(sound.Count("victory")>0&&music.CurrentTrack=="MoonlitForest","Boss defeat plays victory cue and returns to exploration music");
 var musicObject=music;var soundObject=sound;RpgSession.Instance.ReturnToTitle();yield return Wait(1.7f);Check(ForestMusic.Instance==musicObject&&ForestSound.Instance==soundObject&&FindObjectsByType<ForestSound>().Length==1,"Title return keeps single audio managers without duplicate loops");Check(music.CurrentTrack=="MoonlitFirstSteps","Title theme returns after leaving the field");
 int confirms=sound.Count("ui_confirm");PlayerPrefs.SetString("WitchRPG.Test.v4","{broken");bool loaded=RpgSession.Instance.LoadGame();Check(!loaded&&sound.Count("ui_confirm")==confirms,"Invalid save does not play the success cue");PlayerPrefs.DeleteKey("WitchRPG.Test.v4");
 Check(sound.MissingClips==0,"No missing cue assets");Check(errors==0,"No runtime errors");sound.SaveSettings();music.SaveSettings();foreach(var name in new[]{"MusicVolume","MusicMuted","EffectsVolume","AmbientVolume","EffectsMuted","AmbientMuted"})PlayerPrefs.DeleteKey("WitchRPG.Test."+name);PlayerPrefs.Save();Finish(null);
 }
 [Serializable]class Report{public bool passed;public string[] checks,failures;public int runtimeErrors;}
 void Finish(string issue){if(done)return;done=true;if(issue!=null)failures.Add(issue);File.WriteAllText(Path.Combine(folder,"audio-tests.json"),JsonUtility.ToJson(new Report{passed=failures.Count==0,checks=checks.ToArray(),failures=failures.ToArray(),runtimeErrors=errors},true));Application.Quit(failures.Count==0?0:1);}
}
}
