using UnityEngine;using System;using System.IO;using System.Collections;using System.Collections.Generic;using System.Linq;
namespace WitchPlayground {
public sealed class UXVerification:MonoBehaviour {
 static bool launched;string folder;bool done;float began;int errors;float stressAverageFPS,stressP95Ms;List<string> checks=new List<string>(),failures=new List<string>();WitchPlayer p;RpgProgress stats;HeroRoster roster;ClassCombat combat;SlimeMonster source;Vector3 arena=new Vector3(2000,.02f,0);List<SlimeMonster> enemies=new List<SlimeMonster>();
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Init(){var a=Environment.GetCommandLineArgs();int i=Array.IndexOf(a,"--ux-verify");if(!launched&&i>=0&&i+1<a.Length){launched=true;var v=new GameObject("UX verification").AddComponent<UXVerification>();v.folder=a[i+1];DontDestroyOnLoad(v.gameObject);Application.runInBackground=true;}}
 void Check(bool ok,string label){(ok?checks:failures).Add(label);Debug.Log((ok?"UX PASS ":"UX FAIL ")+label);}
 IEnumerator Wait(float t){yield return new WaitForSeconds(t);}void Update(){if(!done&&Time.realtimeSinceStartup-began>210)Finish("Timed out");}
 void Bind(){p=FindAnyObjectByType<WitchPlayer>();stats=p.GetComponent<RpgProgress>();roster=p.GetComponent<HeroRoster>();combat=p.Combat;p.TestControl=true;foreach(var e in FindObjectsByType<SlimeMonster>()){e.TestIdle=true;if(!e.isBee&&!e.isBoss)source=e;}}
 SlimeMonster Spawn(Vector3 offset){var e=Instantiate(source,arena+offset,Quaternion.identity);e.TestIdle=true;enemies.Add(e);return e;}
 IEnumerator Prepare(bool mobile=false){yield return null;foreach(var e in enemies){e.maxHealth=5000;e.ResetMonster();e.enabled=mobile;}Physics.SyncTransforms();}
 IEnumerator Reset(int hero){foreach(var e in enemies)if(e)Destroy(e.gameObject);enemies.Clear();foreach(var o in FindObjectsByType<ArrowFlight>())Destroy(o.gameObject);p.TestMovement=Vector2.zero;foreach(var m in FindObjectsByType<GrandMeteor>())Destroy(m.gameObject);foreach(var m in FindObjectsByType<ArrowRain>())Destroy(m.gameObject);foreach(var m in FindObjectsByType<MagicProjectile>())Destroy(m.gameObject);foreach(var m in FindObjectsByType<RasterEffect>())Destroy(m.gameObject);foreach(var m in FindObjectsByType<CombatSprite>())Destroy(m.gameObject);stats.ResetProgress();roster.Select(hero);p.Respawn();p.Teleport(arena);RpgUI.Instance.ReleaseInputForTest();p.ProcessButtons(false,false,false,Vector3.zero);Camera.main.GetComponent<PlaygroundView>().Snap();p.transform.rotation=Quaternion.identity;stats.ranks=new[]{1,1,1,1};stats.RestoreMana();stats.CritOverride=0;yield return Wait(.12f);}
 IEnumerator Hold(bool j,bool mouse,float duration,Vector3 aim){float start=Time.time;while(Time.time-start<duration){p.ProcessButtons(j,mouse,false,aim);yield return null;}}
 IEnumerator Shot(string n){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(folder,n+".png"));yield return null;}
 IEnumerator Start(){began=Time.realtimeSinceStartup;Directory.CreateDirectory(folder);Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception||t==LogType.Error)errors++;};yield return Wait(.8f);Bind();var floor=GameObject.CreatePrimitive(PrimitiveType.Cube);floor.layer=10;floor.transform.position=new Vector3(2000,-.25f,0);floor.transform.localScale=new Vector3(80,.5f,80);
 yield return Reset(0);var target=Spawn(Vector3.right*5);var far=Spawn(Vector3.forward*8);yield return Prepare();yield return Hold(true,false,.35f,far.HitPoint);p.ProcessButtons(false,false,false,far.HitPoint);yield return Wait(.5f);Check(p.LastShotDirection.x>.99f&&target.Health<5000&&far.Health==5000,"Witch J aims at nearest enemy, regardless of facing or mouse");
 yield return Reset(0);target=Spawn(Vector3.right*3);far=Spawn(Vector3.forward*7);yield return Prepare();yield return Hold(false,true,.35f,far.HitPoint);p.ProcessButtons(false,false,false,far.HitPoint);yield return Wait(.5f);Check(p.LastShotDirection.z>.99f&&target.Health==5000&&far.Health<5000,"Witch mouse keeps manual aimed direction");
 yield return Reset(0);target=Spawn(Vector3.right*4);far=Spawn(Vector3.forward*7);yield return Prepare();yield return Hold(true,false,.3f,far.HitPoint);target.ReceiveHit(new HitData{damage=6000});p.ProcessButtons(false,false,false,far.HitPoint);yield return Wait(.5f);Check(p.LastShotDirection.z>.99f&&far.Health<5000,"J reselects a live enemy if nearest dies while charging");
 yield return Reset(0);target=Spawn(Vector3.right*4);yield return Prepare();yield return Hold(true,false,.3f,target.HitPoint);target.transform.position=arena+Vector3.left*4;Physics.SyncTransforms();p.ProcessButtons(false,false,false,Vector3.forward);yield return Wait(.5f);Check(p.LastShotDirection.x<-.99f&&target.Health<5000,"J targets current enemy position at release");
 yield return Reset(0);p.transform.rotation=Quaternion.LookRotation(Vector3.left);yield return Hold(true,false,.25f,arena+Vector3.right*5);p.ProcessButtons(false,false,false,arena+Vector3.right*5);Check(p.LastShotDirection.x<-.99f,"Without enemies, J still fires forward");
 yield return Reset(0);target=Spawn(Vector3.right*4);far=Spawn(Vector3.forward*7);yield return Prepare();var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.layer=11;wall.transform.position=arena+new Vector3(2,1,0);wall.transform.localScale=new Vector3(.2f,3,3);Physics.SyncTransforms();Check(p.WitchAutoTarget()==far,"Auto target skips enemy behind solid wall");Destroy(wall);
 // Meteor: visible timer, interruption before impact, successful full channel and continuing burn.
 yield return Reset(0);target=Spawn(Vector3.forward*5);yield return Prepare();Check(stats.TrySkill(SpellId.Meteor,target.transform.position),"Meteor starts");Check(p.IsChanneling&&p.ChannelSpell==SpellId.Meteor&&p.Channel01<.05f,"Meteor exposes a three-second cast gauge");yield return Wait(1.1f);Check(p.Channel01>.33f&&p.Channel01<.45f,"Meteor gauge follows elapsed channel time");yield return Shot("meteor-casting");p.TestMovement=Vector2.right;var before=p.transform.position;yield return Wait(.25f);Check(!p.IsChanneling&&!p.IsSpellCasting&&!p.KnockbackImmune,"Movement cancels meteor cast, pose and guard");Check(ClassCombat.Flat(p.transform.position-before).magnitude>.35f,"Movement resumes immediately after cast cancellation");p.TestMovement=Vector2.zero;yield return Wait(2.1f);Check(target.Health==5000&&!FindAnyObjectByType<GrandMeteor>(),"Cancelled meteor never impacts and removes its caster object");Check(stats.Cooldown(SpellId.Meteor)==0&&Mathf.Abs(stats.Mana-stats.MaxMana)<.1f,"Cancelled meteor costs no mana or cooldown");
 yield return Reset(0);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Meteor,target.transform.position);yield return Wait(2.65f);p.HandleChannelInput(Vector2.zero,true);yield return Wait(.6f);Check(target.Health==5000&&!FindAnyObjectByType<GrandMeteor>()&&!p.IsChanneling,"Late action input cancels descending meteor before damage");Check(!FindObjectsByType<RasterEffect>().Any(f=>f.loop),"Cancelled meteor removes looping seal and fire orbit");
 yield return Reset(0);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Meteor,target.transform.position);yield return Wait(.5f);RpgUI.Instance.Open(RpgUI.Window.Pause);yield return new WaitForSecondsRealtime(.15f);Check(p.IsChanneling,"Menu pauses and preserves prepared channel");float progress=p.Channel01;yield return new WaitForSecondsRealtime(.3f);Check(Mathf.Abs(p.Channel01-progress)<.01f,"Cast gauge pauses while menu is open");RpgUI.Instance.Close();p.CancelChannel();yield return Wait(.1f);Check(target.Health==5000,"Closing menu does not cast or damage by itself");
 yield return Reset(0);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Meteor,target.transform.position);yield return Wait(1);p.TakeDamage(10);Check(p.IsChanneling&&p.Health==90,"Meteor retains damage-taking knockback protection while channeling");yield return Wait(2.2f);Check(!p.IsChanneling&&target.Health==4820,"Full meteor channel impacts for 180 damage and clears gauge");p.TestMovement=Vector2.right;yield return Wait(4.2f);p.TestMovement=Vector2.zero;Check(target.Health==4732,"Movement after impact preserves all four burning damage ticks");
 // Rain: early and late cancel, interruption on hit, full channel with persistent released spell.
 yield return Reset(2);target=Spawn(Vector3.forward*5);yield return Prepare();Check(stats.TrySkill(SpellId.Heal,target.transform.position),"Arrow rain starts");yield return Wait(.8f);Check(p.IsChanneling&&p.ChannelSpell==SpellId.Heal&&p.Channel01>.35f&&p.Channel01<.48f,"Arrow rain exposes two-second cast progress");yield return Shot("arrow-rain-casting");p.TestMovement=Vector2.left;yield return Wait(.2f);p.TestMovement=Vector2.zero;Check(!p.IsChanneling&&!p.IsSpellCasting,"Movement cancels arrow rain and drawing pose");Check(!FindObjectsByType<CombatSprite>().Any(f=>f.ground&&f.row==3),"Cancelled rain clears ground warning immediately");yield return Wait(2.4f);Check(target.Health==5000&&!FindAnyObjectByType<ArrowRain>(),"Cancelled rain never spawns arrows or damage");
 yield return Reset(2);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Heal,target.transform.position);yield return Wait(1.8f);p.HandleChannelInput(Vector2.zero,true);yield return Wait(.6f);Check(!p.IsChanneling&&target.Health==5000&&!FindAnyObjectByType<ArrowRain>(),"Late attack or skill input cancels arrow rain");
 yield return Reset(2);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Heal,target.transform.position);yield return Wait(.4f);p.TakeDamage(10);yield return Wait(2);Check(!p.IsChanneling&&!FindAnyObjectByType<ArrowRain>()&&target.Health==5000,"Getting hit interrupts archer channel and gauge together");
 yield return Reset(2);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Heal,target.transform.position);yield return Wait(2.2f);Check(!p.IsChanneling&&FindAnyObjectByType<ArrowRain>(),"Completing two-second draw releases arrow rain");p.TestMovement=Vector2.left;yield return Wait(3.2f);p.TestMovement=Vector2.zero;Check(target.Health==4886,"Released rain retains six 80-percent damage ticks while player moves");
 yield return Reset(0);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Meteor,target.transform.position);yield return Wait(.2f);p.TakeDamage(500);yield return Wait(.2f);Check(p.IsDead&&!p.IsChanneling&&!FindAnyObjectByType<GrandMeteor>(),"Death cancels meteor and clears channel effects");
 yield return Reset(0);target=Spawn(Vector3.forward*5);yield return Prepare();stats.manaRegenTuning=0;float mp=stats.Mana;stats.TrySkill(SpellId.Meteor,target.transform.position);yield return Wait(.5f);Check(stats.Mana==mp&&stats.Cooldown(SpellId.Meteor)==0,"Channel reserves cast without spending resources early");stats.SelectLeft();yield return Wait(.1f);Check(p.IsChanneling,"Changing selected skill with Tab does not cancel current cast");yield return Wait(2.6f);Check(stats.Mana==mp-stats.Cost(SpellId.Meteor)&&stats.Cooldown(SpellId.Meteor)>7,"Mana and cooldown commit exactly once on completion");stats.manaRegenTuning=1;
 yield return Reset(2);target=Spawn(Vector3.forward*5);yield return Prepare();stats.TrySkill(SpellId.Heal,target.transform.position);yield return Wait(.2f);p.CancelChannel();Check(stats.Cooldown(SpellId.Heal)==0&&stats.Mana==stats.MaxMana,"Cancelled arrow rain has no resource penalty");
 yield return Reset(0);target=Spawn(Vector3.forward*4);yield return Prepare();yield return Wait(.2f);Check(p.GetComponent<AimAssist>().Target==target,"Aim marker identifies J auto-target");yield return Shot("target-marker");RpgUI.Instance.Open(RpgUI.Window.Bag);RpgUI.Instance.Close();int shots=p.ShotsFired;p.ProcessButtons(true,true,false,target.HitPoint);Check(!p.IsCharging&&shots==p.ShotsFired,"Closing UI suppresses both held keyboard and mouse attack");RpgUI.Instance.ReleaseInputForTest();
 RpgVFX.Texts.Clear();for(int i=0;i<12;i++)RpgVFX.DamageText(target.HitPoint,2,false);RpgVFX.HealText(target.HitPoint,5);Check(RpgVFX.Texts.Count==2&&RpgVFX.Texts[0].amount==24,"Rapid damage ticks merge while healing remains separate");Check(RpgVFX.Texts[0].offset.x!=RpgVFX.Texts[1].offset.x,"Damage and healing occupy different text lanes");for(int i=0;i<150;i++)RpgVFX.DamageText(arena+Vector3.forward*i*2,1,false);Check(RpgVFX.Texts.Count<=72,"Combat text count is capped under load");RpgVFX.Texts.Clear();
 yield return Reset(1);target=Spawn(Vector3.forward*.9f);yield return Prepare(true);p.TakeDamage(40);yield return Wait(.4f);int hp=p.Health;shots=p.ShotsFired;yield return Hold(true,false,2.02f,target.HitPoint);p.ProcessButtons(false,false,false,target.HitPoint);yield return Wait(.3f);Check(p.ShotsFired>=shots+3&&target.Health<=4910,"Warrior close-range forward combo lands all three hits");Check(Vector3.Dot(target.transform.position-p.transform.position,p.transform.forward)>.45f,"Warrior does not step through the target");Check(p.Health>hp,"Warrior combo still heals actual dealt damage");
 // Compare body-root angular motion with travel direction for all three classes.
 for(int hero=0;hero<3;hero++){foreach(var input in new[]{Vector2.up,Vector2.left,Vector2.right}){yield return Reset(hero);var view=Camera.main.GetComponent<PlaygroundView>();view.yaw=145;view.pitch=32;view.Snap();var expected=(ClassCombat.Flat(Camera.main.transform.forward).normalized*input.y+ClassCombat.Flat(Camera.main.transform.right).normalized*input.x).normalized;var root=p.animator.GetComponentsInChildren<Transform>().First(t=>t.name.Equals("Root",StringComparison.OrdinalIgnoreCase)||t.name=="CTRL_root");var rollStart=p.transform.position;Check(combat.TryEvade(input),"Hero "+hero+" starts directional roll "+input);var rest=root.rotation;yield return Wait(.12f);var delta=root.rotation*Quaternion.Inverse(rest);delta.ToAngleAxis(out float angle,out Vector3 axis);if(angle>180)angle-=360;float forwardAngle=angle*Vector3.Dot(axis,p.transform.right);Check(forwardAngle>5,"Hero "+hero+" body rotates forward in travel direction "+input);if(input==Vector2.up)yield return Shot("forward-roll-"+hero);yield return Wait(.46f);var traveled=ClassCombat.Flat(p.transform.position-rollStart);Check(Vector3.Dot(traveled.normalized,expected)>.98f&&traveled.magnitude>2,"Hero "+hero+" roll displacement matches input "+input);}}
 yield return Reset(0);p.ProtectArrival();hp=p.Health;p.TakeDamage(25);Check(p.Health==hp,"Arrival protection prevents immediate spawn damage");yield return Wait(2.1f);p.TakeDamage(25);Check(p.Health==hp-25,"Arrival protection expires after two seconds");

 yield return Reset(2);p.Teleport(p.Spawn);var at=p.transform.position;var samples=new List<float>();for(int i=0;i<12;i++){float angle=i*Mathf.PI/6;var e=Instantiate(source,GroundSpellTravel.GroundPosition(at+new Vector3(Mathf.Cos(angle),0,Mathf.Sin(angle))*(3+i%3),.02f),Quaternion.identity);e.TestIdle=true;e.maxHealth=5000;enemies.Add(e);}yield return Wait(.25f);foreach(var e in enemies)e.ResetMonster();ArrowRain.Begin(at+Vector3.forward*3,6,combat.Hit(.8f,Vector3.down));float until=Time.time+4;while(Time.time<until){samples.Add(Time.unscaledDeltaTime);yield return null;}samples.Sort();stressAverageFPS=1/samples.Average();stressP95Ms=samples[(int)(samples.Count*.95f)]*1000;Debug.Log("UX STRESS averageFPS="+stressAverageFPS+" p95ms="+stressP95Ms);Check(RpgVFX.Texts.Count<=72,"Forest battle keeps floating text bounded under load");yield return Shot("forest-ux");

 // Short taps near the end of an attack should survive its recovery, exactly once.
 yield return Reset(1);target=Spawn(Vector3.forward*1.5f);yield return Prepare(true);shots=p.ShotsFired;p.ProcessButtons(true,false,false,target.HitPoint);p.ProcessButtons(false,false,false,target.HitPoint);yield return Wait(.46f);p.ProcessButtons(true,false,false,target.HitPoint);p.ProcessButtons(false,false,false,target.HitPoint);Check(p.HasBufferedAction,"Late warrior tap is buffered");yield return Wait(.48f);Check(p.ShotsFired==shots+2&&p.ActionName=="SlashLeft","Buffered tap executes the next combo strike once");yield return Wait(.5f);Check(p.ShotsFired==shots+2&&!p.HasBufferedAction,"Buffered combo does not cause further phantom attacks");
 yield return Reset(1);target=Spawn(Vector3.forward*1.5f);yield return Prepare();combat.SwordAttack(target.HitPoint,false);yield return Wait(.46f);Check(stats.TrySkill(SpellId.Meteor,target.HitPoint)&&p.HasBufferedAction,"Skill tap queues during final attack recovery");yield return Wait(.23f);Check(p.ActionName=="FanSlash"&&!p.HasBufferedAction,"Buffered skill begins after attack finishes");
 yield return Reset(1);combat.SwordAttack(arena+Vector3.forward,false);yield return Wait(.46f);p.ProcessButtons(true,false,false,arena+Vector3.forward);p.ProcessButtons(false,false,false,arena+Vector3.forward);RpgUI.Instance.Open(RpgUI.Window.Bag);Check(!p.HasBufferedAction,"Opening a menu clears buffered attacks");RpgUI.Instance.Close();RpgUI.Instance.ReleaseInputForTest();yield return Wait(.6f);
 yield return Reset(1);shots=p.ShotsFired;combat.SwordAttack(arena+Vector3.forward,false);yield return Wait(.1f);p.ProcessButtons(true,false,false,arena+Vector3.forward);p.ProcessButtons(false,false,false,arena+Vector3.forward);yield return Wait(.85f);Check(p.ShotsFired==shots+1,"Early taps are not stored for an unexpectedly delayed attack");
 // Narrow passage, wall sliding and small steps: use the same controller as the forest.
 var obstacles=new List<GameObject>();
 for(int hero=0;hero<3;hero++){yield return Reset(hero);Camera.main.GetComponent<PlaygroundView>().yaw=0;Camera.main.GetComponent<PlaygroundView>().Snap();foreach(float side in new[]{-1f,1f}){var w=GameObject.CreatePrimitive(PrimitiveType.Cube);w.layer=11;w.transform.position=arena+new Vector3(side*.825f,1,2);w.transform.localScale=new Vector3(1,2,6);obstacles.Add(w);}Physics.SyncTransforms();var begin=p.transform.position;p.TestMovement=Vector2.up;yield return Wait(1.1f);p.TestMovement=Vector2.zero;Check(p.transform.position.z-begin.z>1.8f,"Hero "+hero+" traverses a 0.65m narrow passage");foreach(var o in obstacles)Destroy(o);obstacles.Clear();yield return null;}
 yield return Reset(1);Camera.main.GetComponent<PlaygroundView>().yaw=0;Camera.main.GetComponent<PlaygroundView>().Snap();var blockWall=GameObject.CreatePrimitive(PrimitiveType.Cube);blockWall.layer=11;blockWall.transform.position=arena+new Vector3(1,1,2);blockWall.transform.localScale=new Vector3(1,2,12);p.TestMovement=new Vector2(1,1);yield return Wait(1.5f);p.TestMovement=Vector2.zero;Check(p.transform.position.z>1.6f&&p.transform.position.x-arena.x<.36f,"Diagonal movement slides along wall without passing through it");Destroy(blockWall);yield return null;
 yield return Reset(0);Camera.main.GetComponent<PlaygroundView>().yaw=0;Camera.main.GetComponent<PlaygroundView>().Snap();blockWall=GameObject.CreatePrimitive(PrimitiveType.Cube);blockWall.layer=11;blockWall.transform.position=arena+new Vector3(0,1,1);blockWall.transform.localScale=new Vector3(3,2,.2f);p.TestMovement=Vector2.up;yield return Wait(1);Check(p.State=="Idle","Blocked movement stops the walking-in-place animation");p.TestMovement=Vector2.zero;Destroy(blockWall);yield return null;
 yield return Reset(0);Camera.main.GetComponent<PlaygroundView>().yaw=0;Camera.main.GetComponent<PlaygroundView>().Snap();var step=GameObject.CreatePrimitive(PrimitiveType.Cube);step.layer=10;step.transform.position=arena+new Vector3(0,.08f,1.1f);step.transform.localScale=new Vector3(3,.2f,1);p.TestMovement=Vector2.up;yield return Wait(1.4f);p.TestMovement=Vector2.zero;Check(p.transform.position.z>2,"Low 20cm step does not trap player");Destroy(step);yield return null;
 // Frozen pose, root visual, simultaneous status, expiry and death cleanup.
 yield return Reset(0);target=Spawn(Vector3.forward*2);yield return Prepare(true);target.FreezeFor(1.5f);target.RootFor(2.5f);yield return Wait(.2f);var status=target.GetComponent<StatusVisuals>();var frozenPos=target.visual.localPosition;var frozenScale=target.visual.localScale;Check(status.IceVisible&&status.RootsVisible,"Ice and root bindings can be shown together");yield return Wait(.4f);Check(target.visual.localPosition==frozenPos&&target.visual.localScale==frozenScale,"Frozen slime no longer bounces or squashes");yield return Shot("frozen-and-rooted");yield return Wait(1);Check(!status.IceVisible&&status.RootsVisible,"Frozen visual ends while longer root remains");yield return Wait(1);Check(!status.IceVisible&&!status.RootsVisible,"Both status visuals clear on expiry");target.FreezeFor(2);target.RootFor(2);target.ReceiveHit(new HitData{damage=6000});yield return null;Check(!status.IceVisible&&!status.RootsVisible,"Status visuals disappear on death");target.ResetMonster();yield return null;Check(!status.IceVisible&&!status.RootsVisible,"Respawn does not keep previous immobilization effects");

 yield return Reset(0);var beeSource=FindObjectsByType<SlimeMonster>().First(e=>e.isBee);var bee=Instantiate(beeSource,arena+Vector3.forward*4,Quaternion.identity);bee.TestIdle=true;enemies.Add(bee);yield return Wait(.1f);bee.FreezeFor(.6f);yield return Wait(.2f);Check(bee.visual.GetComponentInChildren<Animator>().speed==0,"Frozen bee wing animation pauses");yield return Wait(.6f);Check(bee.visual.GetComponentInChildren<Animator>().speed==1,"Bee wing animation resumes after thaw");
 var bossObject=Instantiate(MoonwolfEvent.Instance.boss,arena+Vector3.forward*25,Quaternion.identity);bossObject.SetActive(true);var bossHealth=bossObject.GetComponent<SlimeMonster>();enemies.Add(bossHealth);yield return Wait(.1f);bossHealth.FreezeFor(.6f);yield return Wait(.2f);Check(bossObject.GetComponentInChildren<Animator>().speed==0,"Frozen boss body animation pauses");yield return Wait(.6f);Check(bossObject.GetComponentInChildren<Animator>().speed==1,"Boss body animation resumes after thaw");
 // Walking/running must not accelerate upper-body casting and archery.
 yield return Reset(2);target=Spawn(Vector3.forward*6);yield return Prepare();p.ProcessButtons(false,true,false,target.HitPoint);p.TestMovement=Vector2.right;p.TestRunning=true;yield return Wait(.3f);int layer=p.animator.GetLayerIndex("MobileCast");var upper=p.animator.GetCurrentAnimatorStateInfo(layer);Check(Mathf.Abs(p.animator.speed-1)<.01f&&p.animator.GetFloat("MoveRate")>1.2f,"Running changes locomotion rate without changing whole animator speed");Check(upper.normalizedTime<.7f,"Moving archer draw has not finished prematurely at 0.3 seconds");yield return Shot("running-bow-draw");p.TestMovement=Vector2.zero;p.TestRunning=false;p.ProcessButtons(false,false,false,target.HitPoint);yield return Wait(.5f);
 for(int hero=0;hero<3;hero++){yield return Reset(hero);p.TestMovement=Vector2.up;yield return Wait(.45f);Check(Mathf.Abs(p.GetComponent<VisualGrounding>().SoleGap)<.06f,"Hero "+hero+" walking soles remain grounded");p.TestRunning=true;yield return Wait(.45f);Check(Mathf.Abs(p.GetComponent<VisualGrounding>().SoleGap)<.06f,"Hero "+hero+" running soles remain grounded");p.TestMovement=Vector2.zero;p.TestRunning=false;yield return Wait(.15f);Check(p.State=="Idle"&&Mathf.Abs(p.animator.speed-1)<.01f,"Hero "+hero+" returns cleanly from running to idle");}
 yield return Reset(1);var reviewView=Camera.main.GetComponent<PlaygroundView>();reviewView.yaw=165;reviewView.pitch=20;Camera.main.orthographicSize=2.4f;reviewView.Snap();var reviewLight=new GameObject("Motion review fill").AddComponent<Light>();reviewLight.type=LightType.Point;reviewLight.range=10;reviewLight.intensity=.75f;reviewLight.transform.position=arena+new Vector3(1,3,3);foreach(var actionName in new[]{"SlashRight","SlashLeft","SlashOverhead","Guard","DashSlash","FanSlash"}){p.PlayAction(actionName,.8f,false);float maxGap=0;for(int i=0;i<6;i++){yield return Wait(.1f);if(i==2)yield return Shot("motion-"+actionName+"-mid");maxGap=Mathf.Max(maxGap,Mathf.Abs(p.GetComponent<VisualGrounding>().SoleGap));}Check(maxGap<.08f,"Warrior foot grounding remains stable during "+actionName);yield return Shot("motion-"+actionName);yield return Wait(.25f);}
 Check(errors==0,"No runtime errors");Finish(null);
 }
 [Serializable]class Report{public bool passed;public string[] checks,failures;public int runtimeErrors;public float stressAverageFPS,stressP95Ms;}
 void Finish(string issue){if(done)return;done=true;if(issue!=null)failures.Add(issue);File.WriteAllText(Path.Combine(folder,"ux-tests.json"),JsonUtility.ToJson(new Report{passed=failures.Count==0,checks=checks.ToArray(),failures=failures.ToArray(),runtimeErrors=errors,stressAverageFPS=stressAverageFPS,stressP95Ms=stressP95Ms},true));Application.Quit(failures.Count==0?0:1);}
}
}
