using UnityEngine;using System.Collections.Generic;using System;using System.Globalization;
namespace WitchPlayground {
[DefaultExecutionOrder(120)]public sealed class DeveloperPanel:MonoBehaviour {
 public static DeveloperPanel Instance;public bool Visible;public int Tab;bool editing,clearFocus;Vector2 scroll;Rect panel;float scale;GUIStyle text,field,button,header;readonly Dictionary<string,string> edits=new Dictionary<string,string>();WitchPlayer p;RpgProgress stats;PlaygroundView view;Light moon;ForestOptions options;
 public static bool InputCaptured=>Instance&&Instance.Visible&&Instance.editing;
 public static bool PointerOver{get{if(!Instance||!Instance.Visible)return false;float s=Mathf.Min(Screen.width/1280f,Screen.height/800f);return Instance.panel.Contains(new Vector2(Input.mousePosition.x/s,(Screen.height-Input.mousePosition.y)/s));}}
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var p=UnityEngine.Object.FindAnyObjectByType<WitchPlayer>();if(p&&!p.GetComponent<DeveloperPanel>())p.gameObject.AddComponent<DeveloperPanel>();}
 void Awake(){Instance=this;}
 void Start(){p=GetComponent<WitchPlayer>();stats=GetComponent<RpgProgress>();view=Camera.main.GetComponent<PlaygroundView>();options=FindAnyObjectByType<ForestOptions>();foreach(var l in FindObjectsByType<Light>())if(l.name=="Moonlight")moon=l;LoadTuning();}
 public void Toggle(){Visible=!Visible;editing=false;clearFocus=true;p.CancelCharge();}
 void Update(){if(RpgSession.Instance.Playing&&!RpgSession.Instance.Creating&&(Input.GetKeyDown(KeyCode.Alpha0)||Input.GetKeyDown(KeyCode.Keypad0))&&!editing)Toggle();if(Visible&&(Input.GetKeyDown(KeyCode.Return)||Input.GetKeyDown(KeyCode.KeypadEnter))){editing=false;clearFocus=true;}}
 [Serializable]public class Profile {public PlaygroundView.Settings camera;public float walk,run,jump,walkStride,runStride,charge,damage,mana,moon,moonPitch,moonYaw,fog,shadowDistance;public bool shadows;}
 public Profile Capture(){return new Profile{camera=view.Capture(),walk=p.walkSpeed,run=p.runSpeed,jump=p.jumpHeight,walkStride=p.walkStrideSpeed,runStride=p.runStrideSpeed,charge=stats.baseChargeSeconds,damage=stats.damageTuning,mana=stats.manaRegenTuning,moon=moon?moon.intensity:1.1f,moonPitch=moon?moon.transform.eulerAngles.x:55,moonYaw=moon?moon.transform.eulerAngles.y:335,fog=RenderSettings.fogDensity,shadowDistance=QualitySettings.shadowDistance,shadows=options.EnvironmentShadows};}
 public void Apply(Profile d){if(d.camera!=null)view.Apply(d.camera);p.walkSpeed=Mathf.Clamp(d.walk,.5f,6);p.runSpeed=Mathf.Clamp(d.run,1,10);p.jumpHeight=Mathf.Clamp(d.jump,.1f,3);p.walkStrideSpeed=Mathf.Clamp(d.walkStride,.3f,4);p.runStrideSpeed=Mathf.Clamp(d.runStride,.5f,6);stats.baseChargeSeconds=Mathf.Clamp(d.charge,.2f,4);stats.damageTuning=Mathf.Clamp(d.damage,.1f,5);stats.manaRegenTuning=Mathf.Clamp(d.mana,0,5);p.fullChargeSeconds=stats.baseChargeSeconds/stats.CastSpeed;if(moon){moon.intensity=d.moon;moon.transform.rotation=Quaternion.Euler(d.moonPitch,d.moonYaw,0);}RenderSettings.fogDensity=d.fog;QualitySettings.shadowDistance=d.shadowDistance;options.SetEnvironmentShadows(d.shadows);}
 public void SaveTuning(){if(p&&stats&&!RpgSession.Instance.Testing){PlayerPrefs.SetString("WitchRPG.Tuning.v41",JsonUtility.ToJson(Capture()));PlayerPrefs.Save();}}
 public void LoadTuning(){if(!RpgSession.Instance.Testing&&PlayerPrefs.HasKey("WitchRPG.Tuning.v41"))try{Apply(JsonUtility.FromJson<Profile>(PlayerPrefs.GetString("WitchRPG.Tuning.v41")));}catch(Exception e){Debug.LogWarning("Tuning: "+e.Message);}}
 string T(string ko,string en,string ja)=>Loc.T(ko,en,ja);
 void Styles(){if(text!=null)return;var font=GetComponent<RpgUI>().font;text=new GUIStyle(GUI.skin.label){font=font,fontSize=14,wordWrap=true};text.normal.textColor=new Color(1,.94f,.78f);header=new GUIStyle(text){fontSize=20};field=new GUIStyle(GUI.skin.textField){font=font,fontSize=14,alignment=TextAnchor.MiddleCenter};button=new GUIStyle(GUI.skin.button){font=font,fontSize=14};}
 void Label(float y,string value)=>GUI.Label(new Rect(18,y,374,42),value,text);
 float Row(ref float y,string id,string label,float value,float min,float max){GUI.Label(new Rect(18,y,244,22),label,text);float old=value;float next=GUI.HorizontalSlider(new Rect(18,y+26,257,18),value,min,max);string key="dev_"+id;if(!edits.ContainsKey(key)||GUI.GetNameOfFocusedControl()!=key||Mathf.Abs(next-old)>.0001f)edits[key]=next.ToString("0.###",CultureInfo.InvariantCulture);GUI.SetNextControlName(key);string content=GUI.TextField(new Rect(290,y+10,95,28),edits[key],field);edits[key]=content;if(float.TryParse(content,NumberStyles.Float,CultureInfo.InvariantCulture,out float typed)&&!float.IsNaN(typed)&&!float.IsInfinity(typed))next=typed;y+=51;return Mathf.Clamp(next,min,max);}
 void OnGUI(){if(!Visible||!RpgSession.Instance.Playing)return;Styles();scale=Mathf.Min(Screen.width/1280f,Screen.height/800f);float h=Screen.height/scale;panel=new Rect(15,112,418,Mathf.Min(610,h-145));GUI.depth=-100;var old=GUI.matrix;GUI.matrix=Matrix4x4.Scale(Vector3.one*scale);GUI.color=new Color(.12f,.065f,.18f,.97f);GUI.DrawTexture(panel,Texture2D.whiteTexture);GUI.color=Color.white;GUI.BeginGroup(panel);GUI.Label(new Rect(16,12,350,31),T("개발자 설정 · 0","Developer settings · 0","開発設定 · 0"),header);if(GUI.Button(new Rect(375,10,28,28),"×",button))Toggle();int next=GUI.Toolbar(new Rect(14,48,390,31),Tab,new[]{T("카메라","Camera","カメラ"),T("이동","Movement","移動"),T("전투","Combat","戦闘"),T("환경","World","環境")},button);if(next!=Tab){Tab=next;scroll=Vector2.zero;clearFocus=true;}float bodyHeight=Tab==0?680:Tab==1?450:Tab==2?400:470;scroll=GUI.BeginScrollView(new Rect(0,88,416,panel.height-166),scroll,new Rect(0,0,397,bodyHeight));float y=8;
 if(Tab==0){var c=view.Capture();c.pitch=Row(ref y,"pitch",T("내려다보는 각도 ° (낮을수록 백뷰)","Pitch ° (lower = behind)","俯角 °（低いほど背面）"),c.pitch,10,80);c.yaw=Row(ref y,"yaw",T("좌우 방향 °","Yaw °","左右の角度 °"),c.yaw,0,360);c.zoom=Row(ref y,"zoom",T("화면 범위 (작을수록 크게 보임)","View size (smaller = closer)","表示範囲（小さいほど拡大）"),c.zoom,2,12);c.height=Row(ref y,"height",T("바라보는 높이 m","Focus height m","注視点の高さ m"),c.height,-.5f,2);c.distance=Row(ref y,"distance",T("카메라 거리 m","Camera distance m","カメラ距離 m"),c.distance,3,35);c.follow=Row(ref y,"follow",T("따라오는 속도","Follow speed","追従速度"),c.follow,1,25);c.sensitivity=Row(ref y,"sensitivity",T("회전 감도","Orbit sensitivity","回転感度"),c.sensitivity,.3f,8);c.zoomStep=Row(ref y,"wheel",T("휠 확대 속도","Wheel zoom speed","ホイール速度"),c.zoomStep,.05f,1);c.orthographic=GUI.Toggle(new Rect(18,y,360,28),c.orthographic,T("직교 투영 (해제하면 원근)","Orthographic (off = perspective)","平行投影（解除で透視投影）"),button);y+=36;c.fov=Row(ref y,"fov",T("원근 시야각 FOV °","Perspective FOV °","透視視野角 FOV °"),c.fov,25,85);view.Apply(c);Label(y,T("Shift + 우클릭 드래그: 시점 회전\n직교 투영에서는 거리보다 화면 범위로 확대합니다.","Shift + RMB drag: orbit\nIn orthographic mode, view size controls zoom.","Shift + 右ドラッグ: 回転\n平行投影では表示範囲で拡大します。"));y+=60;if(GUI.Button(new Rect(18,y,366,36),T("현재 화면을 기본 백뷰로 저장 (Z)","Save current view as default (Z)","現在の視点を既定に保存（Z）"),button)){view.SaveBackView();RpgSession.Instance.SaveSettings();}y+=44;if(GUI.Button(new Rect(18,y,178,32),T("초기값 · 29.3°","Factory · 29.3°","初期値 · 29.3°"),button))view.FactoryCamera();if(GUI.Button(new Rect(205,y,179,32),T("카메라 값 복사","Copy camera values","カメラ値をコピー"),button))GUIUtility.systemCopyBuffer=JsonUtility.ToJson(view.Capture(),true);}
 else if(Tab==1){p.walkSpeed=Row(ref y,"walk",T("걷기 속도 m/s","Walk speed m/s","歩行速度 m/s"),p.walkSpeed,.5f,6);p.runSpeed=Row(ref y,"run",T("달리기 속도 m/s","Run speed m/s","走行速度 m/s"),p.runSpeed,1,10);p.jumpHeight=Row(ref y,"jump",T("점프 높이 m","Jump height m","ジャンプ高度 m"),p.jumpHeight,.1f,3);p.walkStrideSpeed=Row(ref y,"walkStride",T("걷기 모션 기준 속도","Walk animation reference speed","歩行モーション基準速度"),p.walkStrideSpeed,.3f,4);p.runStrideSpeed=Row(ref y,"runStride",T("달리기 모션 기준 속도","Run animation reference speed","走行モーション基準速度"),p.runStrideSpeed,.5f,6);Label(y,T("모션 기준 속도가 작을수록 발걸음이 빨라집니다.","Lower reference speeds make footsteps faster.","基準速度を下げると足運びが速くなります。"));y+=55;Label(y,"XYZ "+p.transform.position.ToString("F2")+"\n"+T("접지: ","Grounded: ","接地: ")+p.Grounded+" · "+p.State);}
 else if(Tab==2){stats.baseChargeSeconds=Row(ref y,"charge",T("기본 차징 시간 s","Base charge time s","基本チャージ時間 s"),stats.baseChargeSeconds,.2f,4);p.fullChargeSeconds=stats.baseChargeSeconds/stats.CastSpeed;stats.damageTuning=Row(ref y,"damage",T("피해 배율","Damage multiplier","ダメージ倍率"),stats.damageTuning,.1f,5);stats.manaRegenTuning=Row(ref y,"mana",T("MP 재생 배율","MP regeneration multiplier","MP回復倍率"),stats.manaRegenTuning,0,5);Label(y,"HP "+p.Health+" / "+p.maxHealth+" · MP "+stats.Mana.ToString("F0")+" / "+stats.MaxMana);y+=46;Label(y,T("치명타 확률 ","Critical chance ","会心率 ")+Mathf.RoundToInt(stats.CritChance*100)+"%\n"+T("서리 마법은 이동 중 시전 가능","Frost can be cast while moving","氷魔法は移動中に詠唱可能"));y+=62;if(GUI.Button(new Rect(18,y,366,34),T("HP / MP 회복","Restore HP / MP","HP / MP回復"),button))p.RestoreHealth();}
 else{if(moon){moon.intensity=Row(ref y,"moon",T("달빛 밝기","Moonlight intensity","月光の強さ"),moon.intensity,0,3);float pitch=Row(ref y,"moonPitch",T("그림자 광원 높이 °","Shadow light elevation °","影の光源高度 °"),moon.transform.eulerAngles.x,10,85);float yaw=Row(ref y,"moonYaw",T("그림자 광원 방향 °","Shadow light direction °","影の光源方向 °"),moon.transform.eulerAngles.y,0,360);moon.transform.rotation=Quaternion.Euler(pitch,yaw,0);}RenderSettings.fogDensity=Row(ref y,"fog",T("안개 밀도","Fog density","霧の密度"),RenderSettings.fogDensity,0,.05f);QualitySettings.shadowDistance=Row(ref y,"shadowDistance",T("그림자 표시 거리 m","Shadow distance m","影の表示距離 m"),QualitySettings.shadowDistance,10,80);bool shadows=GUI.Toggle(new Rect(18,y,366,32),options.EnvironmentShadows,T("환경 그림자 (1)","Environment shadows (1)","環境の影（1）"),button);if(shadows!=options.EnvironmentShadows)options.SetEnvironmentShadows(shadows);y+=45;Label(y,T("프레임 상한 60 · 현재 ","Frame cap 60 · Current ","上限60 FPS · 現在 ")+options.MeasuredFPS.ToString("F0")+" FPS");}
 GUI.EndScrollView();if(GUI.Button(new Rect(14,panel.height-66,188,36),T("설정 저장","Save settings","設定を保存"),button)){RpgSession.Instance.Save();clearFocus=true;}if(GUI.Button(new Rect(214,panel.height-66,188,36),T("저장값 불러오기","Reload settings","保存設定を読込"),button)){LoadTuning();clearFocus=true;}GUI.Label(new Rect(16,panel.height-25,390,22),T("실시간 적용 · 숫자 입력 후 Enter · 0 닫기","Live preview · Enter after typing · 0 closes","即時反映 · 入力後Enter · 0で閉じる"),new GUIStyle(text){fontSize=12});if(clearFocus){GUI.FocusControl(null);clearFocus=false;}editing=GUI.GetNameOfFocusedControl().StartsWith("dev_");GUI.EndGroup();GUI.matrix=old;}
}
}
