using UnityEngine;
using System.Linq;
namespace WitchPlayground {
[DefaultExecutionOrder(-50)]public sealed partial class RpgUI:MonoBehaviour {
 public enum Window{None,Status,Bag,Skills,Pause,Audio,Adventure}public static RpgUI Instance;public WitchPlayer player;public Font font;public Window ActiveWindow{get;private set;}
 public static bool Blocking=>DeveloperPanel.InputCaptured||Instance&&((RpgSession.Instance&&!RpgSession.Instance.Playing)||Instance.ActiveWindow!=Window.None||RpgProgress.Instance.PendingChoices>0||Instance.player.IsDead);
 public static bool SuppressCombatInput=>Instance&&Instance.suppressClick;public void ReleaseInputForTest(){suppressClick=false;}
 public static bool PointerOverHUD=>DeveloperPanel.PointerOver||Instance&&(Instance.suppressClick||Instance.OverHUD());
 Texture2D panel,atlas;GUIStyle title,label,small,dark,center;float scale,w,h;RpgProgress stats;RpgSession session;HeroRoster roster;ForestOptions options;ForestInteraction interaction;bool suppressClick;static string toast;static float toastUntil;string entered="";Window audioReturn;int hoveredSound;bool hoverSeen;
 void Awake(){Instance=this;player=GetComponent<WitchPlayer>();stats=GetComponent<RpgProgress>();session=GetComponent<RpgSession>();roster=GetComponent<HeroRoster>();options=FindAnyObjectByType<ForestOptions>();interaction=GetComponent<ForestInteraction>();panel=Resources.Load<Texture2D>("RPG/panel");atlas=Resources.Load<Texture2D>("RPG/controls");}
 void Update(){MenuInput();if(!session.Playing&&!NameEditing&&Input.GetKeyDown(KeyCode.Escape)){if(ActiveWindow!=Window.None)Close();else session.Creating=false;}Input.imeCompositionMode=NameEditing||DeveloperPanel.InputCaptured?IMECompositionMode.On:IMECompositionMode.Off;if((Input.GetKeyDown(KeyCode.Alpha2)||Input.GetKeyDown(KeyCode.Keypad2))&&!session.Creating&&!DeveloperPanel.InputCaptured)Loc.Toggle();if(session.Playing&&!player.TestControl&&!DeveloperPanel.InputCaptured){if(Input.GetKeyDown(KeyCode.C))Toggle(Window.Status);if(Input.GetKeyDown(KeyCode.B))Toggle(Window.Bag);if(Input.GetKeyDown(KeyCode.V))Toggle(Window.Skills);if(Input.GetKeyDown(KeyCode.Escape)){if(ActiveWindow!=Window.None)Close();else if(!player.IsDead)Open(Window.Pause);}}if(suppressClick&&!Input.GetMouseButton(0)&&!Input.GetMouseButton(1)&&!Input.GetKey(KeyCode.J)&&!Input.GetKey(KeyCode.E))suppressClick=false;bool modal=!session.Playing||ActiveWindow!=Window.None||stats.PendingChoices>0;Time.timeScale=modal?0:1;if(modal)player.CancelCharge();}
 public void Open(Window window){if(window==Window.Audio)audioReturn=ActiveWindow;ForestSound.Play("ui_open",null,.6f);ActiveWindow=window;player.ClearBufferedInput();player.CancelCharge();suppressClick=true;}public void Close(){ForestSound.Play("ui_back",null,.6f);ActiveWindow=ActiveWindow==Window.Audio?audioReturn:Window.None;suppressClick=true;if(stats.PendingChoices==0&&session.Playing&&ActiveWindow==Window.None)Time.timeScale=1;}void Toggle(Window window){if(ActiveWindow==window)Close();else Open(window);}
 public static void ClearToast(){toastUntil=0;}public static void Toast(string text){if(toast==text&&Time.unscaledTime<toastUntil)return;toast=text;toastUntil=Time.unscaledTime+2;}
 bool OverHUD(){float s=Mathf.Min(Screen.width/1280f,Screen.height/800f);float x=Input.mousePosition.x/s,y=(Screen.height-Input.mousePosition.y)/s;return y>Screen.height/s-128||y<235&&x>Screen.width/s-240||y<(Adventure?325:110)&&x<316;}
 void Styles(){if(title!=null)return;label=new GUIStyle(GUI.skin.label){font=font,fontSize=18,wordWrap=true,alignment=TextAnchor.UpperLeft};label.normal.textColor=new Color(1,.94f,.76f);title=new GUIStyle(label){fontSize=24};small=new GUIStyle(label){fontSize=12};dark=new GUIStyle(label);dark.normal.textColor=new Color(.24f,.11f,.29f);center=new GUIStyle(label){alignment=TextAnchor.MiddleCenter};}
 void Text(Rect r,string text,GUIStyle style,bool outline=false){r.x=Mathf.Round(r.x);r.y=Mathf.Round(r.y);if(outline){var back=new GUIStyle(style);back.normal.textColor=new Color(.16f,.065f,.22f);GUI.Label(new Rect(r.x+1,r.y+1,r.width,r.height),text,back);}GUI.Label(r,text,style);}
 void OnGUI(){if(Event.current.type==EventType.Layout){if(!hoverSeen)hoveredSound=0;hoverSeen=false;}Styles();BeginMenu();if(font&&font.material.mainTexture)font.material.mainTexture.filterMode=FilterMode.Point;scale=Mathf.Min(Screen.width/1280f,Screen.height/800f);w=Screen.width/scale;h=Screen.height/scale;GUI.matrix=Matrix4x4.Scale(Vector3.one*scale);GUI.skin.font=font;if(!session.Playing){GUI.enabled=ActiveWindow!=Window.Audio;DrawOpening();GUI.enabled=true;if(ActiveWindow==Window.Audio){GUI.color=new Color(.075f,.035f,.12f,.88f);GUI.DrawTexture(new Rect(0,0,w,h),Texture2D.whiteTexture);GUI.color=Color.white;DrawAudioSettings();}EndMenu();GUI.matrix=Matrix4x4.identity;return;}DrawWorld();menuCollect=false;GUI.enabled=!Blocking;DrawHUD();GUI.enabled=true;menuCollect=MenuActive;if(Blocking){GUI.color=new Color(.075f,.035f,.12f,.77f);GUI.DrawTexture(new Rect(0,0,w,h),Texture2D.whiteTexture);GUI.color=Color.white;}if(player.IsDead)DrawDeath();else if(stats.PendingChoices>0)DrawLevel();else if(ActiveWindow==Window.Status)DrawStatus();else if(ActiveWindow==Window.Bag)DrawBag();else if(ActiveWindow==Window.Skills)DrawSkills();else if(ActiveWindow==Window.Pause)DrawPause();else if(ActiveWindow==Window.Audio)DrawAudioSettings();else if(ActiveWindow==Window.Adventure)DrawAdventureWindow();if(Time.unscaledTime<toastUntil&&!Blocking){Icon(new Rect(w/2-300,112,600,54),9);Text(new Rect(w/2-275,119,550,40),toast,center,true);}EndMenu();GUI.matrix=Matrix4x4.identity;}
 Rect UV(int i){float x=(i%4)*.25f;if(i<4)return new Rect(x,.725f,.25f,.275f);if(i<8)return new Rect(x,.465f,.25f,.26f);if(i==8)return new Rect(.036f,.269f,.181f,.176f);if(i==9||i==10)return new Rect(x+.007f,.317f,.235f,.076f);if(i==11)return new Rect(.804f,.288f,.135f,.138f);return new Rect(x+.016f,.127f,.222f,.044f);}
 void Icon(Rect r,int index){if(index>=4&&index<=7&&roster&&roster.Selected>0){GUI.DrawTextureWithTexCoords(r,atlas,UV(8),true);string[] ko=roster.Selected==1?new[]{"검격","잔영","광역","패링"}:new[]{"사격","연사","덫","화살비"};string[] en=roster.Selected==1?new[]{"SLASH","DASH","FAN","PARRY"}:new[]{"ARROW","TRIPLE","TRAP","RAIN"};string[] ja=roster.Selected==1?new[]{"剣撃","残影","範囲","防御"}:new[]{"射撃","連射","罠","矢雨"};if(stats.Cooldown((SpellId)(index-4))<=0)Text(r,Loc.T(ko[index-4],en[index-4],ja[index-4]),new GUIStyle(center){fontSize=12},true);return;}GUI.DrawTextureWithTexCoords(r,atlas,UV(index),true);}
 void Bar(Rect r,float value,int fill){Icon(r,12);GUI.BeginGroup(new Rect(r.x,r.y,r.width*Mathf.Clamp01(value),r.height));Icon(new Rect(0,0,r.width,r.height),fill);GUI.EndGroup();}
 bool Button(Rect r,string text,bool pale=false){GUI.color=r.Contains(Event.current.mousePosition)?new Color(1,.9f,.72f):Color.white;Icon(r,pale?10:9);GUI.color=Color.white;HoverSound(r);bool click=MenuButton(r);if(click)ForestSound.Play("ui_click",null,.55f);var style=new GUIStyle(center){fontSize=18};style.normal.textColor=pale?dark.normal.textColor:new Color(1,.95f,.80f);Text(new Rect(r.x+20,r.y+2,r.width-40,r.height-4),text,style,!pale);return click;}
 bool IconButton(Rect r,int index,string text,bool selected=false){Color tint=GUI.color;GUI.color=selected?new Color(1,.75f,.35f):tint;Icon(r,8);GUI.color=tint;Icon(new Rect(r.x+8,r.y+6,r.width-16,r.height-30),index);Text(new Rect(r.x+4,r.yMax-24,r.width-8,20),text,new GUIStyle(center){fontSize=12},true);HoverSound(r);bool clicked=MenuButton(r);if(clicked)ForestSound.Play("ui_select",null,.5f);return clicked;}
 Rect Panel(string heading,float width=580,float height=700,bool close=true){var r=new Rect((w-width)/2,(h-height)/2,width,height);GUI.DrawTexture(r,panel);Text(new Rect(r.x+55,r.y+height*.105f-18,width-110,36),heading,new GUIStyle(title){alignment=TextAnchor.MiddleCenter},true);if(close){var x=new Rect(r.xMax-58,r.y+height*.105f-13,26,26);Icon(x,11);if(MenuButton(x,true))Close();}return r;}
 void DrawOpening(){var r=new Rect(w/2-50,155,475,510);if(session.Creating)PrepareNameEntry(new Rect(r.x+62,r.y+220,350,50),new Rect(r.x+62,r.y+297,350,54));GUI.color=new Color(.06f,.03f,.10f,.8f);GUI.DrawTexture(new Rect(0,0,w,h),Texture2D.whiteTexture);GUI.color=Color.white;Text(new Rect(0,32,w,58),Loc.T("달빛숲의 모험","Moonlit Forest","月明かりの森"),new GUIStyle(title){fontSize=36,alignment=TextAnchor.MiddleCenter},true);Text(new Rect(0,95,w,34),Loc.T("작은 영웅, 깨어나는 은빛 달","Little heroes beneath a silver moon","小さな英雄と目覚める銀の月"),center,true);
  float x=w/2-445;if(roster.preview){Icon(new Rect(x,150,350,480),8);var portrait=new Rect(x+12,162,326,456);GUI.DrawTexture(portrait,roster.preview,ScaleMode.ScaleToFit);float imageHeight=portrait.width*roster.preview.height/roster.preview.width;var imageRect=new Rect(portrait.x,portrait.center.y-imageHeight/2,portrait.width,imageHeight);roster.PreviewInput(imageRect,session.Creating&&GUI.enabled);}Text(new Rect(x,636,350,38),roster.ClassName(roster.Selected),new GUIStyle(title){alignment=TextAnchor.MiddleCenter},true);if(session.Creating)Text(new Rect(x-15,677,380,26),Loc.T("좌클릭 드래그로 돌려보기","Left-drag to rotate","左ドラッグで回転"),new GUIStyle(small){alignment=TextAnchor.MiddleCenter},true);
  GUI.DrawTexture(r,panel);Text(new Rect(r.x+40,r.y+36,r.width-80,40),session.Creating?Loc.T("새로운 모험","New Adventure","新しい冒険"):Loc.T("은빛 달의 부름","Call of the Silver Moon","銀の月の呼び声"),new GUIStyle(title){alignment=TextAnchor.MiddleCenter},true);
  if(!session.Creating){if(Button(new Rect(r.x+62,r.y+140,350,54),Loc.T("시작하기","Start","はじめる"),true)){session.Creating=true;roster.PlayIntro();}GUI.enabled=session.HasSave&&ActiveWindow!=Window.Audio;if(Button(new Rect(r.x+62,r.y+212,350,54),Loc.T("불러오기","Load Game","つづきから"),true))session.LoadGame();GUI.enabled=ActiveWindow!=Window.Audio;if(Button(new Rect(r.x+62,r.y+285,350,50),"2 · "+Loc.LanguageName))Loc.Toggle();if(Button(new Rect(r.x+62,r.y+356,350,50),Loc.T("종료","Quit","終了")))session.Quit();}
  else {for(int i=0;i<3;i++)if(Button(new Rect(r.x+48+i*128,r.y+105,123,48),roster.ClassName(i),roster.Selected==i))roster.Select(i);Text(new Rect(r.x+61,r.y+175,350,36),Loc.T("이름 (1~12자)","Name (1–12)","名前（1〜12文字）"),dark);var field=new GUIStyle(GUI.skin.textField){font=font,fontSize=24,alignment=TextAnchor.MiddleLeft,padding=new RectOffset(12,12,6,6)};field.normal.textColor=dark.normal.textColor;DrawNameEntry(new Rect(r.x+62,r.y+220,350,50),new Rect(r.x+62,r.y+297,350,54),field);if(Button(new Rect(r.x+62,r.y+297,350,54),Loc.T("모험 시작","Begin Adventure","冒険をはじめる"),true)){if(session.NewGame(ConfirmedName(),roster.Selected))Close();}if(Button(new Rect(r.x+62,r.y+367,350,48),Loc.T("뒤로","Back","戻る")))session.Creating=false;}
  if(Button(new Rect(r.x+62,r.y+425,350,38),Loc.T("소리 설정","Audio Settings","サウンド設定"),true))Open(Window.Audio);
  if(session.Notice.Length>0)Text(new Rect(w/2-350,h-70,700,40),session.Notice,center,true);Text(new Rect(20,h-35,w-40,24),"v4.20 · 2 · "+Loc.LanguageName+Loc.T("   |   창 가장자리를 드래그해 크기를 조절하세요.","   |   Drag the window edge to resize.","   |   ウィンドウの端をドラッグしてサイズ変更。"),small,true);
 }
 void DrawHUD(){Icon(new Rect(16,16,300,90),8);Icon(new Rect(25,25,65,68),2);Text(new Rect(102,28,202,34),session.PlayerName,title,true);Text(new Rect(102,67,205,22),"Lv."+stats.Level+"  "+stats.XP+" / "+stats.NeededXP+" XP",small,true);DrawMinimap();DrawObjective();
  float start=w/2-163;for(int i=0;i<4;i++){var id=(SpellId)i;var r=new Rect(start+i*83,h-113,76,84);bool known=stats.Learned(id);GUI.color=known?Color.white:new Color(.4f,.4f,.4f);bool click=IconButton(r,4+i,i==0?"J / LMB":i==1?"U":i==2?"I":"K",i>0&&stats.SelectedSkill==id);GUI.color=Color.white;if(click&&i>0){stats.SelectedSkill=id;Toast(stats.SpellName(id)+Loc.T(" · 우클릭 시전"," · Right-click to cast"," · 右クリックで発動"));}if(stats.Cooldown(id)>0)Text(new Rect(r.x,r.y+20,r.width,40),Mathf.CeilToInt(stats.Cooldown(id)).ToString(),new GUIStyle(center){fontSize=24},true);if(r.Contains(Event.current.mousePosition))Text(new Rect(start-90,h-157,505,36),stats.SpellName(id)+(known?" · "+stats.Cost(id)+" MP":Loc.T(" · 미습득"," · Locked"," · 未習得")),center,true);}
  Text(new Rect(start-60,h-29,450,20),"Tab < · RMB: "+stats.SpellName(stats.SelectedSkill),new GUIStyle(center){fontSize=12},true);
  if(IconButton(new Rect(w-265,h-117,76,84),2,"C"))Toggle(Window.Status);if(IconButton(new Rect(w-180,h-117,76,84),1,"B"))Toggle(Window.Bag);if(IconButton(new Rect(w-95,h-117,76,84),3,"V"))Toggle(Window.Skills);
  Icon(new Rect(15,h-117,340,89),8);Text(new Rect(31,h-105,308,74),Loc.T("WASD 이동 · 방향+Space 회피\nJ / 좌클릭 기본공격 · 우클릭 선택스킬\nC 상태 · B 가방 · V 스킬 · Esc 메뉴\n0 개발자 · 1 그림자 · 2 언어 · Z 시점","WASD Move · Direction+Space Dodge\nJ / LMB Attack · RMB Selected skill\nC Stats · B Bag · V Skills · Esc Menu\n0 Developer · 1 Shadows · 2 Language · Z View","WASD 移動 · 方向+Space 回避\nJ / 左クリック 攻撃 · 右クリック スキル\nC 状態 · B バッグ · V スキル · Esc メニュー\n0 開発 · 1 影 · 2 言語 · Z 視点"),small,true);Bar(new Rect(18,h-9,w-36,7),stats.XP/(float)stats.NeededXP,15);
  if(player.ArrivalProtected)Text(new Rect(w/2-200,90,400,26),Loc.T("입장 보호 중","Arrival protection","入場保護中"),center,true);
  if(player.IsCharging){Bar(new Rect(w/2-145,h-166,290,17),player.Charge01,14);Text(new Rect(w/2-185,h-202,370,30),(roster.Selected==2&&player.ChargeUsesMouse&&player.Charge01>=1)?Loc.T("조준 완료 · 놓으면 발사","Ready · Release to fire","照準完了 · 離して発射"):(roster.Selected==2?Loc.T("집중 ","Focusing ","集中 "):Loc.T("마력 충전 ","Charging ","チャージ "))+Mathf.RoundToInt(player.Charge01*100)+"%",center,true);}if(player.IsChanneling){Bar(new Rect(w/2-145,h-166,290,17),player.Channel01,14);Text(new Rect(w/2-245,h-206,490,35),stats.SpellName(player.ChannelSpell)+" · "+player.ChannelRemaining.ToString("0.0")+Loc.T("초","s","秒"),center,true);Text(new Rect(w/2-230,h-235,460,24),Loc.T("이동·공격 시 취소 · 완료 시 MP 소모","Move / attack to cancel · MP spent on completion","移動・攻撃で中止 · 完了時MP消費"),new GUIStyle(center){fontSize=12},true);}else if(player.IsSpellCasting)Text(new Rect(w/2-200,h-206,400,35),Loc.T("스킬 시전 중","Casting spell","詠唱中"),center,true);
  Text(new Rect(20,h-151,365,28),"S+Space · "+(roster.Selected==0?Loc.T("후방 순간이동","Back blink","後方転移"):roster.Selected==1?Loc.T("방패 방어","Shield guard","盾防御"):Loc.T("백스텝","Backstep","バックステップ"))+"  "+(roster.Selected==2?player.Combat.BackstepCharges+"/3"+(player.Combat.NextBackstepCharge>0?"  +1 · "+player.Combat.NextBackstepCharge.ToString("0.0")+"s":""):(player.Combat.BackCooldown>0?player.Combat.BackCooldown.ToString("0.0")+"s":Loc.T("준비","Ready","準備完了"))),small,true);
  if(Time.time<stats.WeakenedUntil)Text(new Rect(20,113,300,30),Loc.T("공격력 -30%","Attack -30%","攻撃力 -30%"),label,true);
  var boss=FindObjectsByType<MoonwolfBoss>().FirstOrDefault(b=>!b.GetComponent<SlimeMonster>().IsDead);if(boss&&Vector3.Distance(boss.transform.position,player.transform.position)<20){var health=boss.GetComponent<SlimeMonster>();Bar(new Rect(w/2-215,25,430,17),health.Health/(float)health.maxHealth,13);Text(new Rect(w/2-215,49,430,30),health.DisplayName,center,true);if(boss.Casting)Text(new Rect(w/2-215,78,430,30),boss.ActionName,center,true);}
  if(interaction&&!Blocking){if(interaction.Near&&!player.IsCharging&&!player.IsSpellCasting){Icon(new Rect(w/2-200,h-172,400,42),9);Text(new Rect(w/2-180,h-170,360,38),"E · "+interaction.Near.Name,center,true);}if(interaction.Dialog&&Time.time<interaction.DialogUntil&&!(Adventure&&interaction.Dialog.kind==ForestInteractable.Kind.NPC&&!interaction.Dialog.healer)){Icon(new Rect(w/2-300,180,600,128),8);Text(new Rect(w/2-278,193,556,31),interaction.Dialog.Name,label,true);Text(new Rect(w/2-278,233,556,62),interaction.Dialog.Dialogue,label,true);}}
 }
 public int VisibleMinimapEnemies{get;private set;}
 void DrawMinimap(){var r=new Rect(w-224,16,207,194);Icon(r,8);var inner=new Rect(r.x+14,r.y+14,r.width-28,r.height-28);GUI.color=new Color(.07f,.13f,.13f);GUI.DrawTexture(inner,Texture2D.whiteTexture);GUI.color=Color.white;var map=GetComponent<ForestMinimap>();if(map&&map.Texture)GUI.DrawTexture(inner,map.Texture);float range=12;Vector3 right=Vector3.ProjectOnPlane(Camera.main.transform.right,Vector3.up).normalized,forward=Vector3.ProjectOnPlane(Camera.main.transform.forward,Vector3.up).normalized;Vector2 mid=inner.center;Dot(mid,6,new Color(.55f,1,.8f));VisibleMinimapEnemies=0;foreach(var e in FindObjectsByType<SlimeMonster>()){if(e.IsDead)continue;var d=e.transform.position-player.transform.position;var screen=Camera.main.WorldToViewportPoint(e.HitPoint);if(d.magnitude>range||screen.z<0||screen.x<0||screen.x>1||screen.y<0||screen.y>1)continue;Vector2 at=mid+new Vector2(Vector3.Dot(d,right),-Vector3.Dot(d,forward))*(inner.width*.45f/range);Dot(at,e.isBoss?12:5,e.isBoss?new Color(1,.35f,.85f):new Color(1,.42f,.28f));VisibleMinimapEnemies++;}DrawObjectiveDot(inner,mid,right,forward,range);Text(new Rect(r.x-3,r.yMax+4,r.width+6,26),Loc.T("달빛숲","Moonlit Forest","月明かりの森"),center,true);Text(new Rect(r.x,r.yMax+31,r.width,22),Adventure?AdventureProgress.T("금색: 목표 · 빨강: 적","Gold: objective · Red: enemy","金: 目標 · 赤: 敵"):session.BossDefeated?Loc.T("달늑대 토벌 완료","Moonwolf defeated","銀月の狼 討伐完了"):Loc.T("처치 ","Defeated ","討伐 ")+session.Kills+" / 30",new GUIStyle(center){fontSize=12},true);}
 void Dot(Vector2 pos,float size,Color color){GUI.color=new Color(.1f,.04f,.15f);GUI.DrawTexture(new Rect(pos.x-size/2-1,pos.y-size/2-1,size+2,size+2),Texture2D.whiteTexture);GUI.color=color;GUI.DrawTexture(new Rect(pos.x-size/2,pos.y-size/2,size,size),Texture2D.whiteTexture);GUI.color=Color.white;}
 void DrawWorld(){DrawQuestMarker();var cam=Camera.main;Vector3 at=cam.WorldToScreenPoint(player.transform.position);if(at.z>0){float x=at.x/scale,y=(Screen.height-at.y)/scale+7;Bar(new Rect(x-49,y,98,10),player.Health/(float)player.maxHealth,13);Bar(new Rect(x-49,y+13,98,10),stats.Mana/stats.MaxMana,14);}foreach(var e in FindObjectsByType<SlimeMonster>()){if(e.IsDead||e.isBoss||Vector3.Distance(e.transform.position,player.transform.position)>16)continue;var v=cam.WorldToScreenPoint(e.transform.position);if(v.z<0)continue;float x=v.x/scale,y=(Screen.height-v.y)/scale+7;Bar(new Rect(x-41,y,82,9),e.Health/(float)e.maxHealth,13);Text(new Rect(x-85,y+13,170,24),e.DisplayName,new GUIStyle(center){fontSize=12},true);if(e.Frozen||e.Rooted){var stateStyle=new GUIStyle(center){fontSize=12};stateStyle.normal.textColor=e.Frozen?new Color(.45f,.9f,1):new Color(.65f,1,.4f);Text(new Rect(x-85,y+35,170,22),e.Frozen&&e.Rooted?Loc.T("빙결 · 속박","Frozen · Rooted","凍結 · 拘束"):e.Frozen?Loc.T("빙결","Frozen","凍結"):Loc.T("속박","Rooted","拘束"),stateStyle,true);}}
  for(int i=RpgVFX.Texts.Count-1;i>=0;i--){var t=RpgVFX.Texts[i];float f=(Time.time-t.start)/t.duration;if(f>=1){RpgVFX.Texts.RemoveAt(i);continue;}var v=cam.WorldToScreenPoint(t.point+Vector3.up*(.4f+f*.85f));if(v.z<=0)continue;var r=new Rect(v.x/scale-100+t.offset.x,(Screen.height-v.y)/scale-25+t.offset.y,200,60);var style=new GUIStyle(center){fontSize=t.critical?28:20};style.normal.textColor=t.color;if(r.yMax>h-145||r.xMax<0||r.x>w)continue;Text(r,(t.critical?"Critical ":"")+t.text,style,true);}
 }
 void DrawStatus(){var r=Panel(Loc.T("상태창","Character","ステータス"));Text(new Rect(r.x+60,r.y+128,r.width-120,42),session.PlayerName+" · "+roster.ClassName(roster.Selected),new GUIStyle(dark){fontSize=24});string[] names={Loc.T("레벨","Level","レベル"),Loc.T("체력","HP","HP"),Loc.T("마나","MP","MP"),Loc.T("기본공격 피해","Basic damage","通常攻撃ダメージ"),Loc.T("치명타 확률","Critical chance","会心率"),Loc.T("충전 시간","Charge time","チャージ時間"),Loc.T("초당 MP 회복","MP regeneration","毎秒MP回復")};string[] vals={stats.Level.ToString(),player.Health+" / "+player.maxHealth,Mathf.FloorToInt(stats.Mana)+" / "+stats.MaxMana,(roster.Selected>0?Mathf.RoundToInt(player.Combat.AttackDamage).ToString():Mathf.RoundToInt(14*stats.BasicMultiplier)+" ~ "+Mathf.RoundToInt(64*stats.BasicMultiplier)),Mathf.RoundToInt(stats.CritChance*100)+"%",(roster.Selected==1?Loc.T("즉시","Instant","即時"):player.fullChargeSeconds.ToString("0.00")+"s"),stats.ManaRegen.ToString("0.0")};for(int i=0;i<names.Length;i++){float y=r.y+213+i*44;Text(new Rect(r.x+60,y,290,36),names[i],dark);Text(new Rect(r.x+352,y,163,36),vals[i],new GUIStyle(dark){alignment=TextAnchor.UpperRight});}Bar(new Rect(r.x+62,r.y+559,r.width-124,19),stats.XP/(float)stats.NeededXP,15);Text(new Rect(r.x+62,r.y+593,r.width-124,38),Loc.T("다음 레벨까지 ","To next level: ","次のレベルまで ")+(stats.NeededXP-stats.XP)+" XP",dark);}
 void DrawBag(){var r=Panel(Loc.T("가방 · 장비","Bag · Equipment","バッグ · 装備"));Icon(new Rect(r.x+58,r.y+130,96,96),0);Text(new Rect(r.x+170,r.y+132,340,62),roster.WeaponName,new GUIStyle(dark){fontSize=24});Text(new Rect(r.x+170,r.y+200,337,47),Loc.T("모험을 함께하는 기본 무기","Your starting weapon","冒険を共にする初期武器"),dark);if(Button(new Rect(r.x+62,r.y+265,r.width-124,48),stats.Equipped?Loc.T("장착 중 · 해제","Equipped · Unequip","装備中 · 外す"):Loc.T("장착하기","Equip","装備する"),true))stats.SetEquipped(!stats.Equipped);if(Adventure)DrawRelicBag(r);else for(int i=0;i<12;i++){var slot=new Rect(r.x+62+i%4*116,r.y+343+i/4*83,90,74);Icon(slot,8);if(i==0)Icon(new Rect(slot.x+10,slot.y+5,70,64),0);}Text(new Rect(r.x+62,r.y+613,r.width-124,43),stats.Equipped?Loc.T("무기 장착 중","Weapon equipped","武器を装備中"):Loc.T("무기 미장착 · 공격 불가","No weapon · Attacks disabled","未装備 · 攻撃できません"),dark);}
 string Description(SpellId id)=>roster.Selected>0?ClassSkills.Description(roster.Selected,id):id==SpellId.Energy?Loc.T("차징할수록 큰 발사체와 피해","Charge for size and damage","チャージで威力と弾が増大"):id==SpellId.Frost?Loc.T("이동 시전 · 칼날 3회 · 빙결 30%","Move while casting · 3 waves · 30% Freeze","移動詠唱 · 氷刃3連 · 30%凍結"):id==SpellId.Meteor?Loc.T("3초 시전 · 대폭발 · 화염 4초","3s cast · Impact · 4s burning","3秒詠唱 · 大爆発 · 4秒炎上"):Loc.T("5초 동안 매초 최대 HP 10% 회복","10% max HP each second for 5s","5秒間、毎秒最大HPの10%回復");
 void DrawSkills(){var r=Panel(Loc.T("스킬창","Spellbook","スキル"));for(int i=0;i<4;i++){var id=(SpellId)i;float y=r.y+130+i*120;Icon(new Rect(r.x+47,y,r.width-94,109),9);Icon(new Rect(r.x+58,y+14,70,72),4+i);Text(new Rect(r.x+143,y+12,340,30),stats.SpellName(id)+(stats.Learned(id)?"  Lv."+stats.Rank(id):Loc.T(" · 미습득"," · Locked"," · 未習得")),label,true);Text(new Rect(r.x+143,y+48,345,28),Description(id),new GUIStyle(small){fontSize=12},true);Text(new Rect(r.x+143,y+77,340,23),(i==0?"J / LMB":i==1?"U":i==2?"I":"K")+" · "+(i==0&&roster.Selected==0?"2~8":stats.Cost(id).ToString())+" MP"+(i>0?" · "+stats.SkillCooldown(id).ToString("0.0")+"s":""),small,true);if(i>0&&MenuButton(new Rect(r.x+47,y,r.width-94,109))){stats.SelectedSkill=id;Close();}}}
 void DrawLevel(){Text(new Rect(0,32,w,60),"LEVEL "+stats.Level,new GUIStyle(center){fontSize=36},true);Text(new Rect(0,94,w,34),Loc.T("세 축복 중 하나를 선택하세요.","Choose one of three blessings.","3つの祝福から1つを選んでください。"),center,true);if(stats.Offers==null)return;float width=322,start=(w-width*3-40)/2;for(int i=0;i<3;i++){var o=stats.Offers[i];var r=new Rect(start+i*(width+20),163,width,475);GUI.DrawTexture(r,panel);Text(new Rect(r.x+30,r.y+25,width-60,40),o.category==0?Loc.T("새 스킬","New Spell","新スキル"):o.category==1?Loc.T("스킬 강화","Spell Upgrade","スキル強化"):Loc.T("기본 능력","Power Up","基本能力"),center,true);Text(new Rect(r.x+37,r.y+94,width-74,75),stats.OfferTitle(o),new GUIStyle(dark){alignment=TextAnchor.MiddleCenter});Icon(new Rect(r.x+114,r.y+169,94,94),o.category<2?4+(int)o.spell:0);Text(new Rect(r.x+39,r.y+283,width-78,88),stats.OfferDescription(o),new GUIStyle(dark){alignment=TextAnchor.UpperCenter,fontSize=18});var choice=new Rect(r.x+39,r.y+397,width-78,43);if(Button(choice,Loc.T("선택","Choose","選ぶ"),true)){stats.Choose(i);suppressClick=true;break;}DrawCardFocus(r,choice);}}

 void HoverSound(Rect r){if(Event.current.type!=EventType.Repaint)return;bool inside=GUI.enabled&&r.Contains(Event.current.mousePosition);int id=Mathf.RoundToInt(r.x)*1000+Mathf.RoundToInt(r.y);if(inside){hoverSeen=true;if(hoveredSound!=id){hoveredSound=id;ForestSound.Play("ui_hover",null,.3f);}}}
 void DrawAudioSettings(){
  var r=Panel("",580,470);Text(new Rect(r.x+55,r.y+28,r.width-110,30),Loc.T("소리 설정","Audio Settings","サウンド設定"),new GUIStyle(title){fontSize=20,alignment=TextAnchor.MiddleCenter},true);
  var music=ForestMusic.Instance;var sound=ForestSound.Instance;if(!music||!sound)return;
  string[] labels={Loc.T("배경음악","Music","BGM"),Loc.T("효과음","Effects","効果音"),Loc.T("환경음","Ambience","環境音")};
  for(int i=0;i<3;i++){
   float y=r.y+127+i*78;float value=i==0?music.Volume:i==1?sound.EffectsVolume:sound.AmbientVolume;bool muted=i==0?music.Muted:i==1?sound.EffectsMuted:sound.AmbientMuted;
   Text(new Rect(r.x+55,y,130,32),labels[i],new GUIStyle(dark){fontSize=18});Text(new Rect(r.x+181,y,54,32),Mathf.RoundToInt(value*100)+"%",new GUIStyle(dark){fontSize=14});
   Color c=GUI.color;GUI.color=muted?new Color(.65f,.6f,.7f):new Color(.76f,.61f,.86f);float changed=MenuSlider(new Rect(r.x+236,y+10,161,22),value);GUI.color=c;
   if(Mathf.Abs(changed-value)>.001f){if(i==0)music.SetVolume(changed);else sound.SetVolume(i==2,changed);}
   if(Button(new Rect(r.x+410,y,115,34),muted?Loc.T("켜기","On","オン"):Loc.T("음소거","Mute","消音"),true)){if(i==0)music.SetMuted(!muted);else sound.SetMuted(i==2,!muted);}
  }
  Text(new Rect(r.x+55,r.y+370,r.width-110,42),Loc.T("설정은 자동으로 저장됩니다.","Settings are saved automatically.","設定は自動で保存されます。"),new GUIStyle(dark){alignment=TextAnchor.MiddleCenter,fontSize=14});
 }
 void DrawPause(){var r=Panel(Loc.T("잠시 쉬어가기","Paused","ひと休み"),500,680,false);if(Button(new Rect(r.x+66,r.y+139,368,49),Loc.T("계속하기","Resume","再開"),true))Close();if(Button(new Rect(r.x+66,r.y+213,368,49),"2 · "+Loc.LanguageName))Loc.Toggle();if(Button(new Rect(r.x+66,r.y+287,368,49),Loc.T("저장하기","Save","セーブ"),true)){session.Save();ForestSound.Play("ui_save");Toast(Loc.T("저장했습니다.","Saved.","セーブしました。"));Close();}if(Button(new Rect(r.x+66,r.y+361,368,49),Loc.T("저장 후 시작화면","Save & Title Screen","セーブしてタイトルへ")))session.ReturnToTitle();if(Button(new Rect(r.x+66,r.y+435,368,49),Loc.T("저장하고 종료","Save & Quit","セーブして終了")))session.Quit();if(Button(new Rect(r.x+66,r.y+505,368,38),Loc.T("소리 설정","Audio Settings","サウンド設定"),true))Open(Window.Audio);if(Adventure&&!Adventure.CanReturnCamp)Text(new Rect(r.x+66,r.y+602,368,32),AdventureProgress.T("주변 적과 거리를 벌린 후 이용하세요","Move away from enemies to return","敵から離れると帰還できます"),new GUIStyle(dark){fontSize=12,alignment=TextAnchor.MiddleCenter});GUI.enabled=!Adventure||Adventure.CanReturnCamp;if(Adventure&&Button(new Rect(r.x+66,r.y+559,368,38),AdventureProgress.T("캠프로 귀환 · 전투 외","Return to Camp · Out of combat","キャンプへ帰還 · 非戦闘時"),true)){if(Adventure.ReturnCamp())Close();}GUI.enabled=true;}
 void DrawDeath(){var r=Panel(Loc.T("잠시 숨을 고르세요","Take a Breath","ひと息つきましょう"),500,475,false);Text(new Rect(r.x+66,r.y+148,368,100),Loc.T("레벨, 장비와 의뢰 진행은 유지됩니다.\n다시 모험을 떠나세요.","Your level, gear and quest progress are kept.\nThe adventure continues.","レベルと装備はそのまま。\nもう一度、冒険へ。"),dark);if(Button(new Rect(r.x+66,r.y+307,368,54),Loc.T("체크포인트에서 부활","Return to checkpoint","復帰地点でよみがえる"),true)){player.Respawn();player.ProtectArrival();Close();}}
}
}
