using UnityEngine;
namespace WitchPlayground {
public sealed partial class RpgUI {
 AdventureProgress Adventure=>AdventureProgress.Instance;
 void DrawQuestMarker(){var a=Adventure;if(!a||!a.Ready||a.GuideMarker.Length==0||Vector3.Distance(player.transform.position,a.Guide)>24)return;var v=Camera.main.WorldToScreenPoint(a.GuideHead);if(v.z<=0)return;float x=v.x/scale,y=(Screen.height-v.y)/scale;var mark=new Rect(x-23,y-46,46,48);Icon(mark,8);var style=new GUIStyle(center){fontSize=38};style.normal.textColor=a.GuideMarker=="!"?new Color(.65f,1,.75f):new Color(1,.86f,.3f);Text(mark,a.GuideMarker,style,true);Text(new Rect(x-70,y+3,140,22),a.GuideMarker=="!"?AdventureProgress.T("의뢰 완료","Quest complete","依頼完了"):AdventureProgress.T("새 의뢰","New quest","新しい依頼"),new GUIStyle(center){fontSize=14},true);}
 void DrawObjective(){var a=Adventure;if(!a||!a.Ready||DeveloperPanel.Instance&&DeveloperPanel.Instance.Visible)return;Icon(new Rect(16,145,300,143),8);Text(new Rect(35,157,260,24),AdventureProgress.T("현재 목표","CURRENT OBJECTIVE","現在の目標"),small,true);Text(new Rect(35,188,260,52),a.Objective,new GUIStyle(label){fontSize=16},true);Text(new Rect(35,246,260,34),a.Hint,new GUIStyle(small){fontSize=12},true);if(a.Relics.Empowered)Text(new Rect(20,295,290,30),AdventureProgress.T("달빛 잔상 · 다음 기본공격 +30%","Moonlit Echo · Next basic +30%","月光の残響 · 次の通常攻撃+30%"),small,true);else if(a.Relics.MoveMultiplier>1)Text(new Rect(20,295,290,30),AdventureProgress.T("바람잎 · 이동속도 +20%","Windleaf · Movement +20%","風葉 · 移動速度+20%"),small,true);
  if(a.Near&&!Blocking&&!player.IsCharging&&!player.IsSpellCasting){Icon(new Rect(w/2-240,h-172,480,42),9);Text(new Rect(w/2-220,h-170,440,38),"E · "+a.Near.Label,center,true);}
 }
 void DrawObjectiveDot(Rect inner,Vector2 mid,Vector3 right,Vector3 forward,float range){var a=Adventure;if(!a||!a.Ready||a.Stage==AdventureStage.Reward||a.Stage==AdventureStage.Complete)return;Vector3 d=a.Target-player.transform.position;Vector2 v=new Vector2(Vector3.Dot(d,right),-Vector3.Dot(d,forward));Vector2 at=mid+Vector2.ClampMagnitude(v,range)*(inner.width*.43f/range);Dot(at,9,new Color(1,.86f,.28f));Text(new Rect(at.x-10,at.y-25,20,20),"!",new GUIStyle(center){fontSize=16},true);}
 void DrawRelicBag(Rect r){var a=Adventure;if(!a)return;Text(new Rect(r.x+62,r.y+340,r.width-124,32),AdventureProgress.T("유물 · 1개 장착","RELICS · One equipped","遺物 · 1個装備"),new GUIStyle(dark){fontSize=20});for(int i=0;i<3;i++){float y=r.y+383+i*74;bool own=a.Relics.Owns(i),equipped=a.Relics.State.equipped==i;Text(new Rect(r.x+62,y,290,27),own?AdventureRelics.Name(i):AdventureProgress.T("미발견 유물","Undiscovered relic","未発見の遺物"),new GUIStyle(dark){fontSize=16});Text(new Rect(r.x+62,y+29,290,39),own?AdventureRelics.Description(i):AdventureProgress.T("의뢰 보상으로 획득","Earned from adventure requests","依頼の報酬で獲得"),new GUIStyle(dark){fontSize=12});GUI.enabled=own;if(Button(new Rect(r.x+368,y+6,145,44),equipped?AdventureProgress.T("해제","Unequip","外す"):AdventureProgress.T("장착","Equip","装備"),true))a.Relics.Equip(equipped?-1:i);GUI.enabled=true;}}
 void DrawAdventureWindow(){var a=Adventure;if(!a){Close();return;}string heading=a.Stage==AdventureStage.Reward?AdventureProgress.T("숲이 건넨 선물","A Gift from the Forest","森からの贈り物"):a.Stage==AdventureStage.Gate?AdventureProgress.T("은빛 달의 부름","Call of the Silver Moon","銀の月の呼び声"):AdventureProgress.T("루미 · 숲길 안내자","Lumi · Forest Guide","ルミ · 森の案内人");var r=Panel(heading,760,680,a.Stage!=AdventureStage.Reward);
  string text=a.Stage==AdventureStage.Offer?AdventureProgress.T("숲길의 불빛이 꺼져가고 있어요. 길을 막은 적 네 마리를 물리치고, 두 오염 지점을 정화해 주세요. 그 너머 달늑대가 저주에 갇혀 있어요.\n\n금색 표식을 따라가세요. J 또는 좌클릭으로 공격합니다. 방향키와 Space로 위험을 피하세요.","The forest lights are fading. Defeat four enemies on the road, then cleanse two corrupted sites. Beyond them, the Moonwolf is trapped by a curse.\n\nFollow the gold marker. Attack with J or left click. Move with a direction and Space to dodge.","森の灯りが消えかけています。道をふさぐ4体を倒し、2つの汚染を浄化してください。その先で銀月の狼が呪いに囚われています。\n\n金色の目印へ。Jまたは左クリックで攻撃。方向キーとSpaceで回避できます。"):a.Stage==AdventureStage.Gate?AdventureProgress.T("이곳이 새로운 부활 지점입니다. 체력과 마나를 회복했어요.\n\n달늑대는 돌진, 서리 폭풍, 하울링을 사용합니다. 바닥의 예고 범위를 보고 회피하세요.\n\n쓰러져도 정화한 숲길은 유지됩니다. 보스 전투는 처음부터 다시 도전합니다.","This refuge is your new checkpoint. HP and MP are restored.\n\nThe Moonwolf uses a charge, frost storm and howl. Watch the warning areas and dodge.\n\nCleared sites remain cleared if you fall. The boss encounter starts fresh.","ここが新しい復帰地点です。HPとMPを回復しました。\n\n狼は突進、氷の嵐、遠吠えを使います。地面の予告を見て回避しましょう。\n\n倒れても浄化は維持されます。ボス戦は最初から再挑戦です。"):a.Stage==AdventureStage.Reward?(a.State.rewardSource==0?AdventureProgress.T("달늑대를 감싸던 보랏빛이 걷히고, 숲에 은빛이 돌아옵니다. 하지만 오래된 둥지에는 아직 오염이 남아 있습니다.\n유물 하나를 선택하세요. 선택한 유물을 장착하고 캠프로 돌아갑니다.","The violet curse lifts from the Moonwolf, and silver light returns to the forest. An old nest still holds traces of corruption.\nChoose one relic. It will be equipped, and you will return to camp.","狼の紫の呪いが晴れ、森に銀の光が戻ります。古い巣にはまだ汚染が残っています。\n遺物を1つ選ぶと装備してキャンプへ戻ります。"):AdventureProgress.T("의뢰를 마쳤습니다. 남은 유물 중 하나를 선택하세요. 소유한 유물은 가방에서 바꿀 수 있습니다.","Request complete. Choose a remaining relic. Switch owned relics in your bag.","依頼完了。残りの遺物を選んでください。持っている遺物はバッグで変更できます。")):a.Stage==AdventureStage.Complete?AdventureProgress.T("숲길도, 오래된 둥지도 평온을 되찾았어요. 도와줘서 고마워요.\n\n현재 준비된 모험을 모두 마쳤습니다. 유물과 성장 기록은 저장됩니다. 숲을 더 둘러보거나 메뉴에서 저장하고 마칠 수 있어요.","The forest road and old nest are peaceful again. Thank you.\n\nYou have completed all currently available adventures. Relics and progress are saved. Explore freely or save and leave through the menu.","森の道も古い巣も平穏を取り戻しました。ありがとう。\n\n現在遊べる冒険をすべて完了しました。遺物と成長は保存されます。自由に探索するか、メニューから保存して終了できます。"):AdventureProgress.T("숲의 불빛은 돌아왔지만, 아직 도움이 필요해요. 다음에 할 일을 골라 주세요. 선택하지 않은 의뢰도 나중에 할 수 있어요.\n\n달빛 약초: 숲길의 세 지점에서 약초 회수.\n꿀날개 둥지: 정예 꿀벌과 호위 둘을 처치하고 정화.\n각 의뢰를 마치면 남은 유물을 하나 받습니다.","The lights are back, but there is more to do. Choose a request; the other will remain available.\n\nMoon herbs: gather herbs at three road sites.\nHoneywing nest: defeat an elite bee and two guards, then cleanse the nest.\nEach request awards a remaining relic.","灯りは戻りましたが、まだ助けが必要です。依頼を選んでください。もう一方は後から遊べます。\n\n月光草：道の3か所で薬草を集める。\n蜂の巣：精鋭蜂と護衛2体を倒して浄化。\n各依頼で残りの遺物を1つ獲得します。");
  Text(new Rect(r.x+65,r.y+135,r.width-130,a.Stage==AdventureStage.Reward?120:310),text,new GUIStyle(dark){fontSize=18});
  if(a.Stage==AdventureStage.Offer){if(Button(new Rect(r.x+140,r.y+515,480,54),AdventureProgress.T("숲길로 출발","Accept the request","依頼を受ける"),true)&&a.AcceptMain())Close();}
  else if(a.Stage==AdventureStage.Gate){if(Button(new Rect(r.x+140,r.y+515,480,54),AdventureProgress.T("달늑대에게 도전","Face the Moonwolf","銀月の狼に挑む"),true)&&a.EnterBoss())Close();}
  else if(a.Stage==AdventureStage.Reward){for(int i=0;i<3;i++){float x=r.x+57+i*218;Icon(new Rect(x,r.y+282,210,271),8);Text(new Rect(x+15,r.y+300,180,57),AdventureRelics.Name(i),new GUIStyle(center){fontSize=18},true);Text(new Rect(x+20,r.y+370,170,108),AdventureRelics.Description(i),new GUIStyle(label){fontSize=14},true);GUI.enabled=!a.Relics.Owns(i);if(Button(new Rect(x+15,r.y+494,180,43),a.Relics.Owns(i)?AdventureProgress.T("보유 중","Owned","所持中"):AdventureProgress.T("선택","Choose","選ぶ"),true)&&a.ChooseRelic(i))Close();GUI.enabled=true;}}
  else if(a.Stage==AdventureStage.Camp){for(int i=0;i<2;i++){GUI.enabled=(a.State.sideDone&(1<<i))==0;if(Button(new Rect(r.x+125,r.y+477+i*68,510,50),i==0?AdventureProgress.T("달빛 약초 회수","Gather Moon Herbs","月光草を集める"):AdventureProgress.T("꿀날개 둥지 정화","Cleanse Honeywing Nest","蜂の巣を浄化"),true)&&a.AcceptSide(i))Close();GUI.enabled=true;}}
  else if(Button(new Rect(r.x+140,r.y+515,480,54),AdventureProgress.T("숲으로 돌아가기","Return to the forest","森に戻る"),true))Close();
 }
}
}
