using UnityEngine;
namespace WitchPlayground {
public sealed partial class RpgUI {
 AdventureProgress Adventure=>AdventureProgress.Instance;
 void DrawQuestMarker(){var a=Adventure;if(!a||!a.Ready||a.GuideMarker.Length==0||Vector3.Distance(player.transform.position,a.Guide)>24)return;var v=Camera.main.WorldToScreenPoint(a.GuideHead);if(v.z<=0)return;float x=v.x/scale,y=(Screen.height-v.y)/scale;var mark=new Rect(x-23,y-46,46,48);Icon(mark,8);var style=new GUIStyle(center){fontSize=38};style.normal.textColor=a.GuideMarker=="!"?new Color(.65f,1,.75f):new Color(1,.86f,.3f);Text(mark,a.GuideMarker,style,true);Text(new Rect(x-70,y+3,140,22),a.GuideMarker=="!"?AdventureProgress.T("의뢰 완료","Quest complete","依頼完了"):AdventureProgress.T("새 의뢰","New quest","新しい依頼"),new GUIStyle(center){fontSize=14},true);}
 int journalTab;
 void DrawObjective(){var a=Adventure;if(!a||!a.Ready||DeveloperPanel.Instance&&DeveloperPanel.Instance.Visible)return;Icon(new Rect(16,145,300,160),8);Text(new Rect(35,157,260,24),AdventureProgress.RegionName(a.RegionAt(player.transform.position))+" · Lv."+new[]{"1–3","3–6","6–9"}[a.RegionAt(player.transform.position)],small,true);Text(new Rect(35,187,260,65),a.Objective,new GUIStyle(label){fontSize=15},true);Text(new Rect(35,253,260,42),a.Hint,new GUIStyle(small){fontSize=12},true);
  if(a.Near&&!Blocking&&!player.IsCharging&&!player.IsSpellCasting){Icon(new Rect(w/2-240,h-172,480,42),9);Text(new Rect(w/2-220,h-170,440,38),"E · "+a.Near.Label,center,true);}
  if(stats.PendingChoices>0&&!Blocking){var r=new Rect(w/2-215,108,430,37);if(Button(r,AdventureProgress.T("성장 선택 ","Growth choices ","成長選択 ")+stats.PendingChoices+" · "+(a.CanManage?"E / L":AdventureProgress.T("안전한 곳에서 열기","Open when safe","安全な場所で開く")),true))TryOpenGrowth();}
  if((a.State.relicRewards>0||a.Quests.HasReward)&&!Blocking)Text(new Rect(25,309,310,26),AdventureProgress.T("L · 수령할 보상이 있습니다","L · Rewards available","L · 報酬を受け取れます"),small,true);
 }
 void DrawObjectiveDot(Rect inner,Vector2 mid,Vector3 right,Vector3 forward,float range){var a=Adventure;if(!a||!a.Ready)return;Vector3 d=a.Target-player.transform.position;Vector2 v=new Vector2(Vector3.Dot(d,right),-Vector3.Dot(d,forward));Vector2 at=mid+Vector2.ClampMagnitude(v,range)*(inner.width*.43f/range);Dot(at,9,new Color(1,.86f,.28f));}
 void DrawRelicBag(Rect r){var a=Adventure;if(!a)return;Text(new Rect(r.x+62,r.y+338,r.width-124,33),AdventureProgress.T("유물 · 정수 ","Relics · Essence ","遺物 · 精髄 ")+a.State.essence,new GUIStyle(dark){fontSize=18});for(int i=0;i<3;i++){float y=r.y+382+i*74;bool own=a.Relics.Owns(i);Text(new Rect(r.x+62,y,240,29),own?AdventureRelics.Name(i)+" +"+a.Relics.Rank(i):AdventureProgress.T("미발견 유물","Undiscovered relic","未発見の遺物"),new GUIStyle(dark){fontSize=14});Text(new Rect(r.x+62,y+29,215,38),own?a.Relics.EffectDescription(i):AdventureProgress.T("보스·후속 의뢰로 획득","Earn from boss / follow-up quests","ボス・続きの依頼で獲得"),new GUIStyle(dark){fontSize=11});GUI.enabled=own;if(Button(new Rect(r.x+287,y+4,94,39),a.Relics.State.equipped==i?AdventureProgress.T("해제","Off","外す"):AdventureProgress.T("장착","Equip","装備"),true))a.Relics.Equip(a.Relics.State.equipped==i?-1:i);GUI.enabled=own&&a.CanManage&&a.Relics.Rank(i)<3&&a.State.essence>=a.Relics.UpgradeCost(i);if(Button(new Rect(r.x+387,y+4,131,39),a.Relics.Rank(i)>=3?"MAX":AdventureProgress.T("강화 ","Upgrade ","強化 ")+a.Relics.UpgradeCost(i),true))a.Relics.Upgrade(i);GUI.enabled=true;}}
 public bool TryOpenGrowth(){if(stats.PendingChoices<=0||Adventure&&!Adventure.CanManage)return false;Open(Window.Growth);menuInputFrame=Time.frameCount;return true;}
 public void OpenJournal(int tab=0){journalTab=Mathf.Clamp(tab,0,3);Open(Window.Adventure);}
 void DrawAdventureWindow(){var a=Adventure;if(!a){Close();return;}var r=Panel(AdventureProgress.T("숲의 수첩 · L","Forest Journal · L","森の手帳 · L"),800,690);
  string[] tabs={AdventureProgress.T("탐사","Explore","探索"),AdventureProgress.T("사냥 의뢰","Hunts","狩り"),AdventureProgress.T("유물 보상","Relic rewards","遺物報酬"),AdventureProgress.T("쉼터","Refuge","休憩所")};
  journalTabDrawing=true;for(int i=0;i<4;i++)if(Button(new Rect(r.x+64+i*170,r.y+100,162,36),tabs[i],journalTab==i))journalTab=i;journalTabDrawing=false;
  if(journalTab==0)DrawJournalStory(r,a);else if(journalTab==1)DrawJournalHunts(r,a);else if(journalTab==2)DrawJournalRelics(r,a);else DrawJournalRefuge(r,a);
  Text(new Rect(r.x+64,r.yMax-98,r.width-128,34),a.CanManage?AdventureProgress.T("완료해도 현재 위치가 유지됩니다","Rewards keep you where you are","報酬を受け取っても移動しません"):AdventureProgress.T("보상·강화·성장 선택은 주변 적에게서 벗어난 뒤 이용하세요","Move away from enemies to claim rewards or choose growth","敵から離れて報酬・強化・成長を選ぼう"),new GUIStyle(dark){fontSize=13,alignment=TextAnchor.MiddleCenter});
 }
 void DrawJournalStory(Rect r,AdventureProgress a){
  Text(new Rect(r.x+68,r.y+156,r.width-136,60),a.Objective,new GUIStyle(dark){fontSize=21});
  string intro=AdventureProgress.T("원하는 구역에서 사냥하며 숲을 조사해 주세요. 어떤 적이든 첫 5마리 처치에 포함됩니다. 일반 적은 의뢰와 무관하게 다시 나타납니다.","Explore and hunt wherever you like. Any five enemies count for the first survey. Regular enemies return independently of quests.","好きな場所で狩りをして森を調べよう。最初の5体はどの敵でも対象。通常の敵は依頼と無関係に再出現します。");
  string survey=AdventureProgress.T("슬라임 +1 · 꿀벌 +2 · 정예 +5 · 첫 정화 +10\n조사 80점과 서로 다른 2구역 발견으로 달늑대가 해금됩니다. 권장 Lv.6–8이며, 더 준비한 뒤 도전해도 됩니다.","Slime +1 · Bee +2 · Elite +5 · First cleanse +10\n80 survey points and two discovered regions unlock the Moonwolf. Suggested Lv.6–8; challenge when ready.","スライム+1 · 蜂+2 · 精鋭+5 · 初浄化+10\n調査80と2地域発見で狼を解放。推奨Lv.6–8。準備してから挑戦できます。");
  string after=AdventureProgress.T("달늑대의 저주는 걷혔지만 숲 깊은 곳에 흔적이 남아 있습니다. 자유 사냥으로 유물을 강화하거나 다음 의뢰를 선택하세요. 쉼터에서 위험 단계를 직접 바꿀 수 있습니다.","The curse lifts, but traces remain deeper in the forest. Hunt to upgrade relics or choose a follow-up request. Change danger at a refuge.","呪いは解けましたが森の奥に痕跡が残っています。狩りで遺物を強化し、次の依頼を選ぼう。休憩所で危険度を変更できます。");
  Text(new Rect(r.x+68,r.y+223,r.width-136,180),!a.State.mainAccepted?intro:a.State.bossCleared?after:survey,new GUIStyle(dark){fontSize=17});
  if(!a.State.mainAccepted){if(Button(new Rect(r.x+150,r.y+436,500,49),AdventureProgress.T("숲 조사 시작","Begin the survey","森の調査を始める"),true)){a.AcceptMain();Close();}}
  else if(a.State.bossCleared){for(int i=0;i<2;i++){bool done=(a.State.sideDone&(1<<i))!=0,active=a.State.sideActive==i;GUI.enabled=!done&&a.State.sideActive<0;if(Button(new Rect(r.x+82+i*320,r.y+426,308,50),(i==0?AdventureProgress.T("달빛 약초 3곳","Three moon herbs","月光草3か所"):AdventureProgress.T("꿀날개 정예 의뢰","Elite Honeywing request","精鋭蜂の依頼"))+(done?" ✓":active?" …":""),true)){a.AcceptSide(i);Close();}GUI.enabled=true;}if(a.State.sideActive>=0)Text(new Rect(r.x+80,r.y+488,640,34),a.State.sideActive==0?AdventureProgress.T("약초 진행 ","Herbs ","薬草 ")+a.HerbCount+" / 3":AdventureProgress.T("꿀날개 둥지 사건을 완료하세요","Complete the Honeywing nest event","蜂の巣の事件を完了しよう"),dark);}
  else if(Button(new Rect(r.x+150,r.y+432,500,46),AdventureProgress.T("사냥 의뢰 고르기","Choose a hunt","狩りの依頼を選ぶ"),true))journalTab=1;
  GUI.enabled=stats.PendingChoices>0&&a.CanManage;if(Button(new Rect(r.x+150,r.y+544,500,43),AdventureProgress.T("성장 선택 대기 ","Pending growth ","成長選択待ち ")+stats.PendingChoices,true))TryOpenGrowth();GUI.enabled=true;
 }
 void DrawJournalHunts(Rect r,AdventureProgress a){Text(new Rect(r.x+68,r.y+151,r.width-136,39),AdventureProgress.T("최대 2개 · 수락 후 처치 집계 · 완료 후 다시 선택","Up to two hunts · Kills count after accepting · New choices after claiming","最大2件 · 受注後の撃破を集計 · 報酬後に次を選択"),new GUIStyle(dark){fontSize=14});for(int i=0;i<3;i++){var q=a.Quests.State.jobs[i];float y=r.y+203+i*123;Text(new Rect(r.x+70,y,420,35),a.Quests.Title(q)+"  "+q.count+" / "+q.Target,new GUIStyle(dark){fontSize=20});Text(new Rect(r.x+70,y+39,400,31),AdventureProgress.T("보상: 경험치 24~28 · 정수 8","Reward: 24–28 XP · 8 essence","報酬: 経験値24–28 · 精髄8"),new GUIStyle(dark){fontSize=13});GUI.enabled=a.State.mainAccepted&&(!q.Complete||a.CanManage);if(Button(new Rect(r.x+491,y,235,42),q.Complete?AdventureProgress.T("보상 받기","Claim","報酬を受け取る"):q.active?(a.Quests.Tracked==q?AdventureProgress.T("추적 중","Tracking","追跡中"):AdventureProgress.T("이 의뢰 추적","Track this hunt","この依頼を追跡")):AdventureProgress.T("수락","Accept","受注"),true)){if(q.Complete)a.Quests.Claim(i);else if(q.active){a.Quests.State.tracked=i;a.Save();}else if(!a.Quests.Accept(i))Toast(AdventureProgress.T("의뢰는 최대 2개까지 수락할 수 있습니다","You can accept up to two hunts","受注できる狩りは最大2件です"));}GUI.enabled=true;if(q.active&&Button(new Rect(r.x+491,y+49,235,31),AdventureProgress.T("포기 · 진행 초기화","Abandon · Reset progress","放棄 · 進行リセット")))a.Quests.Abandon(i);}}
 void DrawJournalRelics(Rect r,AdventureProgress a){Text(new Rect(r.x+67,r.y+153,r.width-134,61),AdventureProgress.T("보관된 유물 보상 ","Stored relic rewards ","保管中の遺物報酬 ")+a.State.relicRewards+" · "+AdventureProgress.T("숲의 정수 ","Essence ","精髄 ")+a.State.essence,new GUIStyle(dark){fontSize=19});for(int i=0;i<3;i++){var card=new Rect(r.x+63+i*226,r.y+230,218,320);Icon(card,8);Text(new Rect(card.x+15,card.y+20,188,65),AdventureRelics.Name(i)+" +"+a.Relics.Rank(i),center,true);Text(new Rect(card.x+20,card.y+95,178,110),a.Relics.EffectDescription(i),new GUIStyle(label){fontSize=14},true);bool own=a.Relics.Owns(i);GUI.enabled=a.CanManage&&(own?a.Relics.Rank(i)<3&&a.State.essence>=a.Relics.UpgradeCost(i):a.State.relicRewards>0);var choice=new Rect(card.x+16,card.y+246,186,47);if(Button(choice,own?a.Relics.Rank(i)>=3?"MAX":AdventureProgress.T("강화 ","Upgrade ","強化 ")+a.Relics.UpgradeCost(i):AdventureProgress.T("선택","Choose","選択"),true)){if(own)a.Relics.Upgrade(i);else a.ChooseRelic(i);}DrawCardFocus(card,choice);GUI.enabled=true;}}
 void DrawJournalRefuge(Rect r,AdventureProgress a){Text(new Rect(r.x+70,r.y+158,r.width-140,100),AdventureProgress.T("위험 단계는 쉼터에서 선택합니다. 승리한 단계 다음 단계가 열리며, 언제든 낮출 수 있습니다. 성장과 장비는 유지됩니다.","Choose danger at a refuge. Winning unlocks the next tier. You can lower it and keep your growth and gear.","休憩所で危険度を選択。勝利で次の段階が解放。下げても成長と装備は維持されます。"),new GUIStyle(dark){fontSize=17});for(int i=1;i<=3;i++){GUI.enabled=a.AtRefuge&&a.CanManage&&!a.EventRunning&&i<=a.State.unlockedDanger&&i!=a.State.danger;if(Button(new Rect(r.x+100+(i-1)*205,r.y+297,195,48),AdventureProgress.T("위험 ","Danger ","危険 ")+i+(a.State.danger==i?" ✓":""),true))a.ChangeDanger(i);GUI.enabled=true;}
  Text(new Rect(r.x+80,r.y+377,r.width-160,77),!a.State.bossUnlocked?AdventureProgress.T("조사 80점과 2구역 발견이 필요합니다","Requires 80 survey points and two regions","調査80と2地域の発見が必要です"):a.State.bossCleared?AdventureProgress.T("반복 도전 흔적 ","Rematch traces ","再挑戦の痕跡 ")+a.State.retry+" / 20":AdventureProgress.T("첫 달늑대 도전 · 권장 Lv.6–8","First Moonwolf challenge · Suggested Lv.6–8","初挑戦 · 推奨Lv.6–8"),dark);
  GUI.enabled=a.CanChallenge&&a.CanManage&&ClassCombat.Flat(player.transform.position-a.Gate).magnitude<3;if(Button(new Rect(r.x+130,r.y+480,540,49),AdventureProgress.T("달늑대 도전 · 보스 앞 쉼터에서","Challenge Moonwolf · At the boss refuge","狼に挑戦 · ボス前の休憩所から"),true)&&a.EnterBoss())Close();GUI.enabled=true;
 }
}
}
