using UnityEngine;
using System.Collections;
namespace WitchPlayground {
[DefaultExecutionOrder(-10)]
public sealed class ClassCombat:MonoBehaviour {
 WitchPlayer player;RpgProgress stats;HeroRoster roster;CharacterController motor;int action;float dodgeUntil,parryUntil,blockUntil,rollReady,backReady,basicReady,comboUntil;int combo;int backCharges=3;float backRechargeAt,basicUntil;int lifeStealTenths;bool moved;Vector3 motion;CombatSprite rainMarker;SlimeMonster bowTarget;
 public SlimeMonster AimedBowTarget=>player.IsCharging?bowTarget:player.WitchAutoTarget();
 public int ClassId=>roster?roster.Selected:0;
 public bool Evading=>Time.time<dodgeUntil;
 public bool Defending=>Time.time<parryUntil||Time.time<blockUntil;
 public bool Parrying=>Time.time<parryUntil;
 public bool MovementOverride=>moved;
 public Vector3 Velocity=>motion;
 public float RollCooldown=>Mathf.Max(0,rollReady-Time.time);
 public bool BasicAttacking=>ClassId==1&&Time.time<basicUntil&&player.IsSpellCasting;
 public int BackstepCharges{get{RefreshBacksteps();return backCharges;}}
 public float NextBackstepCharge{get{RefreshBacksteps();return backCharges<3?Mathf.Max(0,backRechargeAt-Time.time):0;}}
 public float BackCooldown=>ClassId==2?(BackstepCharges>0?0:NextBackstepCharge):Mathf.Max(0,backReady-Time.time);
 // Charges replenish serially. Spending another charge never restarts the active timer.
 void RefreshBacksteps(){while(backCharges<3&&Time.time>=backRechargeAt){backCharges++;backRechargeAt=backCharges<3?backRechargeAt+2:0;}}
 void SpendBackstep(){RefreshBacksteps();if(backCharges==3)backRechargeAt=Time.time+2;backCharges--;}

 public int ComboStep{get;private set;}public int ArrowsFired{get;private set;}public readonly System.Collections.Generic.List<float> ArrowTimes=new System.Collections.Generic.List<float>();
 public float BasicDamage=24;
 public float AttackDamage=>BasicDamage*stats.BasicMultiplier*(1+(stats.Rank(SpellId.Energy)-1)*.15f);
 void Awake(){player=GetComponent<WitchPlayer>();stats=GetComponent<RpgProgress>();roster=GetComponent<HeroRoster>();motor=GetComponent<CharacterController>();}
 public static Vector3 Flat(Vector3 d)=>Vector3.ProjectOnPlane(d,Vector3.up);
 public SlimeMonster Nearest(float range=18,Vector3? near=null){SlimeMonster best=null;float distance=float.PositiveInfinity;foreach(var e in FindObjectsByType<SlimeMonster>()){if(e.IsDead||Flat(e.transform.position-transform.position).magnitude>range)continue;float d=Flat(e.transform.position-(near??transform.position)).sqrMagnitude;if(d<distance){best=e;distance=d;}}return best;}
 public HitData Hit(float factor,Vector3 dir,bool critical=false)=>new HitData{damage=Mathf.RoundToInt(AttackDamage*factor*(critical?1.75f:1)),critical=critical,owner=player,direction=Flat(dir).normalized,knockback=critical?2:1,charge=0};
 public void ResetCombat(){Interrupt();rollReady=backReady=basicReady=comboUntil=0;combo=0;lifeStealTenths=0;bowTarget=null;backCharges=3;backRechargeAt=0;}
 public void Interrupt(){ForestSound.Instance?.ChargeStopped();var swordTrail=GetComponent<SwordTrail>();if(swordTrail)swordTrail.Stop();if(rainMarker)Destroy(rainMarker.gameObject);rainMarker=null;basicUntil=0;action++;StopAllCoroutines();moved=false;motion=Vector3.zero;dodgeUntil=parryUntil=blockUntil=0;}
 bool Available()=>!player.IsDead&&!player.IsSpellCasting&&!Evading&&!RpgUI.Blocking&&stats.CanUseWeapon();
 public bool SwordAttack(Vector3 target,bool mouse){if(!Available()||Time.time<basicReady)return false;if(!stats.Spend(2))return false;Vector3 dir=Flat(transform.forward).normalized;if(dir.sqrMagnitude<.1f)dir=transform.forward;transform.rotation=Quaternion.LookRotation(dir);if(Time.time>comboUntil)combo=0;ComboStep=++combo;bool crit=combo==3;if(crit)combo=0;comboUntil=Time.time+1.6f;float duration=crit?.8f:.6f;basicUntil=basicReady=Time.time+duration;player.PlayAction(crit?"SlashOverhead":ComboStep==1?"SlashRight":"SlashLeft",duration,false);SwordTrail.Begin(player,crit);StartCoroutine(SwordAdvance(action,dir,crit));StartCoroutine(SwordImpact(action,dir,crit,duration));return true;}
 // Contact occurs at 0.28/0.46 seconds in the imported sword clips.
 IEnumerator SwordAdvance(int token,Vector3 dir,bool critical){yield return new WaitForSeconds(critical?.30f:.15f);if(!Valid(token))yield break;float seconds=critical?.30f:.24f;float distance=critical?.65f:.42f;moved=true;float end=Time.time+seconds;while(Time.time<end&&Valid(token)){float step=distance/seconds*Time.deltaTime;foreach(var e in FindObjectsByType<SlimeMonster>()){if(e.IsDead)continue;Vector3 d=Flat(e.transform.position-transform.position);float along=Vector3.Dot(d,dir);float width=motor.radius+e.GetComponent<CharacterController>().radius;if(along>0&&(d-dir*along).magnitude<width)step=Mathf.Min(step,Mathf.Max(0,along-width-.08f));}motion=dir*(step/Mathf.Max(Time.deltaTime,.001f));yield return null;}moved=false;motion=Vector3.zero;}
 public void OnDamageDealt(int actualDamage){if(ClassId!=1||player.IsDead||actualDamage<=0)return;if(player.Health>=player.maxHealth){lifeStealTenths=0;return;}lifeStealTenths+=actualDamage;int heal=lifeStealTenths/10;lifeStealTenths%=10;if(heal>0)player.Heal(heal);if(player.Health>=player.maxHealth)lifeStealTenths=0;}
 IEnumerator SwordImpact(int token,Vector3 dir,bool crit,float duration){yield return new WaitForSeconds(crit?.46f:.28f);if(!Valid(token))yield break;var hit=Hit(1,dir,crit);if(AdventureProgress.Instance)hit=AdventureProgress.Instance.Relics.BasicHit(hit);hit.knockback=crit?6.2f:4;player.RecordShot(hit,dir);ForestSound.Play(crit?"slash_heavy":"slash",transform.position,.8f,ComboStep==2?.94f:1);Cone(dir,2.1f,110,hit,true);}
 public bool BeginBow(bool mouse){if(!Available())return false;bowTarget=mouse?null:player.WitchAutoTarget();if(!mouse&&!bowTarget){ForestSound.Play("ui_error");RpgUI.Toast(Loc.T("사거리 안에 적이 없습니다.","No enemy in range.","射程内に敵がいません。"));return false;}return true;}
 public bool FireBow(Vector3 target,bool mouse){if(ClassId!=2||player.IsDead||!stats.CanUseWeapon()||!mouse&&(!bowTarget||bowTarget.IsDead))return false;if(!stats.Spend(2))return false;Vector3 dir=mouse?Flat(target-transform.position).normalized:bowTarget&&!bowTarget.IsDead?Flat(bowTarget.HitPoint-transform.position).normalized:transform.forward;if(!mouse&&(!bowTarget||bowTarget.IsDead))return false;if(dir.sqrMagnitude<.1f)dir=transform.forward;transform.rotation=Quaternion.LookRotation(dir);var hit=Hit(1,dir,stats.CritOverride==1||(stats.CritOverride<0&&Random.value<stats.CritChance));if(AdventureProgress.Instance)hit=AdventureProgress.Instance.Relics.BasicHit(hit);Shoot(dir,hit,mouse?null:bowTarget);player.PlayAction("BowRelease",.22f,true);player.RecordShot(hit,dir);return true;}
 void Shoot(Vector3 dir,HitData hit,SlimeMonster target){ArrowsFired++;ArrowTimes.Add(Time.time);if(ArrowTimes.Count>64)ArrowTimes.RemoveAt(0);ArrowFlight.Fire(transform.position+Vector3.up*.85f+dir*.25f,dir,hit,target);ForestSound.Play("bow_release",transform.position,.8f);}
 public bool Skill(SpellId id,Vector3? point){if(!Available())return false;if(!stats.Learned(id)){ForestSound.Play("ui_error");RpgUI.Toast(Loc.T("레벨업 시 배울 수 있습니다.","Learn this on level up.","レベルアップで習得できます。"));return false;}if(!stats.CheckReady(id))return false;SlimeMonster target=null;
  if((ClassId==1&&id==SpellId.Frost)||(ClassId==2&&id==SpellId.Frost)){target=Nearest(ClassId==1?8:18,ClassId==2?point:null);if(!target){ForestSound.Play("ui_error");RpgUI.Toast(Loc.T("사거리 안에 적이 없습니다.","No enemy in range.","射程内に敵がいません。"));return false;}}
  if(ClassId==2&&id==SpellId.Heal?!stats.PrepareSkill(id):!stats.CommitSkill(id))return false;player.CancelCharge();int token=++action;
  if(ClassId==1){if(id==SpellId.Frost){player.PlayAction("DashSlash",.42f,false,true);StartCoroutine(DashStrike(token,target));}else if(id==SpellId.Meteor){Vector3 dir=point.HasValue?Flat(point.Value-transform.position).normalized:transform.forward;if(dir.sqrMagnitude<.1f)dir=transform.forward;transform.rotation=Quaternion.LookRotation(dir);player.PlayAction("FanSlash",.9f,false);StartCoroutine(Fan(token,dir));}else{parryUntil=Time.time+1.5f;player.PlayAction("Guard",1.5f,false,true);ForestSound.Play("shield_up",transform.position,.6f);CombatVisual.Shield(transform,1.5f);}}
  else {if(id==SpellId.Frost){ForestSound.Play("bow_draw",transform.position,.7f);player.PlayAction("TripleDraw",.9f,true);StartCoroutine(Triple(token,target));}else if(id==SpellId.Meteor){player.PlayAction("TrapSet",.5f,false);StartCoroutine(PlaceTrap(token));}else{Vector3 at=point??(Nearest()?Nearest().transform.position:transform.position+transform.forward*7);var d=Flat(at-transform.position);if(d.magnitude>18)at=transform.position+d.normalized*18;player.PlayAction("RainDraw",2,false);player.StartChannel(SpellId.Heal,2);StartCoroutine(Rain(token,GroundSpellTravel.GroundPosition(at,0)));}}
  return true;
 }
 bool Valid(int token)=>token==action&&!player.IsDead&&stats.Equipped;
 public void Cone(Vector3 dir,float radius,float angle,HitData hit,bool pushForward=false){foreach(var e in FindObjectsByType<SlimeMonster>()){Vector3 d=Flat(e.transform.position-transform.position);if(e.IsDead||d.magnitude>radius||Mathf.Abs(e.HitPoint.y-transform.position.y)>3||Vector3.Angle(dir,d)>angle*.5f)continue;if(Physics.Linecast(transform.position+Vector3.up*.65f,e.HitPoint,(1<<11)|(1<<13)))continue;var h=hit;h.direction=pushForward?dir:d.normalized;e.ReceiveHit(h);}}
 IEnumerator DashStrike(int token,SlimeMonster target){ForestSound.Play("dash",transform.position,.85f);CombatArt.Dash(transform.position,transform.forward);float age=0,nextGhost=0;moved=true;while(age<.25f&&Valid(token)&&target&&!target.IsDead){Vector3 d=Flat(target.transform.position-transform.position);if(d.magnitude<1.1f)break;motion=d.normalized*Mathf.Min(32,Mathf.Max(0,d.magnitude-.85f)/Mathf.Max(Time.deltaTime,.001f));transform.rotation=Quaternion.LookRotation(d);if(age>=nextGhost){CombatVisual.Ghost(player);nextGhost+=.045f;}age+=Time.deltaTime;yield return null;}moved=false;motion=Vector3.zero;if(Valid(token)&&target&&!target.IsDead&&Flat(target.transform.position-transform.position).magnitude<1.8f&&!Physics.Linecast(transform.position+Vector3.up*.5f,target.HitPoint,1<<11)){target.ReceiveHit(Hit(.5f,transform.forward));CombatArt.Dash(transform.position,transform.forward);CombatVisual.Slash(transform.position,transform.forward,new Color(.6f,.8f,1),1.3f,false);}}
 IEnumerator Fan(int token,Vector3 dir){yield return new WaitForSeconds(.4f);if(!Valid(token))yield break;ForestSound.Play("fan",transform.position,.9f);Cone(dir,3.6f,120,Hit(1.8f,dir));CombatVisual.Slash(transform.position,dir,new Color(1,.75f,.25f),3.6f,false);}
 IEnumerator Triple(int token,SlimeMonster target){yield return new WaitForSeconds(.3f);for(int i=0;i<3;i++){if(!Valid(token)||!target||target.IsDead)yield break;Vector3 d=Flat(target.HitPoint-transform.position).normalized;transform.rotation=Quaternion.LookRotation(d);player.PlayOverlay("BowRelease");Shoot(d,Hit(1-i*.1f,d),target);if(i<2)yield return new WaitForSeconds(.2f);}}
 IEnumerator PlaceTrap(int token){Vector3 at=GroundSpellTravel.GroundPosition(transform.position,.05f);yield return new WaitForSeconds(.25f);if(Valid(token))HuntingTrap.Place(at,player);}
 IEnumerator Rain(int token,Vector3 at){int channel=player.ChannelToken;rainMarker=CombatArt.Ground(at,true,3,12,2,.45f);while(player.ValidChannel(channel)&&player.Channel01<1)yield return null;bool fire=Valid(token)&&player.ValidChannel(channel);if(rainMarker)Destroy(rainMarker.gameObject);rainMarker=null;if(fire&&player.CompleteChannel(channel)){ArrowRain.Begin(at,6,Hit(.8f,Vector3.down));}}
 public bool TryEvade(Vector2 input){if(player.IsDead||RpgUI.Blocking||Evading||Defending||!player.Grounded)return false;if(input.sqrMagnitude<.01f)return false;bool back=input.y<-.5f;if(back?BackCooldown>0:RollCooldown>0)return false;if(player.IsSpellCasting&&!player.MobileSpell)return false;player.ClearBufferedInput();player.CancelCharge();Interrupt();Vector3 f=Flat(player.viewCamera.transform.forward).normalized,r=Flat(player.viewCamera.transform.right).normalized;Vector3 direction=(f*input.y+r*input.x).normalized;int token=action;
  if(back){if(ClassId==2)SpendBackstep();else backReady=Time.time+(ClassId==0?10:5);if(ClassId==1){blockUntil=Time.time+1.0f;player.PlayAction("Guard",1,false,true);ForestSound.Play("shield_up",transform.position,.6f);CombatVisual.Shield(transform,1);return true;}direction=-f;if(ClassId==0){AdventureProgress.Instance?.Relics.OnDodge();ForestSound.Play("blink",transform.position,.7f);dodgeUntil=Time.time+.25f;player.PlayAction("Cast",.25f,false,true);CombatVisual.Ghost(player);var start=transform.position;float dist=3.2f;if(Physics.SphereCast(start+Vector3.up*.5f,.3f,direction,out RaycastHit h,dist,(1<<11)|(1<<13)))dist=Mathf.Max(0,h.distance-.1f);var end=GroundSpellTravel.GroundPosition(start+direction*dist,.02f);if(Mathf.Abs(end.y-start.y)<3){player.Teleport(end);RpgVFX.Sprite(start+Vector3.up*.6f,0,1.5f,.4f);RpgVFX.Sprite(end+Vector3.up*.6f,0,1.5f,.4f);}return true;}AdventureProgress.Instance?.Relics.OnDodge();ForestSound.Play("backstep",transform.position,.65f);dodgeUntil=Time.time+.35f;player.PlayAction("Backstep",.35f,false,true);StartCoroutine(EvadeMove(token,direction,2,.35f));}
  else{AdventureProgress.Instance?.Relics.OnDodge();ForestSound.Play("roll",transform.position,.65f);rollReady=Time.time+.85f;dodgeUntil=Time.time+.55f;transform.rotation=Quaternion.LookRotation(direction);player.PlayAction("Roll",.55f,false,true);StartCoroutine(EvadeMove(token,direction,2.6f,.55f));}return true;
 }
 IEnumerator EvadeMove(int token,Vector3 dir,float distance,float seconds){moved=true;motion=dir*distance/seconds;for(float t=0;t<seconds&&token==action&&!player.IsDead;t+=Time.deltaTime)yield return null;moved=false;motion=Vector3.zero;}
 public bool AvoidDamage(SlimeMonster attacker){if(Evading){RpgVFX.EvadeText(transform.position+Vector3.up*.8f);return true;}if(Parrying){ForestSound.Play("parry",transform.position,.9f);if(attacker&&!attacker.IsDead){attacker.StunFor(2);RpgVFX.Impact(attacker.HitPoint,true);}CombatVisual.Shield(transform,.25f);return true;}if(Time.time<blockUntil){ForestSound.Play("block",transform.position,.65f);CombatVisual.Shield(transform,.2f);return true;}return false;}
}
}
