using UnityEngine;
using System.Collections;
namespace WitchPlayground {
public static class CombatVisual {
 static Material wood,steel,glow;static Mesh arrowhead;
 public static Material Glow{get{if(!glow){glow=new Material(Shader.Find("Sprites/Default"));glow.color=new Color(.5f,.8f,1,.5f);}return glow;}}
 public static GameObject Arrow(){if(!wood){wood=new Material(Shader.Find("Standard"));wood.color=new Color(.45f,.25f,.1f);steel=new Material(Shader.Find("Standard"));steel.color=new Color(.75f,.85f,1);steel.SetFloat("_Metallic",.7f);steel.EnableKeyword("_EMISSION");steel.SetColor("_EmissionColor",new Color(.25f,.55f,1)*.7f);}var root=new GameObject("Physical arrow");root.layer=9;Part(root,new Vector3(0,0,0),new Vector3(.025f,.025f,.62f),wood);var head=Part(root,new Vector3(0,0,.34f),new Vector3(.08f,.045f,.14f),steel);if(!arrowhead){arrowhead=new Mesh();arrowhead.vertices=new[]{new Vector3(0,0,1),new Vector3(-.5f,0,-.5f),new Vector3(.5f,0,-.5f),new Vector3(0,.5f,-.5f),new Vector3(0,-.5f,-.5f)};arrowhead.triangles=new[]{0,1,3,0,3,2,0,2,4,0,4,1,1,4,3,4,2,3};arrowhead.RecalculateNormals();}head.GetComponent<MeshFilter>().sharedMesh=arrowhead;Part(root,new Vector3(0,0,-.25f),new Vector3(.13f,.015f,.13f),steel);Part(root,new Vector3(0,0,-.25f),new Vector3(.015f,.13f,.13f),steel);return root;}
 static GameObject Part(GameObject root,Vector3 p,Vector3 s,Material m){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.layer=9;Object.Destroy(o.GetComponent<Collider>());o.transform.SetParent(root.transform,false);o.transform.localPosition=p;o.transform.localScale=s;o.GetComponent<Renderer>().sharedMaterial=m;o.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;return o;}
 public static GameObject Ring(Vector3 at,float radius,Color color,float seconds){var o=new GameObject("Skill boundary");var l=o.AddComponent<LineRenderer>();l.sharedMaterial=Glow;l.startColor=l.endColor=color;l.startWidth=l.endWidth=.05f;l.positionCount=65;for(int i=0;i<=64;i++){Vector3 p=at+new Vector3(Mathf.Cos(i*Mathf.PI/32),0,Mathf.Sin(i*Mathf.PI/32))*radius;l.SetPosition(i,GroundSpellTravel.GroundPosition(p,.075f));}Object.Destroy(o,seconds);return o;}
 public static void Slash(Vector3 at,Vector3 dir,Color color,float radius,bool reverse){CombatArt.Slash(at,dir,radius,reverse);}
 public static void Shield(Transform p,float duration){CombatArt.Shield(p,duration);}
 public static void Ghost(WitchPlayer p){var o=new GameObject("Dash afterimage");foreach(var skin in p.animator.GetComponentsInChildren<SkinnedMeshRenderer>()){if(!skin.enabled)continue;var mesh=new Mesh();skin.BakeMesh(mesh,true);var part=new GameObject("Afterimage skin");part.transform.SetParent(o.transform,false);part.transform.SetPositionAndRotation(skin.transform.position,skin.transform.rotation);part.transform.localScale=skin.transform.lossyScale;part.AddComponent<MeshFilter>().sharedMesh=mesh;var r=part.AddComponent<MeshRenderer>();r.sharedMaterial=Glow;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;part.AddComponent<GhostMesh>().mesh=mesh;}Object.Destroy(o,.3f);}
}
public sealed class GhostMesh:MonoBehaviour {public Mesh mesh;void OnDestroy(){if(mesh)Destroy(mesh);}}
public sealed class ArrowFlight:MonoBehaviour {
 public Vector3 direction;public HitData hit;public SlimeMonster target;public bool cosmetic;float age;bool lodged;public bool Lodged=>lodged;
 public static ArrowFlight Fire(Vector3 from,Vector3 dir,HitData damage,SlimeMonster homing=null,bool visualOnly=false){var o=CombatVisual.Arrow();o.transform.position=from;var a=o.AddComponent<ArrowFlight>();a.direction=dir.normalized;a.hit=damage;a.target=homing;a.cosmetic=visualOnly;if(!visualOnly)o.AddComponent<ArrowGleam>();return a;}
 void Update(){if(Time.timeScale==0||lodged)return;age+=Time.deltaTime;if(age>3){Destroy(gameObject);return;}float distance=26*Time.deltaTime;Vector3 at=transform.position;if(target){if(target.IsDead){Destroy(gameObject);return;}Vector3 delta=target.HitPoint-at;direction=delta.normalized;if(delta.magnitude<=distance+.16f){Lodge(target);return;}at+=direction*distance;}else if(cosmetic){at+=direction*distance;if(Physics.Raycast(at+Vector3.up*.2f,Vector3.down,out var floor,.4f,1<<10)){transform.position=floor.point;lodged=true;Destroy(gameObject,1);return;}}else{if(GroundSpellTravel.Step(ref at,direction,distance,.1f,.85f,out var enemy,out var impact)){transform.position=at;if(enemy)Lodge(enemy);else{lodged=true;Destroy(gameObject,1);}return;}}
  transform.position=at;if(direction.sqrMagnitude>.01f)transform.rotation=Quaternion.LookRotation(direction);
 }
 void Lodge(SlimeMonster e){if(!cosmetic){ForestSound.Play("arrow_hit",e.HitPoint,.6f);e.ReceiveHit(hit);}lodged=true;transform.position=e.HitPoint-direction*.18f;transform.rotation=Quaternion.LookRotation(direction);transform.SetParent(e.visual?e.visual:e.transform,true);gameObject.name="Lodged arrow";Destroy(gameObject,3);}
}
public sealed class HuntingTrap:MonoBehaviour {
 public WitchPlayer owner;public bool Triggered;public float ExpiresAt;GameObject ring;
 public static HuntingTrap Place(Vector3 at,WitchPlayer owner){ForestSound.Play("trap_set",at,.65f);var go=new GameObject("Hunting snare - 40 seconds");go.transform.position=at;var t=go.AddComponent<HuntingTrap>();t.owner=owner;t.ExpiresAt=Time.time+40;t.ring=CombatArt.Ground(at,true,2,1.6f,40,.7f).gameObject;t.ring.transform.SetParent(go.transform,true);return t;}
 void Update(){if(Time.timeScale==0)return;if(Time.time>=ExpiresAt){Destroy(gameObject);return;}foreach(var e in FindObjectsByType<SlimeMonster>()){if(e.IsDead||ClassCombat.Flat(e.transform.position-transform.position).magnitude>.7f||Mathf.Abs(e.transform.position.y-transform.position.y)>2)continue;Triggered=true;ForestSound.Play("trap_trigger",transform.position,.8f);e.RootFor(3);CombatArt.Ground(e.transform.position,true,2,1.8f,3,1);CombatArt.Burst(e.HitPoint,true,2,.9f,.5f);Destroy(gameObject);break;}}
}
public sealed class ArrowRain:MonoBehaviour {
 public int Ticks;public float radius;public HitData hit;
 public static ArrowRain Begin(Vector3 at,float radius,HitData hit){var o=new GameObject("Arrow rain - 3 seconds");o.transform.position=at;var r=o.AddComponent<ArrowRain>();r.radius=radius;r.hit=hit;return r;}
 IEnumerator Start(){ForestSound.Play("rain_start",transform.position,.8f);CombatArt.Ground(transform.position,true,3,radius*2,3,.32f);for(int i=0;i<6;i++){for(int n=0;n<22;n++){Vector2 v=Random.insideUnitCircle*radius;Vector3 p=GroundSpellTravel.GroundPosition(transform.position+new Vector3(v.x,0,v.y),0);ArrowFlight.Fire(p+Vector3.up*6,Vector3.down,hit,null,true);}yield return new WaitForSeconds(.5f);ForestSound.Play("rain_tick",transform.position,.65f);Ticks++;foreach(var e in FindObjectsByType<SlimeMonster>()){if(e.IsDead||ClassCombat.Flat(e.transform.position-transform.position).magnitude>radius||Mathf.Abs(e.transform.position.y-transform.position.y)>4)continue;var h=hit;h.knockback=0;e.ReceiveHit(h);CombatArt.Burst(e.HitPoint,true,1,.65f,.25f);var a=CombatVisual.Arrow();a.transform.position=e.HitPoint;a.transform.rotation=Quaternion.LookRotation(Vector3.down);a.transform.SetParent(e.visual?e.visual:e.transform,true);Destroy(a,3);}}Destroy(gameObject);}
}
// A visible nocked arrow follows the wrist-to-bow line while the upper-body layer draws.
[DefaultExecutionOrder(100)]public sealed class BowNock:MonoBehaviour {
 WitchPlayer p;HeroRoster roster;GameObject arrow;Transform left,right;LineRenderer bowstring;CombatSprite focus;
 void Start(){p=GetComponent<WitchPlayer>();roster=GetComponent<HeroRoster>();}
 void LateUpdate(){bool show=roster.Selected==2&&(p.IsCharging||(p.IsSpellCasting&&(p.ActionName=="RainDraw"||p.ActionName=="TripleDraw"||p.ActionName=="BowDraw")));if(!show){if(arrow)arrow.SetActive(false);if(focus)Destroy(focus.gameObject);return;}if(!arrow){arrow=CombatVisual.Arrow();arrow.name="Nocked arrow";bowstring=arrow.AddComponent<LineRenderer>();bowstring.sharedMaterial=CombatVisual.Glow;bowstring.startColor=bowstring.endColor=new Color(.8f,.75f,.6f);bowstring.startWidth=bowstring.endWidth=.01f;bowstring.positionCount=3;}if(!left||!right){foreach(var t in p.animator.GetComponentsInChildren<Transform>(true)){if(t.name=="Wrist.L")left=t;if(t.name=="Wrist.R")right=t;}}arrow.SetActive(true);Vector3 bow=p.transform.position+p.transform.forward*.45f+Vector3.up*.87f;Vector3 nock=right?right.position:bow-p.transform.forward*.35f;Vector3 direction=p.transform.forward;if(left){bow=left.position;}arrow.transform.position=Vector3.Lerp(nock,bow,.5f)+direction*.15f;arrow.transform.rotation=Quaternion.LookRotation(direction);if(!focus){focus=CombatArt.Burst(bow,true,0,.7f,1);focus.loop=true;focus.fixedFrame=1;}focus.transform.position=bow;focus.size=Mathf.Lerp(.38f,.95f,p.IsCharging?p.Charge01:.85f);focus.opacity=Mathf.Lerp(.25f,.8f,p.IsCharging?p.Charge01:.85f);focus.spin=55;bowstring.SetPosition(0,bow+Vector3.up*.37f);bowstring.SetPosition(1,nock);bowstring.SetPosition(2,bow-Vector3.up*.37f);}
 void OnDestroy(){if(arrow)Destroy(arrow);if(focus)Destroy(focus.gameObject);}
}
}
