using UnityEngine;
using System.Collections.Generic;
namespace WitchPlayground {
[DefaultExecutionOrder(80)]public sealed class VisualGrounding:MonoBehaviour {
 public Transform[] models;public float[] restMin;WitchPlayer player;Vector3[] original;SkinnedMeshRenderer[][] skins;Mesh[][] baked;int[][][] soles;float[] correction;readonly List<Vector3> vertices=new List<Vector3>();
 public float SoleGap{get;private set;}bool wasRolling;
 void Start(){player=GetComponent<WitchPlayer>();original=new Vector3[models.Length];skins=new SkinnedMeshRenderer[models.Length][];baked=new Mesh[models.Length][];soles=new int[models.Length][][];correction=new float[models.Length];for(int i=0;i<models.Length;i++){original[i]=models[i].localPosition;skins[i]=models[i].GetComponentsInChildren<SkinnedMeshRenderer>(true);baked[i]=new Mesh[skins[i].Length];soles[i]=new int[skins[i].Length][];for(int j=0;j<baked[i].Length;j++){baked[i][j]=new Mesh();var r=skins[i][j];var indices=new List<int>();var weights=r.sharedMesh.boneWeights;for(int v=0;v<weights.Length;v++){var w=weights[v];bool foot=(w.weight0>.45f&&r.bones[w.boneIndex0].name.ToLower().Contains("foot"))||(w.weight1>.45f&&r.bones[w.boneIndex1].name.ToLower().Contains("foot"));if(foot)indices.Add(v);}soles[i][j]=indices.ToArray();}}}
 void LateUpdate(){if(player.IsDead||original==null)return;bool rolling=player.IsSpellCasting&&player.ActionName=="Roll";for(int i=0;i<models.Length;i++){if(!models[i]||!models[i].gameObject.activeSelf)continue;var position=original[i];position.y-=restMin[i];models[i].localPosition=position;if(player.Grounded&&Physics.Raycast(transform.position+Vector3.up*.4f,Vector3.down,out RaycastHit hit,1.4f,1<<10)){if(Time.frameCount%3==0||correction[i]==0||rolling||wasRolling){float low=float.PositiveInfinity;for(int j=0;j<skins[i].Length;j++){var r=skins[i][j];r.BakeMesh(baked[i][j],true);baked[i][j].GetVertices(vertices);var m=r.transform.localToWorldMatrix;if(rolling){foreach(var v in vertices)low=Mathf.Min(low,m.m10*v.x+m.m11*v.y+m.m12*v.z+m.m13);}else foreach(var index in soles[i][j]){var v=vertices[index];low=Mathf.Min(low,m.m10*v.x+m.m11*v.y+m.m12*v.z+m.m13);}}if(!float.IsInfinity(low)){correction[i]=Mathf.Clamp(hit.point.y+.008f-low,rolling?-2.5f:-.4f,rolling?2.5f:.4f);SoleGap=low+correction[i]-hit.point.y;}}position.y+=correction[i];models[i].localPosition=position;}}wasRolling=rolling;}
 void OnDestroy(){if(baked!=null)foreach(var group in baked)foreach(var mesh in group)if(mesh)Destroy(mesh);}
}
}
