using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
namespace WitchPlayground {
public enum AdventureStage {Offer,Road,Purify,Gate,Boss,Reward,Camp,Herbs,Elite,Complete}
[DefaultExecutionOrder(-40)]public sealed class AdventureProgress:MonoBehaviour {
 public static AdventureProgress Instance;
 [Serializable]public class Data {public int version=1;public AdventureStage stage;public List<string> defeated=new List<string>();public int purified,herbs,sideDone;public int rewardSource=-1;public bool completionNotice;public AdventureRelics.Data relics=new AdventureRelics.Data();}
 public Data State=new Data();public AdventureStage Stage=>State.stage;public bool Ready{get;private set;}public bool BossActive=>Stage==AdventureStage.Boss;
 public Vector3 Camp{get;private set;}public Vector3 Arena{get;private set;}public Vector3 Gate{get;private set;}public Vector3 Guide{get;private set;}public Vector3 GuideHead{get;private set;}
 public string GuideMarker=>Stage==AdventureStage.Reward||Stage==AdventureStage.Complete||State.completionNotice?"!":Stage==AdventureStage.Offer||Stage==AdventureStage.Camp?"?":"";
 public Vector3[] Sites{get;private set;}public Vector3[] Herbs{get;private set;}
 public readonly Dictionary<string,SlimeMonster> Enemies=new Dictionary<string,SlimeMonster>();
 public AdventureNode Near{get;private set;}public AdventureRelics Relics{get;private set;}
 WitchPlayer player;RpgSession session;SlimeMonster slimeTemplate,beeTemplate;readonly List<AdventureNode> nodes=new List<AdventureNode>();float lastDamage=-100,nextScan,revealAt;bool configured;public bool TestFreezeEnemies;
 public static string T(string ko,string en,string ja)=>Loc.T(ko,en,ja);
 void Awake(){Instance=this;player=GetComponent<WitchPlayer>();session=GetComponent<RpgSession>();Relics=GetComponent<AdventureRelics>()??gameObject.AddComponent<AdventureRelics>();}
 void Start(){Configure();}
 public void Configure(){if(configured)return;configured=true;Camp=player.Spawn;var guide=FindObjectsByType<ForestInteractable>().First(n=>n.kind==ForestInteractable.Kind.NPC&&!n.healer);Guide=guide.transform.position;var renders=guide.GetComponentsInChildren<Renderer>();GuideHead=new Vector3(Guide.x,renders.Length>0?renders.Max(r=>r.bounds.max.y)+.35f:Guide.y+1.6f,Guide.z);
  var originals=FindObjectsByType<SlimeMonster>().Where(e=>!e.isBoss).ToArray();slimeTemplate=originals.First(e=>!e.isBee);beeTemplate=originals.First(e=>e.isBee);
  foreach(var e in originals)e.gameObject.SetActive(false);
  Sites=new[]{Safe(new Vector3(11,0,3)),Safe(new Vector3(-3,0,-5))};Arena=Safe(new Vector3(-8,0,-13),1);Gate=Safe(new Vector3(-3,0,-8));
  Herbs=new[]{Safe(new Vector3(5,0,18)),Safe(new Vector3(14,0,8)),Safe(new Vector3(9,0,0))};
  AddEnemy("road0",false,new Vector3(5,0,18),65);AddEnemy("road1",false,new Vector3(8,0,15),75);AddEnemy("road2",true,new Vector3(12,0,12),85);AddEnemy("road3",false,new Vector3(14,0,9),80);
  for(int site=0;site<2;site++){AddEnemy("site"+site+"a",false,Sites[site]+Vector3.right*1.5f,95);AddEnemy("site"+site+"b",true,Sites[site]-Vector3.right*1.5f,110);AddNode("site"+site,Sites[site]);}
  AddNode("gate",Gate);for(int i=0;i<3;i++)AddNode("herb"+i,Herbs[i]);
  AddEnemy("elite0",true,Sites[0],500,true);AddEnemy("elite1",true,Sites[0]+Vector3.forward*2,140);AddEnemy("elite2",false,Sites[0]-Vector3.forward*2,140);AddNode("elite",Sites[0]);
  Shader.SetGlobalVector("_AdventureClearing",new Vector4(Arena.x,Arena.y,Arena.z,5.5f));Shader.SetGlobalVector("_AdventureSiteA",new Vector4(Sites[0].x,0,Sites[0].z,2.8f));Shader.SetGlobalVector("_AdventureSiteB",new Vector4(Sites[1].x,0,Sites[1].z,2.8f));Ready=true;ApplyWorld();
 }
 // Probe the existing terrain and solid obstacle layers, preserving original artwork.
 public static Vector3 Safe(Vector3 wanted,float radius=.4f){for(int ring=0;ring<10;ring++)for(int i=0;i<(ring==0?1:16);i++){var q=wanted+Quaternion.Euler(0,i*22.5f,0)*Vector3.forward*(ring*.5f);if(!Physics.Raycast(q+Vector3.up*80,Vector3.down,out RaycastHit h,160,1<<10)||h.normal.y<.7f)continue;if(Physics.CheckCapsule(h.point+Vector3.up*(radius+.1f),h.point+Vector3.up*1.9f,radius,(1<<11)|(1<<13)))continue;return h.point+Vector3.up*.04f;}Debug.LogError("No adventure ground near "+wanted);return GroundSpellTravel.GroundPosition(wanted,.04f);}
 void AddEnemy(string id,bool bee,Vector3 at,int hp,bool elite=false){var e=Instantiate(bee?beeTemplate:slimeTemplate,Safe(at),Quaternion.identity);e.name="Adventure · "+id;e.QuestId=id;e.persistentDefeat=true;e.isElite=elite;e.maxHealth=hp;e.aggroRange=5;e.leashRange=7;e.TestIdle=TestFreezeEnemies;if(elite)e.transform.localScale*=1.25f;Enemies[id]=e;}
 void AddNode(string id,Vector3 at){var go=new GameObject("Objective · "+id);go.transform.position=at;var n=go.AddComponent<AdventureNode>();n.Id=id;n.Adventure=this;nodes.Add(n);}
 bool GroupEnabled(string id){if(id.StartsWith("road"))return Stage==AdventureStage.Road;if(id.StartsWith("site"))return Stage==AdventureStage.Purify;if(id.StartsWith("elite"))return Stage==AdventureStage.Elite;return false;}
 public void ApplyWorld(){if(!Ready)return;foreach(var pair in Enemies){bool active=GroupEnabled(pair.Key)&&!State.defeated.Contains(pair.Key);var e=pair.Value;if(e.gameObject.activeSelf!=active){e.gameObject.SetActive(active);if(active)e.ResetMonster();}e.TestIdle=TestFreezeEnemies;}foreach(var n in nodes)n.gameObject.SetActive(NodeVisible(n.Id));if(!BossActive)MoonwolfEvent.Instance?.ResetEncounter();}
 public bool NodeVisible(string id)=>id=="gate"?(Stage==AdventureStage.Gate):id=="elite"?Stage==AdventureStage.Elite:id.StartsWith("site")?Stage==AdventureStage.Purify&&(State.purified&(1<<(id[4]-'0')))==0:id.StartsWith("herb")&&Stage==AdventureStage.Herbs&&(State.herbs&(1<<(id[4]-'0')))==0;
 public int RoadKills=>State.defeated.Count(id=>id.StartsWith("road"));public int SiteCount=>BitCount(State.purified);public int HerbCount=>BitCount(State.herbs);static int BitCount(int n){int count=0;while(n>0){count+=n&1;n>>=1;}return count;}
 public bool GroupDead(string prefix)=>Enemies.Keys.Where(k=>k.StartsWith(prefix)).All(k=>State.defeated.Contains(k));
 public void NewAdventure(){Configure();State=new Data();Relics.Import(State.relics);player.SetCheckpoint(Camp);player.Teleport(Camp);lastDamage=-100;ApplyWorld();}
 public string Export(){State.relics=Relics.State;return JsonUtility.ToJson(State);}
 public void Import(string json,bool oldBoss){Configure();State=string.IsNullOrEmpty(json)?new Data{stage=oldBoss?AdventureStage.Reward:AdventureStage.Offer,rewardSource=oldBoss?0:-1}:JsonUtility.FromJson<Data>(json);State.defeated=State.defeated??new List<string>();Relics.Import(State.relics);if(Stage==AdventureStage.Boss){State.stage=AdventureStage.Gate;player.SetCheckpoint(Gate);player.Teleport(Gate);}if(string.IsNullOrEmpty(json)){player.SetCheckpoint(oldBoss?Gate:Camp);player.Teleport(oldBoss?Gate:Camp);}lastDamage=-100;ApplyWorld();}
 void SetStage(AdventureStage stage){State.stage=stage;ApplyWorld();session.Save();}
 public void TalkGuide(){if(State.completionNotice){State.completionNotice=false;session.Save();}if(Stage==AdventureStage.Offer||Stage==AdventureStage.Camp||Stage==AdventureStage.Complete)RpgUI.Instance.Open(RpgUI.Window.Adventure);else RpgUI.Toast(Objective);}
 public bool AcceptMain(){if(Stage!=AdventureStage.Offer)return false;SetStage(AdventureStage.Road);RpgUI.Toast(player.Combat.ClassId==1?T("J/좌클릭: 가까운 적을 향해 전진 공격","J / LMB: advance toward the nearest enemy","J/左クリック：近くの敵へ前進攻撃"):T("J는 자동 조준 · 좌클릭은 커서 조준","J auto-aims · Left click aims at cursor","Jで自動照準 · 左クリックで手動照準"));return true;}
 public void EnemyDefeated(SlimeMonster enemy){if(!Ready||enemy.QuestId==""||State.defeated.Contains(enemy.QuestId))return;State.defeated.Add(enemy.QuestId);if(Stage==AdventureStage.Road&&RoadKills>=4)SetStage(AdventureStage.Purify);else session.Save();}
 public void BossDefeated(){if(Stage!=AdventureStage.Boss)return;session.BossDefeated=true;State.rewardSource=0;State.stage=AdventureStage.Reward;foreach(var n in nodes)n.gameObject.SetActive(false);revealAt=Time.time+1.8f;var freed=RpgVFX.Sprite(Arena+Vector3.up,3,5,2);freed.tint=new Color(.65f,.85f,1);ForestSound.Play("upgrade",Arena,.8f);session.Save();}
 public bool Interact(string id){if(!Ready||!NodeVisible(id)||player.IsDead||RpgUI.Blocking)return false;var node=nodes.First(n=>n.Id==id);if(ClassCombat.Flat(node.transform.position-player.transform.position).magnitude>2.4f)return false;if(id=="gate"){player.SetCheckpoint(Gate);player.RestoreHealth();player.ProtectArrival();session.Save();RpgUI.Instance.Open(RpgUI.Window.Adventure);return true;}
  if(id.StartsWith("site")||id=="elite"){if(!GroupDead(id)){RpgUI.Toast(T("주변의 표시된 적을 먼저 처치하세요.","Defeat the marked enemies first.","先に周囲の目標の敵を倒しましょう。"));return false;}if(id=="elite"){State.sideDone|=2;State.rewardSource=2;SetStage(AdventureStage.Reward);}else{State.purified|=1<<(id[4]-'0');RpgVFX.Heal(node.transform.position);ForestSound.Play("upgrade",node.transform.position,.7f);SetStage(SiteCount==2?AdventureStage.Gate:AdventureStage.Purify);}}
  else{State.herbs|=1<<(id[4]-'0');ForestSound.Play("pickup",node.transform.position,.7f);RpgVFX.Heal(node.transform.position);if(HerbCount==3){State.sideDone|=1;State.rewardSource=1;SetStage(AdventureStage.Reward);}else{ApplyWorld();session.Save();}}
  return true;
 }
 public bool EnterBoss(){if(Stage!=AdventureStage.Gate||ClassCombat.Flat(player.transform.position-Gate).magnitude>3)return false;State.stage=AdventureStage.Boss;ApplyWorld();MoonwolfEvent.Instance.SummonAt(Arena);session.Save();return true;}
 public bool ChooseRelic(int id){if(Stage!=AdventureStage.Reward||State.rewardSource<0||!Relics.Award(id))return false;State.rewardSource=-1;State.completionNotice=true;ForestSound.Play("upgrade");State.stage=State.sideDone==3?AdventureStage.Complete:AdventureStage.Camp;ApplyWorld();player.CancelChannel();player.Combat.Interrupt();player.SetCheckpoint(Camp);player.Respawn();Camera.main.GetComponent<PlaygroundView>().Snap();player.ProtectArrival();session.Save();return true;}
 public bool AcceptSide(int id){if(Stage!=AdventureStage.Camp||id<0||id>1||(State.sideDone&(1<<id))!=0)return false;State.completionNotice=false;SetStage(id==0?AdventureStage.Herbs:AdventureStage.Elite);return true;}
 public void PlayerDamaged(){lastDamage=Time.time;}
 public void OnRespawn(){Relics.ClearTemporary();if(BossActive){State.stage=AdventureStage.Gate;ApplyWorld();}session.Save();}
 public bool CanReturnCamp=>!player.IsDead&&!BossActive&&!player.IsChanneling&&!player.IsCharging&&Time.time-lastDamage>=5&&!FindObjectsByType<SlimeMonster>().Any(e=>!e.IsDead&&ClassCombat.Flat(e.transform.position-player.transform.position).magnitude<8);
 public bool ReturnCamp(){if(!CanReturnCamp){RpgUI.Toast(T("주변 적과 거리를 벌린 뒤 귀환하세요.","Move away from enemies before returning.","敵から離れてから帰還してください。"));return false;}player.SetCheckpoint(Camp);player.Respawn();Camera.main.GetComponent<PlaygroundView>().Snap();player.ProtectArrival();session.Save();return true;}
 void Update(){if(!Ready||!session.Playing)return;Shader.SetGlobalVector("_AdventureView",new Vector4(Arena.x,Arena.y,Arena.z,ClassCombat.Flat(player.transform.position-Arena).magnitude<12?1:0));if(BossActive&&!player.IsDead&&ClassCombat.Flat(player.transform.position-Arena).magnitude>20){State.stage=AdventureStage.Gate;ApplyWorld();RpgUI.Toast(T("전투에서 벗어났습니다. 보스가 회복합니다.","Encounter left. The boss recovers.","戦闘から離れました。ボスが回復します。"));session.Save();}if(Stage==AdventureStage.Reward&&Time.time>=revealAt&&RpgProgress.Instance.PendingChoices==0&&RpgUI.Instance.ActiveWindow==RpgUI.Window.None&&!player.IsDead)RpgUI.Instance.Open(RpgUI.Window.Adventure);if(RpgUI.Blocking){Near=null;return;}if(Time.time>=nextScan){nextScan=Time.time+.1f;Near=nodes.Where(n=>n.gameObject.activeSelf&&ClassCombat.Flat(n.transform.position-player.transform.position).magnitude<2.4f).OrderBy(n=>(n.transform.position-player.transform.position).sqrMagnitude).FirstOrDefault();}if(!player.TestControl&&Near&&Input.GetKeyDown(KeyCode.E))Interact(Near.Id);}
 public Vector3 Target {get{if(!Ready)return transform.position;if(Stage==AdventureStage.Offer||Stage==AdventureStage.Camp||Stage==AdventureStage.Complete)return Guide;if(Stage==AdventureStage.Gate)return Gate;if(BossActive||Stage==AdventureStage.Reward)return Arena;if(Stage==AdventureStage.Road)return Enemies.Where(e=>e.Key.StartsWith("road")&&!State.defeated.Contains(e.Key)).OrderBy(e=>(e.Value.transform.position-player.transform.position).sqrMagnitude).Select(e=>e.Value.transform.position).FirstOrDefault();return nodes.Where(n=>n.gameObject.activeSelf).OrderBy(n=>(n.transform.position-player.transform.position).sqrMagnitude).Select(n=>n.transform.position).FirstOrDefault();}}
 public string Objective=>Stage==AdventureStage.Offer?T("루미에게 숲길 의뢰 받기","Speak to Lumi at camp","ルミから森の依頼を受ける"):Stage==AdventureStage.Road?T("길목의 적 처치 ","Clear the road: ","道の敵を撃破 ")+RoadKills+" / 4":Stage==AdventureStage.Purify?T("오염 정화 ","Cleanse corruption: ","汚染を浄化 ")+SiteCount+" / 2":Stage==AdventureStage.Gate?T("달늑대 앞 쉼터에서 E","Press E at the Moonwolf refuge","銀月の狼の前の休憩所でE"):BossActive?T("은빛 달늑대의 저주 풀기","Break the Moonwolf's curse","銀月の狼の呪いを解く"):Stage==AdventureStage.Reward?T("모험의 보상 선택","Choose your adventure reward","冒険の報酬を選ぶ"):Stage==AdventureStage.Camp?T("루미에게 다음 의뢰 선택","Choose a new request with Lumi","ルミと次の依頼を選ぶ"):Stage==AdventureStage.Herbs?T("달빛 약초 회수 ","Gather moon herbs: ","月光草を集める ")+HerbCount+" / 3":Stage==AdventureStage.Elite?T("정예 꿀벌 처치 후 오염 정화","Defeat the elite bee and cleanse","精鋭蜂を倒し汚染を浄化"):T("이번 모험 완료 · 숲을 자유롭게 둘러보세요","Adventure complete · Explore freely","冒険完了 · 自由に森を探索できます");
 public string Hint=>Stage==AdventureStage.Road?T("금색 목적지로 이동 · J/좌클릭 공격","Follow gold marker · J / LMB attack","金色の目印へ · J/左クリック攻撃"):Stage==AdventureStage.Purify||Stage==AdventureStage.Elite?T("주변 적 정리 후 빛나는 지점에서 E","Defeat guards, then press E at the light","敵を倒して光る場所でE"):BossActive?T("붉은 예고 범위를 피해 회피하세요","Dodge out of the warning areas","攻撃の予告範囲から回避"):Stage==AdventureStage.Herbs?T("초록빛 약초 가까이에서 E","Press E beside the green herbs","緑の薬草のそばでE"):T("금색 미니맵 표시는 현재 목적지입니다","Gold minimap marker: current objective","ミニマップの金色は現在の目的地");
 void OnDestroy(){if(Instance==this){Instance=null;Shader.SetGlobalVector("_AdventureView",Vector4.zero);Shader.SetGlobalVector("_AdventureClearing",Vector4.zero);Shader.SetGlobalVector("_AdventureSiteA",Vector4.zero);Shader.SetGlobalVector("_AdventureSiteB",Vector4.zero);}}
}
}
