using UnityEngine;
using System;
namespace WitchPlayground {
[DefaultExecutionOrder(-70)]public sealed class RpgSession:MonoBehaviour {
 static bool returningToTitle;public static RpgSession Instance;public bool Playing{get;private set;}public bool Creating;public string PlayerName="";public int Hero;public int Kills;public bool BossDefeated;public string Notice="";
 public bool Testing=>RpgProgress.Instance&&RpgProgress.Instance.TestSession;
 public bool AllowTestStorage;string SaveKey=>Testing?"WitchRPG.Test.v4":"WitchRPG.Save.v4";public void ShowTitleForTest(){Playing=false;}
 public bool HasSave=>PlayerPrefs.HasKey(SaveKey)||PlayerPrefs.HasKey("WitchRPG.Progress.v1");
 void Awake(){Instance=this;Playing=!returningToTitle&&Testing&&Array.IndexOf(Environment.GetCommandLineArgs(),"--v4-ui-test")<0;returningToTitle=false;if(!Testing||Array.IndexOf(Environment.GetCommandLineArgs(),"--adventure-verify")>=0)gameObject.AddComponent<AdventureProgress>();if(Testing){PlayerName="Test";Loc.Language=0;}}
 public bool NewGame(string name,int hero){name=(name??"").Trim();if(name.Length<1||name.Length>12){Notice=Loc.T("이름은 1~12자로 입력하세요.","Enter a name (1–12 characters).","名前を1〜12文字で入力してください。");return false;}ForestSound.Play("ui_confirm");PlayerName=name;Hero=Mathf.Clamp(hero,0,2);Kills=0;BossDefeated=false;RpgProgress.Instance.ResetProgress();GetComponent<HeroRoster>().Select(Hero);Playing=true;Creating=false;Time.timeScale=1;AdventureProgress.Instance?.NewAdventure();GetComponent<WitchPlayer>().Respawn();Camera.main.GetComponent<PlaygroundView>().ResetPracticeCamera();GetComponent<HeroRoster>().PlayIntro();GetComponent<WitchPlayer>().ProtectArrival();Save();return true;}
 [Serializable]class SaveData {public string name,progress,adventure;public int hero,kills,language,width,height,cameraVersion;public bool boss,shadows;public float yaw,pitch,zoom;public Vector3 position,checkpoint;}
 public void Save(){if((Testing&&!AllowTestStorage)||!Playing)return;var p=GetComponent<WitchPlayer>();var view=Camera.main.GetComponent<PlaygroundView>();var options=FindAnyObjectByType<ForestOptions>();var d=new SaveData{adventure=AdventureProgress.Instance?AdventureProgress.Instance.Export():"",cameraVersion=PlaygroundView.SettingsVersion,name=PlayerName,hero=Hero,kills=Kills,boss=BossDefeated,progress=RpgProgress.Instance.Export(),language=Loc.Language,shadows=options.EnvironmentShadows,yaw=view.yaw,pitch=view.pitch,zoom=Camera.main.orthographicSize,width=Screen.width,height=Screen.height,position=p.IsDead?p.Spawn:p.transform.position,checkpoint=p.Spawn};PlayerPrefs.SetString(SaveKey,JsonUtility.ToJson(d));SaveSettings();}
 public void SaveSettings(){if(Testing)return;var v=Camera.main.GetComponent<PlaygroundView>();DeveloperPanel.Instance?.SaveTuning();PlayerPrefs.SetInt("WitchRPG.CameraVersion",PlaygroundView.SettingsVersion);PlayerPrefs.SetInt("WitchRPG.Language",Loc.Language);PlayerPrefs.SetFloat("WitchRPG.CameraYaw",v.yaw);PlayerPrefs.SetFloat("WitchRPG.CameraPitch",v.pitch);PlayerPrefs.SetFloat("WitchRPG.CameraZoom",Camera.main.orthographicSize);PlayerPrefs.SetInt("WitchRPG.Width",Screen.width);PlayerPrefs.SetInt("WitchRPG.Height",Screen.height);PlayerPrefs.SetInt("Forest.EnvironmentShadows",FindAnyObjectByType<ForestOptions>().EnvironmentShadows?1:0);PlayerPrefs.Save();}
 public bool LoadGame(){try{var p=GetComponent<WitchPlayer>();string adventure="";string json=PlayerPrefs.GetString(SaveKey,"");if(json.Length==0){RpgProgress.Instance.Import(PlayerPrefs.GetString("WitchRPG.Progress.v1",""));PlayerName="Yurika";Hero=0;Kills=0;BossDefeated=false;}else{var d=JsonUtility.FromJson<SaveData>(json);RpgProgress.Instance.Import(d.progress);PlayerName=d.name;Hero=d.hero;Kills=d.kills;BossDefeated=d.boss;adventure=d.adventure;p.SetCheckpoint(d.checkpoint);p.Teleport(d.position);Loc.Language=d.language;var view=Camera.main.GetComponent<PlaygroundView>();if(d.cameraVersion>=PlaygroundView.SettingsVersion){view.yaw=d.yaw;view.pitch=d.pitch;Camera.main.orthographicSize=d.zoom;}else view.FactoryCamera();FindAnyObjectByType<ForestOptions>().SetEnvironmentShadows(d.shadows);}AdventureProgress.Instance?.Import(adventure,BossDefeated);GetComponent<HeroRoster>().Select(Hero);Playing=true;Creating=false;Time.timeScale=1;RpgProgress.Instance.RefreshStats();p.RestoreHealth();p.ProtectArrival();Camera.main.GetComponent<PlaygroundView>().Snap();ForestSound.Play("ui_confirm");return true;}catch(Exception e){ForestSound.Play("ui_error");Notice=Loc.T("저장 파일을 읽지 못했습니다.","Could not load the save.","セーブを読み込めませんでした。");Debug.LogWarning(e.Message);return false;}}
 public void RegisterKill(){Kills++;Save();}
 // Reloading clears outstanding projectiles, casts and enemy state before loading another adventure.
 public void ReturnToTitle(){ForestSound.Instance?.StopWorld();ForestSound.Play("ui_back");Save();SaveSettings();if(!Testing)PlayerPrefs.Save();GetComponent<WitchPlayer>().CancelCharge();GetComponent<ClassCombat>().Interrupt();returningToTitle=true;Playing=false;Creating=false;Time.timeScale=1;RpgUI.ClearToast();RpgVFX.Texts.Clear();UnityEngine.SceneManagement.SceneManager.LoadScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene().buildIndex);}
 public void Quit(){Save();SaveSettings();Application.Quit();}
 void OnApplicationQuit(){Save();}
}
}
